#+OPTIONS: ^:{} ^:nil _:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
#+HTML_HEAD: <link rel="stylesheet" href="guide.css"></link>
#+TITLE: The GM's Guide to "Agents of Edgewatch"
* Introduction
** Spoiler Warning

You're viewing a community-sourced Gamemaster's Guide to running the /Agents of Edgewatch/ Adventure Path from Paizo.

**This is entirely spoilers, by definition.**
** In Progress

As of November 2021, this guide is in progress and development. Your editor is compiling it as they run AoE for their group, so things will generally be added as the game progresses through 2021 and the first half of 2022.

See the [[Colophon][Colophon]] for how you can help contribute.

* Adventure Path Overview

_Agents of Edgewatch_ is the story of the player characters -- the titular
Agents of Edgewatch -- and their journey to understand and defeat the threat
of the Twilight Four, a cabal of devotees of Norgorber in their attempt to
take control of Absalom.

In Book 1, the Agents will come up through the ranks.

In Book 2, the Agents will defeat the first of the Twilight Four — The Skinner and her murderous cult.

In Book 3, the Agents will foil the plans second of the Twilight Four — The Infector and his attempt to poison thousands.

In Book 4, the Agents will infiltrate The Infector's temple, capture, and hold them … but ultimately will be framed and arrested.

In Book 5, the Agents will first infiltrate and then break out of Absalom's high-security prison, then turning their attention to the third of the Twilight Four — The Rumormonger.

In Book 6, the Agents will obtain an artifact they need to defeat the fourth of the Twilight Four — The Gray Queen, newly empowered by fulfilling the terms of the Twilight Four's contract with Norgorber.
* Meta
** Adventure Path Length

This – of course – is going to vary dramatically based on the table at which the game is being run, how many side-quests and how much character-service is done, &c.

Based naïvely on the idea that characters should advance in level every 3-4 gaming sessions, a Level 1 - 20 Adventure should take between 55 and 80 sessions, or 1 - 1.5 years at 1 session/week.

This seems to be supported by the experience at some tables, with people reporting "1-2 years" to finish an AP.

[[http:cite:paizo-forums-rzs4349c_18][On the Paizo Forums, Kazimir_980 reports taking 7 3-to-6-hour sessions to get through book 1.]]

On Reddit, u/DragoldC42's group took 9 months for the entire AP:
#+BEGIN_QUOTE
Last Friday I have finished running a 9-month long campaign in agents of edgewatch.
#+END_QUOTE
— cite:reddit-n39df5

[[http:cite:reddit-q9a8a1][u/Merithras asked a question that got some good responses, as well.]]

** Difficulty

Like many APs, the Agents of Edgewatch is considered by some to be … "tuned hot" … "spicy" … "extremely deadly for PCs" … a "TPK machine".

- [[https://www.reddit.com/r/Pathfinder2e/comments/oknoo0/agents_of_edgewatch_catacombs_are_a_death_trap/h59ksqb/?utm_source=reddit&utm_medium=web2x&context=3][Some people saying this might be outliers, though.]]

- The bulk of the discussion at [[https://www.reddit.com/r/Pathfinder2e/comments/oknoo0/agents_of_edgewatch_catacombs_are_a_death_trap/]["Catacombs are a death trap"]] is about the general perception of the difficulty of these early APs.

*** Encounter Rebalancing
In general, in PF2E, when rebalancing encounters for a larger party, you should prefer "more weaker" enemies, not "single up-leveled" enemies.

- the PF2 math is too tight for even-stronger enemies
- too hard to land hits, too high chances of crits (both directions)

Thoughout this guide, we'll give notes on how others re-balanced.

** On Role-Playing Police
**** Policing
**** Requisitioning and Civil Asset Forfeiture

 #+BEGIN_QUOTE
 - The agents, as policemen, being able to confiscate property freely feels weird in this part of the adventure, when they are mostly dealing with ordinary citizens. My group didn’t really care that much, but it was a good topic to raise in session zero and clear out our preferences on anyway. It's very easy in any case to just give the characters a salary.In my experience, later on in the AP, when the agents are dealing with criminals and cults, it feels much more justified to use what they can take, or to give it back for a bounty.
 #+END_QUOTE
 — cite:reddit-n39df5

**** Non-Lethal Damage
** United Paizo Workers

In October 2021 – about 1 year after the final book of _Agents of Edgewatch_ was published (in December 2020) – Paizo labor organized and formed the creation of the _United Paizo Workers_.

[[https://www.reddit.com/r/Pathfinder2e/comments/q85tgm/the_new_paizo_unions_logo_is_a_reference_to_the/][Their logo is a reference to the Kobold Worker's Union from Book 1, Chapter 2.

* Enemy Makeup and Composition
** Book 1

*Summary by Type*

    | *type*         | *ch 1* | *ch 2* | *ch 3* | *ch 4* |
    | *humanoid*     |      8 |     15 |      4 |      4 |
    | *aberration*   |      1 |        |      1 |      1 |
    | *animal/beast* |      8 |      4 |      2 |      1 |
    | *construct*    |        |        |        |      4 |
    | *devil*        |        |        |        |      1 |
    | *elemental*    |        |        |        |      2 |
    | *fey*          |        |        |        |      1 |
    | *fiend*        |        |        |      2 |        |
    | *ooze*         |        |        |      1 |      1 |
    | *undead*       |      4 |        |      3 |        |


    | *chapter 1*          |  *lvl* | *traits*                |
    |----------------------+--------+-------------------------|
    | 6× Human             | -1 - 2 | humanoid                |
    | 2× Goblin            |     -1 | humanoid                |
    | 4× Skeleton          |     -1 | undead                  |
    | 1× Cockatrice        |      3 | animal/beast            |
    | 1× Owlbear           |      3 | animal/beast            |
    | 1× Rust Monster      |      4 | aberration              |
    | 2× Hyenas            |      0 | animal/beast            |
    | 1× Giant Viper       |      2 | animal/beast            |
    | 1× Almiraj           |      1 | animal/beast            |
    | 1× Flash Beetle      |     -1 | animal/beast            |
    | 1× Ankhrav           |      3 | animal/beast            |
    |----------------------+--------+-------------------------|
    | *chapter 2*          |  *lvl* | *traits*                |
    |----------------------+--------+-------------------------|
    | 15× Kobold           |  0 - 2 | humanoid                |
    | 1× Hunting Spider    |      1 | animal/beast            |
    | 3× Bloodseeker       |     -1 | animal/beast            |
    | FIXME: hazards       |        |                         |
    |----------------------+--------+-------------------------|
    | *chapter 3*          |  *lvl* | *traits*                |
    |----------------------+--------+-------------------------|
    | 1× Gelatinous Cube   |      3 | ooze                    |
    | 3× Ghoul             |      1 | undead                  |
    | 2× Ratfolk           |      2 | humanoid                |
    | 2× Calgini Creepers  |      2 | humanoid                |
    | 2× Vargouilles       |      2 | animal/beast, fiend     |
    | 1× Grick             |      3 | aberration              |
    |----------------------+--------+-------------------------|
    | *chapter 4*          |  *lvl* | *traits*                |
    |----------------------+--------+-------------------------|
    | 1× Mimic             |      4 | aberration              |
    | 1× Hidden Chute      |      3 | hazard                  |
    | 1× Flying Guillotine |      5 | hazard                  |
    | 2× Summoning Rune    |      5 | hazard                  |
    | 2× Cinder Rat        |      3 | elemental               |
    | 1× Barbazu Devil     |      5 | devil, fiend            |
    | 1× Canopy Drop       |      4 | hazard                  |
    | 1× Giant Viper       |      2 | animal/beast            |
    | 2× Humanoid          |      2 | humanoid                |
    | 1× Redcap            |      4 | fey                     |
    | 1× Ralso             |      4 | humanoid                |
    | 2× Soulbound Dolls   |      2 | construct               |
    | 1× Attic Whisperer   |      4 | undead                  |
    | 2× Animated Statue   |      3 | construct               |
    | 1× Gas Trap          |      5 | hazard                  |
    | 1× Plunger Chute     |      3 | hazard                  |
    | 6× Pickled Punk      |      1 | undead                  |
    | 4× Shredskin         |      2 | undead                  |
    | 1× Ochre Jelly       |      6 | ooze                    |
    | 3× Wight             |      3 | undead                  |
    | 1× Binumir           |      3 | undead                  |
    | 1× Henrid Pratchett  |      6 | humanoid, serial killer |

** Book 2

    | *Creature*      | *Level* | *Ch* | *traits*     |
    |-----------------+---------+------+--------------|
    | 2× Wasp Swarm   |       4 |  2-1 | animal/beast |
    | 2× Ether Spider |       4 |  2-1 | animal/beast |
    | 1× Xill         |       6 |  2-1 | aberration   |
    | 2× Riding Dog   |       2 |  2-1 | animal/beast |
    | 15× Humanoid    |     2-5 |  2-1 | humanoid     |
    | 1× Bunyip       |       3 |  2-1 | animal/beast |

* Party Makeup and Composition

** Alchemist

An Alchemist character who is a follower of Norgorber – even in his less-offensive "Blackfingers" aspect – might still create dramatic tension with the party, as it becomes clear early on that the Agents are on the trail of a muder cult of Norgorberites.

A main plot point from Book 1 through the end of Book 3 is the poison called "Blackfinger Blight".

A key event in Book 4 is the "Noxious Retort", a world-class Alchemical conference at the Norgorber temple in Absalom; the PCs will need to infiltrate this conference to advance the plot.

The Temple of Norgorber and NPCs in the AP can be used to great effect to provide foreshadowing, or even just as a downtime location if the PC wants formula or reagents.

On the other hand, "DragoldC42" points out that this does lead to lots of enemies with poison resistance…

#+BEGIN_QUOTE
([Poisoner-archetype was] Bad choice for the AP in retrospect, there are a metric ton of poison
resisting enemies in this campaign)
#+END_QUOTE
— cite:reddit-n39df5

** Champion

There is a non-trivial presence of undead throughout the AP. A Champion who takes [[https://2e.aonprd.com/Feats.aspx?ID=221][Shining Oath]] will have plenty of opportunity to weave that into their play:

#+BEGIN_QUOTE
You’ve sworn an oath to put the undead to rest. Add the following tenet to your champion’s code after the other tenets: “You must end the existence of undead you encounter as long as you have a reasonable chance of success; in the unlikely event you find a good undead, you can try to work out a more peaceful way to help it recover from its undead state rather than destroying it in combat, such as helping it complete its unfinished business and find peace.”
#+END_QUOTE

As a central part of Book 5 is teaming up with the "zealborn" undead master criminal Miogimo to advance the Agent's interests, this oath can create plenty of dramatic tension to play out, as well.

** AP-provided Archetypes
*** Jalmeri Heavenseeker Archetype (Book 2, Chapter 3/4, Level 7)
*** Provocator Archetype (Book 3, Chapter 3, Level 12)
* Locations and Geography
** Precipice Quarter
- Edgewatch
- Radiant Festival, main fairgrounds
- Book 1
*** Edgewatch Station / Headquarters

#+BEGIN_COMMENT
- "I always pictured the watch headquarters shoehorned into some existing, half repaired building.
  My imagining puts in the shell of what was once a grand hotel, now with half the rooms collapsed and just boarded off, and holding cells being old rooms"
- https://paizo.com/threads/rzs434ha?Community-Created-Content#3
#+END_COMMENT

** Foreign Quarter
- Sleepless Suns
- Book 2, Chapter 3
  - Copper Hand Hideout
- Book 3
  - Irorium / Blood City Games
** Ascendant Court
- Godless Graycloaks
- Book 2, Chapter 4
  - The Catacombs, Skinsaw Cultists, The Skinner
- Book 4
  - Temple to Norgorber, Noxious Retrort
** The Puddles
- The Muckruckers
- Book 2, Chapter 1
  - Smugglers
** The Docks
** The Coins
- Token Guard
- Book 2, Chapters 1-2
  - Bank leads, Bank Robbery
* Timeline
** Official
** Unofficial
* NPCS
** Primary / Major
*** Grospek Lavarsus
#+BEGIN_QUOTE
- Lavarsus ends up getting manipulated by the antagonists and arresting the
  wrong person. Play up Lavarsus as full of pride and incompetent
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
*** Hendrid Pratchett

#+BEGIN_QUOTE
I have to say, Hendrid Pratchett is one of the scariest and abhorrent monsters I've ever seen for Pathfinder. Facing this guy is worse than facing a Shoggoth, at least you expect the eldritch horror to come if facing one of them or know that they're around.

This guy is an act to follow for Chaotic Evil Villians, he's a charismatic manipulator to where he's easily so trustworthy to any person that would interact with him, yet so demented that the more you begin to peel away at his alibi and hotel, the darker tones start to kick in and break away at you mentally with each of his heinous crimes.

His form of revenge on getting hit with a mug is peeling away the skins of the four adventurers or mentally torturing two people to kill each other and make fake escape attempts that end up in vain, only for them to become scarred that they can't even trust the help that comes to save them. The fact that he keeps Ralso tied psychologically by having two dolls to act as her replacement sisters and his other demented works of art. And let's not forget the two ghosts he keeps as children to see him as a father figure.

James, congratulations. I am literally scared of this guy.

#+END_QUOTE

Volusto 	Aug 4, 2020, 12:33 am https://paizo.com/threads/rzs4349b?1-Devil-at-the-Dreaming-Palace#41
*** Radiant Festival
#+BEGIN_QUOTE
- The story of how the radiant festival started gets explored in book 6. I had
  a float featuring the half-angel in the parade
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
*** Festival Committee / Grand Council

#+BEGIN_QUOTE
- Some members of the festival committee and the grand council will end up
  playing major roles in the final books. So they should be introduced and
  interacted with early. I had my PCs give a brief 5 minute presentation in
  front of the radiant festival committee at the palace in Wise Quarter about
  their discovery of a potential bank heist plot.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
*** The Black Whale
#+BEGIN_QUOTE
- The Black Whale is a prison for important political prisoners that is
  visited in book 5. Give it a brief mention maybe at some point when
  appropriate.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
*** Jonas Flakfatter ("The Infector" / "Father Infector")
*** Starwatch, Starwatch Keep
#+BEGIN_QUOTE
- Starwatch will eventually (in book 3) adopt the PCs and Starwatch Keep is
  where they'll get some offices of their own. Have them visit it early on if
  they want or make sure they've heard it at least. Same goes for Fort
  Tempest, make sure they've heard it exists.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r

*** Olansa Terimor ("The Gray Queen") — L20 NE female human city planner, master thief
*** Reginald Vancaskerkin ("The Rumormonger")
#+BEGIN_QUOTE
- Vancaskerkin ends up being one of the main antagonists. Make Vancaskerkin
  prominent, especially through his tabloid Eyes on Absalom. Don't forget to
  tell the PCs about the frontpages of the paper (especially the ones that
  they are featured on), invite them for interviews, make them trust him as a
  partner they can go to ask for help. My players certainly have. For book 2
  Vancaskerkin will show up and warn the PCs about Pratchett trying to publish
  his memoirs from prison to create a favourable impression to the public
  before his upcoming trial.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
** Secondary / Minor
*** Captain Asilia of Gyr, Starwatch — N female human ranger 12

#+BEGIN_QUOTE
A stern-looking human woman with a shock of white hair and an impressive
tricorn sits behind a broad, imposing desk.  She stands and introduces herself
as Captain Asilia of Gyr (N female human ranger 12), leader of Starwatch and
commander of the warship Hurricane Wings, and gestures for the agents to sit
down, gesturing to the room’s comfortable chairs.
#+END_QUOTE
— cite:paizo-aoe-book3#page=6

#+BEGIN_COMMENT

- Captain of Starwatch
- Will be "commanding officer" in Book 3, 4?
  - Book 3 page 6: picture, narrative introduction
- Nautical dress

#+END_COMMENT
*** Blackfinger Blight

#+BEGIN_COMMENT
- Introduced in Book 1, Chapter 1
- Plays a key role in Book 3 Chapter 3
- Doesn't really show up between.

If your party has an Alchemist or Investigator, they might get curious to follow up on this clue…

- index
  - Book 1, pg 13:
    - "The zoo creatures themselves are acting unusually aggressive, with a
      starting attitude of hostile. This is the result of a rage-inducing
      serum called blackfinger blight. An agent of Jonis Flakfatter, one of
      the city’s high priests of Norgorber (and an important antagonist later
      in this campaign), tested his latest formulation by introducing the
      contagion into the animals’ water supply. An agent who succeeds at a DC
      15 Nature check realizes that this sudden hostility seems abnormal, as
      does the black froth around some of the creatures’ mouths, yet the
      Edgewatch agents aren’t intended to discover much about the contagion
      itself at this time. Rather, this is foreshadowing for the much larger
      role blackfinger blight will play later on in the Adventure Path, (see
      the campaign summary on page 76).

      The poison’s current formulation has a short half-life.  If knocked
      unconscious or restrained, creatures affected by the virus recover in a
      day or two.  None of the escaped creatures are currently capable of
      spreading the blight.

  - Book 3, pg 5: Heading, "The Blackfinger Blight Bomb"


#+END_COMMENT
*** Wrent Dicaspiron ("The Skinner")
*** Harlo Doleen

#+BEGIN_QUOTE
- Harlo Doleen ends up getting murdered which is a major plot point and
  twist. I made him be an acquaintance to one of the PCs. The PC used to be a
  slave and Harlo used to be his master. They have an awkward relationship now
  after not seeing each other for more than 3 years.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
*** Blood City Games / Irorium

#+BEGIN_QUOTE
- The Irorium will be the setting of a big part of book 3. Make sure to
  mention it a few times. I had Oggrum (one of the gladiators the PCs will
  have to fight eventually) get a float in the radiant parade advertising his
  exploits.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
*** Noxious Retort / Temple of Norgorber
#+BEGIN_QUOTE
- The Noxious Retort is an annual alchemical conference taking place at the
  Blackfingers temple. It will be showcased in book 4. Make sure your players
  learn about it beforehand if they are into alchemy or if they try to learn
  about Norgorber temples in the city.
#+END_QUOTE
—- cite:reddit-ocdrxm-h3uh21r
*** House of the Planes

#+BEGIN_QUOTE
- House of Planes will be revisited in one of the later books. So it should
  probably be mentioned a few times. In book 2 I had my PCs track down one of
  the smugglers there after a botched attempt to raid their base of
  operations.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
*** Lucky Nimbus Casino
#+BEGIN_QUOTE
- The Lucky Nimbus casino will play a role in book 3. Make sure to mention it
  exists. I had an elaborate float advertising it in the radiant parade.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
*** Godless Graycloaks

It's not quite stated strongly enough in the Player's Guide that the Godless Graycloaks are explicitly and strictly atheist.

*** (Godless Graycloak's) Captain Runewulf — N male human barbarian 13

#+BEGIN_QUOTE
"as he is more colloquially known, Runewulf the Unbeliever."
#+END_QUOTE
— cite:paizo-aoe-book2#page=28

*** Beldrin's Tower (Precipice Quarter)
#+BEGIN_QUOTE
- Beldrin's tower in Precipice Quarter ends up being the place of the final
  confrontation. It should at least be mentioned earlier, implant the idea of
  visiting it for a tour while the festival is going on.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
* Plot Notes
** Book 1: "The Devil in the Dreaming Palace"
*** Title … spoilers, Paizo!

Just the name of this book is a spoiler combined with the fact that the Party meets Pratchett, who identifies himself as the owner of The Dreaming Palace in literally the first encounter the PCs have in the game. :(  Even Players who are not /trying/ to spoil themselves might come across the book name on the internet, including AoN.

Since you can't change the book name, there are a couple of options:

1/ Rename the "Dreaming Palace" hotel. The name is not particularly important … feel free to change it.

2/ Skip the Pratchett+Ralso encounter in the Tipsy Tengu entirely (see [FIXME] link to below).

*** Book 1, Chapter 1: "The Mean Streets of Absalom"
**** Noise Complaint / Tipsy Tengu

As mentioned earlier, the title of the book matches the name of the hotel that the primary atagonist tells the party in their very first encounter.

It's a strange decision the AP authors made, here.

Changing the name of the "Dreaming Palace" will preserve the suspense throughout the book, and is recommended.

Also, just skip the encounter with Pratchett and Ralso in the Tipsy Tengu entirely.

The encounter serves two purposes:

- Foreshadow Pratchett. There is no particular need to do so, and this extremely brief encounter doesn't particular serve to do so well in any case.

  [[http:cite:reddit-n39df5][u/DragoldC42 concurs...]]
  #+BEGIN_QUOTE
  The chance encounter with the book villain in the very start is a bit too
  obviously foreshadowing- seeing the owner of the dreaming palace in an
  adventure named this way does not give much room to doubt. I found it not
  really disrupting, as the players could make some disconnect, but for another
  GM I would advise to just change the name of Pratchett's hotel.
  #+END_QUOTE
  --- cite:reddit-n39df5

- Provide a reason why the skins of the drunk adventurers are flayed and hanging in Pratchett's trophy room (they broke his nose). Pratchett has plenty of motivation to kill anyone he wants (he's a sadistic serial-killer dick-hole), so there's no need to /motivate/ this.

**** "Guards! Guards!"
**** "Panic at the Zoo" / Knight's Marvelous Menagerie

The Menagerie encounter has a bit of a reputation for being rough.

You have some options.

#+BEGIN_QUOTE
- the deadly zoo encounter- which includes two different monsters with the ability to petrify the party as well as a buffed rust monster, against which the party has to pace without a real chance to take 10 minutes of rest- is too much for most level 1 parties, including mine.

I gave my players the option to just tie up the monsters with rope after a successful grapple check, and this gave a much easier win condition to the combats while still being hard enough considering they had to go all over the zoo with no rests.
#+END_QUOTE
— cite:reddit-n39df5

**** The Graveraker goes missing

The AP makes a point of the Graveraker going missing at this point.

It is extremely easy for a/ you to miss this point here in the text and b/ for it to be lost on the Party. It's another piece of foreshadowing that can get a bit lost.

The Graveraker does not come up again until Book 4, but is an important plot point much later in the AP; the party will have a critical encounter within its strange extra-dimensional interior!

Many folks recommend making more of a point of it.

#+BEGIN_QUOTE
- The Graveraker becomes an important plot point in the 4th and 6th books, Yet after it disappears somewhere in the start of this book, no mention of it exists in the AP for three whole books- at least not in a way major enough to remind the players it exists. My group totally forgot about it by the point the twists happened. I would advice all GMs running the AP to find ways to bring the Graveraker up a few times. Also, no art of the Graveraker exists in the AP at all. I would have really liked to see what it is like!
#+END_QUOTE
— cite:reddit-n39df5

[[https://paizo.com/threads/rzs4349b&page=9?1-Devil-at-the-Dreaming-Palace#447][GreatGraySkwid has some good perspective about the Gravewalker going missing, here…]]
#+BEGIN_QUOTE
The whole point of Graveraker's disappearance happening off camera is so
that the actually qualified Agents of Edgewatch (i.e., not "our" party) can
be dedicated to tracking down an established and well-known exhibit of the
Festival, leaving our teams of rookie misfits to investigate a batch of
people who may or may not actually be missing.
#+END_QUOTE
— cite:paizo-rzs4349b--447

#+BEGIN_QUOTE
- The Graveraker will show up again in book 4. Show Bolera working on the
  Graveraker case. In my game, she's slowly uncovering some clues like
  mentioning that she thinks it was no coincidence that the zoo attack and the
  Graveraker theft happened at the same time, interviewing the inventor and
  making some vague references about a missing power source and the
  involvement of the radiant festival committee
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r

*** Book 1, Chapter 2: "Missing Persons" / The Dragonfly Pagoda
*** Book 1, Chapter 3: "Into the Undercity" / House of the Planes
**** The Back Door

- [FIXME] Grolna relevance?
- Treasure
  - +1 rune

**** The House of the Planes

This section is intended to provide leads to Ralso and Pratchett, and to tie the missing stone masons to Ralso.

As written, it is extremely heavy-handed. Literally every NPC knows something absurdly relevant about Pratchett or Ralso.

In terms of priority, the following things "must" happen here:

- The party should meet Reginald Vancaskerkin, and ideally they should /like/ him.

  #+BEGIN_QUOTE
  -Reginald Vancaskerkin is described in the book as someone who is "oily, nosy, and of questionable moral fiber", while the later books seem to think he has become a fan and friend of the party, at least until he backstabs them. I would advice playing him as someone who your players would like, and not a walking red flag as my reading of the first book alone implied to me.
  #+END_QUOTE
  --- cite:reddit-n39df5

- The party should find out that Ralso fenced some Minkainan stone mason tools, and she works at the Dreaming Palace.

- [Read The Alexandrian and invent two more clues, in case they don't find that one.]

Everything else is gravy.

- While Hoff will come back up later in the AP (Book 4), Hoff is not a plot-critical character.

- Book 4 does have a map of the House of the Planes, and I'll recommend using it. The location is interesting, even if this is just a social encounter.

*** Book 1, Chapter 4: "The Murder Hotel" / The Dreaming Palace
**** Content Warning

This dungeon is no joke, either difficulty-wise or especially thematically.

You should make sure your Players are comfortable with the content here. *It's more important to make sure of that than to prevent spoiling things.*

Some people are going to have serious problems with – for example – mutated, deformed fetuses kept alive in jars! Some people might have real-life bad experiences with voyeurism or being spied on!

It is of course okay if they do, and it's your job to only challenge them as much as they are comfortable being challenged.

Be kind.

**** The Dreaming Palace

- [[https://www.reddit.com/r/Pathfinder2e/comments/ojp6to/agents_of_edgewatch_book_1_finale_im_in_doubt/][There are some concerns with the pacing/leveling in the Dreaming Palace]], and [[https://www.reddit.com/r/Pathfinder2e/comments/ojp6to/agents_of_edgewatch_book_1_finale_im_in_doubt/h5354t4/?utm_source=reddit&utm_medium=web2x&context=3][u/Naurgul has some good advice on particular aspects of that]].

- (FIXME) You should have plans for what you will do if the party is split because 1 or 2 of them fall through one of the traps into the basement.

- [[https://www.reddit.com/r/Pathfinder2e/comments/p887ao/agents_of_edgewatch_spoilers_sidequest_ideas_for/][At least two groups have independently tamed the mimic into becoming a party "pet" or acquaintance. :)]]

**** Hendrid Pratchett encounter

Experiences with this encounter vary, but it is a Severe 4 encounter, and based on the time and physical constraints of this dungeon crawl, the party will likely be encountering Pratchett with below-full health and limited resources (consumables, spells) remaining.

On reddit, [[https://www.reddit.com/r/Pathfinder2e/comments/otxspj/final_fight_of_the_first_book_of_agents_of/h70146j/?utm_source=reddit&utm_medium=web2x&context=3][u/SanityIsOptional suggests a varied action spend from Pratchett to help smooth the encounter for the PCs]]:
#+BEGIN_QUOTE
From my experience running him: Make sure he's spending actions to move
around and using intimidate on the players. Essentially eat up his actions
on thematic and interesting things that aren't attacks. Especially if they
end up harassing the players or making the characters angry at him. He
shouldn't be taking the party seriously, and should be trying to taunt them
at least in the start of the fight.
#+END_QUOTE
— cite:reddit-otxspj-h70146j

This goes both ways, too. As in PF2 generally: the party using actions to force /enemies/ to spend actions is of good utility.

[[http:cite:reddit-otxspj-h71hhre][u/mads838 agrees]]:
#+BEGIN_QUOTE
The group i played in managed it. But it was tough as All hell. Try to convince you players to start using stuff like grapple, trip or disarm. Actions wasted because of those are actions he isnt using to kill the players.
#+END_QUOTE
— cite:reddit-otxspj-h71hhre

--------------------------------------------------

The Binumir are also a challenge.
[[http:cite:reddit-otxspj-h7jg3rc][As u/narchy notes]]:
#+BEGIN_QUOTE
The ghost twins scream is a REALLY nasty one. The fighter and champion in our group failed the save, which means no AoO or Retributive Strike.
#+END_QUOTE
— cite:reddit-otxspj-h7jg3rc

[[http:cite:reddit-otxspj-h6yiyr8][u/Naurgul has some advice]]:
#+BEGIN_QUOTE
The fight gets much easier if the PCs take out the children twin ghosts he has with him with RP instead of fighting. If they are reminded of their former lives they don't attack. So maybe give them a few extra hints about that. For example if they try to recall knowledge on them ask if they use society or religion; a successful society check should be enough to remind them of the twins they read about in their missing persons reports.
#+END_QUOTE
— cite:reddit-otxspj-h6yiyr8

And [[http:cite:reddit-larstr0n-otxspj-h6ygq77][u/larstr0n (GM, Tabletop Gold podcast) recommends using the Binumir the scale the combat on the fly]]:
#+BEGIN_QUOTE
If you're concerned about Pratchett, there’s a lot of room to run his ghost twins suboptimally and use them to ratchet the tension up and down depending on what level of peril you’re looking for.
#+END_QUOTE
— cite:reddit-larstr0n-otxspj-h6ygq77

Stepping back a bit, [[https://www.reddit.com/r/Pathfinder2e/comments/otxspj/final_fight_of_the_first_book_of_agents_of/h6zoyve/?utm_source=reddit&utm_medium=web2x&context=3][u/Unconfidence finds this encounter "exemplary of the stuff I don't like about Paizo's APs."]]:
#+BEGIN_QUOTE
This combat made me think that either the people who made this system really
didn't understand the way poison interacts with death & dying, or that I am
missing something about it. Because like, going to the ground with
persistent damage, that's death. And we certainly had three of our six party
members at high levels of Wounded.

It's extremely dicey and pretty exemplary of the stuff I don't like about
Paizo's APs. The entire "difficulty" seems to be in high numbers and a
serious risk of a few bad rolls dooming a character or a party, despite any
of their best choices. I would seriously suggest any DM running this
consider putting Alchemical Antidotes or something of the sort somewhere in
the Inn, or I dunno, something.
#+END_QUOTE
— cite:reddit-otxspj-h6zoyve

[On Rebalancing]


[[http:cite:reddit-otxspj-h6z514n][u/SighJayAtWork describes]]:
#+BEGIN_QUOTE
I had six PCs so I added an extra "body" to the Binumir (like an eatin, I gave them both two actions) and a few Zrukbats to the encounter, just to give them some more bodies to deal with
#+END_QUOTE
— cite:reddit-otxspj-h6z514n

**** Pratchett Chase

[[http:cite:paizo-rzs4349b--441][Naurgul has some guidance on how to handle Pratchett's attempted escape using the GMG's Chase Subsystem…]]
#+BEGIN_QUOTE
Here's some potential obstacles for this chase scene along with some example checks that the characters could use to bypass them:

- secret door closes behind him (acrobatics to jump in before it closes, athletics to hold it open, thievery to re-open)
- flaming mass (acrobatics to jump through, athletics make a path, or they can just walk through it and take some damage)
- Pratchett throws down the shelves with the jars in E31 (Athletics to throw them out of the way, Acrobatics to squeeze through the gaps, maybe some spell)
- leftover monsters attack (acrobatics to tumble through, Athletics to shove away, recall knowledge or deception to distract them)
#+END_QUOTE
— cite:paizo-rzs4349b_441

** Book 2: "Sixty Feet Under"
*** Book 2, Chapter 1: "The Unusual Suspects"

While ultimately pretty linear, this chapter has a bit of an open-world / sandbox feel, putting choice into the party's hands.

#+BEGIN_QUOTE
is a very strong point in this book- a less structured investigation sequence gave an almost "open world" feeling while playing, with the party able to choose the pace and theorize on where the robbery will take place. Running this section was a lot of fun for me!
#+END_QUOTE
— cite:reddit-n39df5

**** FIXME

- https://paizo.com/threads/rzs4349c?2-Sixty-Feet-Under#41
  - > Is it explained why Chadraxa made a complaint against Orvington Moneychangers?
  - [next post]
    - > I assume that's related to the debt Orvington's son owes Chadraxa, which he has failed to pay.
    - > Same reason she had people graffiti his bank, and throw a wasp nest on the roof.
*** Book 2, Chapter 2: "A Penny Saved"

#+BEGIN_QUOTE
The robbery itself is okey - The robber's plan is kinda silly and they are bound to fail, but it felt good having the party stop them and save the day anyway. I feel that a GM taking the time to improve this scene could make it into a much better moment than I had.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 2, Chapter 3: "Caught Copper-Handed"

#+BEGIN_QUOTE
felt a bit disappointing in my group, because there was an expectation that another investigative part would follow the format of chapter 1. But the infiltration into the copper hands hideout was still an enjoyable dungeon. Our unlucky elf rouge got a minor case of lycanthropy from this part though- nothing a visit to a temple could not fix, but this could have messed with some plans.
#+END_QUOTE
— cite:reddit-n39df5

It's here at the very end of Book 2, Chapter 3 that we learn some pertinent backstory…

#+BEGIN_QUOTE
For the past few months, she explains, the Copper Hand has worked with a murderer named the Skinner and her cultists under threat of violence.
#+END_QUOTE
— cite:paizo-aoe-book2#page=27

*** Book 2, Chapter 4: "Descent into Death"
**** The Catacombs

You'll probably definitely want to get a read on your group's (dis)like of dungeon crawls for this one. The dungeon itself is large, and there are random-encounter tables. To give you a sense…

#+BEGIN_QUOTE
As the agents explore the Catacombs, keep track of how long the party is
spending in the dungeon.  For every 8 hours that passes in the game world,
there is an 80% chance the agents run into a random encounter.
#+END_QUOTE
— cite:paizo-aoe-book2#page=31


At the same time, in the AP's narrative, the missing Graycloaks contingent has been down here since "less than a week ago" [cite:paizo-aoe-book2#p28]…

#+BEGIN_QUOTE
"It’s been several days since my team of Graycloaks descended into the Catacombs […]"
#+END_QUOTE
— cite:paizo-aoe-book2#page=29

…so being down at least a 1-3 days would not be unreasonable.

#+BEGIN_QUOTE
as a dungeon crawl was too long for our taste. It took us 3 whole 4 hour sessions to get through it. And even with plenty of side quests happening in there it was still a too long section of mostly combat in an otherwise more RP balanced adventure. I would advise any GM's who feel the combat becomes repetitive in their groups to shorten this part- there are enough simple encounters to cut out of it without losing anything important
#+END_QUOTE
— cite:reddit-n39df5


----------

Tyrrociese is a particular problem.

[[http:cite:reddit-oknoo0-h59zt3p][u/larstr0n (GM, Tabletop Gold podcast)]] strongly advises…
#+BEGIN_QUOTE
I strongly advise, for that monster, taking the book’s advice and having them engage the ofalth in the next room in battle. In my game,I kept the ooze focused on the party enough to freak them out, and then strung out a kong vs Godzilla fight between the two big bads. This approach kept my party challenges and made for a memorable, cinematic encounter.
#+END_QUOTE
— cite:reddit-oknoo0-h59zt3p

#+BEGIN_COMMENT

OTOH…

@author{paizo-Deriven_Firelion}
@misc{
  FIXME
  cleared = "false"
}
[[https://paizo.com/threads/rzs4349c&page=2?2-Sixty-Feet-Under#91][Deriven Firelion says]]:
#+BEGIN_QUOTE
#+END_QUOTE
That elite ofalth was brutal. My players ran into it at lvl 7. I decided to reduce it to a regular Ofalth. It was still brutal.
#+END_COMMENT

[[http:cite:reddit-oknoo0-h5aswqa][u/valahan23 has a number of recommendations…]]
#+BEGIN_QUOTE
I'm currently running AoE and we finished up the catacombs about a month ago. Overall, I'm not a fan of Book 2. I Think the author is the type who loves theory crafting monsters without really thinking about balance. I first noticed this with the copper hand illusionists in chapter 3 that are supposedly level 5, but are a full wizard/rogue. Their spell DC was higher than the party's optimized level 6 wizard. I'd be fine with that if they weren't also a full blown rogue.

I ended up making some changes to to the eldritch ooze TYRROICESE cause I personally think that monster was just poorly designed. This is pretty much entirely was because the ooze template was used without really looking at how oozes work.

- Not all oozes are immune to slashing/piercing (gelatinous cube), but those that are also have the split trait, basically cutting them in half with the HP split between the two. The benefit to splitting them is that you can then have your caster nuke them with AoE. The eldritch ooze got the benefit of immunities without being able to be split. (So I got rid of these immunities on the eldritch ooze)

- Oozes are usually immune to critical hits/precision damage because they are just a blob of ooze so they don't have specific spots to hit for more damage. The eldritch ooze is a large suit of armor basically being piloted by an ooze. (I removed it's immunity to precision damage with the reasoning that the rogue and investigator would be able to find weak points in the armor to attack)

- Lastly I made his pseudopod burst follow the standard MAP rule. As letting a solo encounter have 3 attacks at +23 when the party's AC is in the high 20s was just insane to me. His chance to crit was way above 50% with an average crit doing around 46 damage.

Even with these adjustments it was a super close fight with most of the party unconscious and the remaining members sitting around 10-20 HP when they defeated it.
#+END_QUOTE
— cite:reddit-oknoo0-h5aswqa

[[http:cite:reddit-oknoo0-h59vm90][u/DocTam suggests pushing holy water to help with the crawl]]:
#+BEGIN_QUOTE
I think providing/encouraging the party to get Holy Water is the best way to make the dungeon manageable; since it makes the hardest fights much easier. Books 3 and 4 have been much more manegable difficulty wise; so don't despair too much.
#+END_QUOTE
— cite:reddit-oknoo0-h59vm90

** Book 3: "All or Nothing"

#+BEGIN_QUOTE
This is probably my favorite book in the AP! It was the best at not only giving varied scenarios to play in, but also providing GM tools to expand and enhance those parts to their liking.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 3, Chapter 1: "Street Justice"

#+BEGIN_QUOTE
which involves resolving a gang war in the docks has some very flavorful NPCs with interesting personalities, one of which (Maurrisa) Became a recurring NPC in my game. This part is also relatively free in its structure and contains some moral choices to make.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 3, Chapter 2: "The House Always Wins"

#+BEGIN_QUOTE
The casino heist is a very interesting chapter as well. Somehow the casino games given did not translate well into our VTT experience, But the inclusion of so many mechanics and tools to make the heist interesting is just great! I am sure many GM's can make good use of this part- even as inspiration for home games.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 3, Chapter 3: "Deadly Games"

#+BEGIN_QUOTE
Gives the characters the task of dealing with a bomb threat in the middle of a gladiator tournament. The scenarios given in the AP itself are quite basic. But the tools provided, the various arena game mechanics and the flavor text-gave me plenty of inspiration to expand this part into a mini tournament arc- which was probably the highlight of the campaign! I highly recommend customizing this part to your group's liking.

I have made another post in the past about a stat problem with the final boss of this chapter- it has a mistake with its AC that makes fighting him a breeze, so you might want to check it out before you run it.
#+END_QUOTE
— cite:reddit-n39df5

** Book 4: "Assault on Hunting Lodge Seven"
*** Book 4, Chapter 1: "The Noxious Retort"

#+BEGIN_QUOTE
After a quick starting dungeon, this chapter including my favorite dungeon experience of the AP. The blackfinger temple- with the convention in it's upper floor, the puzzles, the interesting monsters, and the reasonable length of it- was a very fun dungeon crawl!
#+END_QUOTE
-- cite:reddit-n39df5

*** Book 4, Chapter 2: "The Gervin Legacy"

#+BEGIN_QUOTE
In which the agents hole up in a haunted safe house to keep a watch over their prisoner, is another interesting chapter. It is divided into parts which feel tower-defense-like (protecting the house from assassins) and a small dungeon crawl in the basement. After cleansing the haunted house and defending it for so long, my players grew attached to the hunting lodge, so I gave them the deed to the house as a gift from the city as thanks for their service. The fact that the hunting lodge does not cointain any toilet in it became somewhat of a joke in our group, and the players announced they are building one in the house after they acquired it.

Small note about the final boss of this chapter- The lesser death is a tough monster- with its disadvantage aura and high attacks, definitely has a potential to kill a PC. My players have managed to exploit its teleporting reaction to trap it inside the house vault (which I stated to be teleport proof). That was a very proud GM moment for me, and I rewarded their creative thinking with a homebrew item that the lesser death bargained for its freedom.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 4, Chapter 3: "A Wonderful Time in Harrowland"

#+BEGIN_QUOTE
the investigation of harrowland was not interesting for my group. I think that we are all missing the excitement about all the harrow lore in there- so it felt like we were missing half the fun in there. Still, I imagine that for a group with more golarion lore background this could be a nice theme dungeon.

The end of the book features the twist of Reginald framing the party. This did not land that well in my group for a couple of reasons:- The framing plot depends heavily on the Graveraker. About which most of my party forgot by the time they got to this point. Foreshadow it more!- Reginald was obviously evil from the first time they met him. So the reaction was more of "Oh finally he shows he is evil and we an go kick his ass" and not the seemingly intended shock.
#+END_QUOTE
— cite:reddit-n39df5

** Book 5: "Belly of the Black Whale"

#+BEGIN_QUOTE

This book has a nice change of pace from the previous ones- The agents have to work now outside the law, as their badges have been taken from them after they were framed. This gave the players many opportunities to test the moral compass of the characters, and how much are they willing to do outside the law to get their goals. Good RP stuff!
#+END_QUOTE
— cite:reddit-n39df5
*** Book 5, Chapter 1: "Dishonorably Discharged"

#+BEGIN_QUOTE
deals with gaining enough favor with a crime lord to get the secrets on how to break out the Starborn from the Black Whale prison. Miogimo the crime lord is a good [foil] to the agents, showing how taking justice into their own hands can make them end up. Overall, the chapter gives plenty of roleplay moments to shine.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 5, Chapter 2: "Belly of the Black Whale"

#+BEGIN_QUOTE
is about the jailbreak from the black whale prison. The dungeon itself in there is decent, but I needed to put extra work in to make it feel more like a prison. Things like patrol routes, and more details about the day to day management of the prison are lacking the way they are presented in the adventure, I think this section could benefit from some clearer details.

After the prison break, the chapter goes again into a bit of an investigation- where the agents need to find the evidence to clear their names and catch Vancaskerkin, in my group at least we mostly glossed through this part, because some details and npc's presented in the chapter were not working well with the way things occurred in my game. This still seems like a nice scenario.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 5, Chapter 3: "The Rumormonger’s Stronghold"

#+BEGIN_QUOTE
is the clockwork dungeon of Vancaskerkin. The dungeon itself is quite cool to run. There are different difficulty levels for many encounters, some cool monsters and a few secrets to discover. Reginald himself was a bit underwhelming (At least to the power level of my party), My solution was giving him 2 clockwork abilities at once, instead of just one, to up the danger- worked quite well for me!

Another great thing about the showdown with Vancaskerkin is the alternative win condition against him- instead of killing the villain, the players have an option of resolving the conflict by exchanging his mind using a machine he has build. My party went for this option, and Regi-mouse became a cannon part of our Golarion.

In my opinion, the fight against Reginald felt like it should have been the final one of the AP. He was behind all the troubles the agents faced so far, and by defeating him, clearing their names and redeeming Starborn in the eyes of the public, the agents can feel satisfied with their victory. I'll explain my reasons for this below- but to keep a strong thematic sense, I would advise to finish the campaign here- and avoid part 6. It is a perfectly self-contained ending by this point.
#+END_QUOTE
— cite:reddit-n39df5

** Book 6: "Ruins of the Radiant Siege"

#+BEGIN_QUOTE
Sadly, this last part of the AP is also the weakest in it. It has many interesting ideas, but I'm afraid that as written, it feels off from the rest of the AP, and does not contribute much to the story other than continuing it to level 20.

Firstly, the big villain is someone who was basically invisible to the players! Olansa shows up one time before this book, and this is just to shake the characters hands and go away. At least the AP makes her presence clear enough to the GM before this point, so some foreshadowing can be added- but this is work the GM cannot be aware of unless they kept reading ahead, in detail, and realize Olansa is not properly foreshadowed anywhere. It feels especially hollow facing Olansa after defeating Reginald- who was there plotting since the start of the game, and the characters have a really good reason to hate.

This could be a minor thing should Olansa have been an interesting villain, but as she stands in the book, she has no motivations. Her backstory seemed shallow, it is unclear what, if anything, she would do should the characters fail to dethrone her- the book gives no clue for us. It is unclear what her motivation to take the throne is other than to get more power. This came off to me very one dimensional and boring.

Thanks to a suggestion I saw in the Paizo forums, I altered her in my home game to have the plan to steal the whole city of Absalom into a demiplane, where she can rule it with an iron fist forever. But if you run it as is from the book, she is stated to do next to nothing but sit in her tower and wait to be defeated, other than maybe messing up some beurocracy in the city.

Secondly- This part of the adventure is a major change in tone from the rest of the AP.This is even said on page 3 of the book, where the writer explains the agents are now too strong for criminals to be a problem for them. So they should retrain their social skills and get ready for some extraplanar monsters popping in their way. I feel it's a bad note to finish a campaign focused on using diplomacy to solve problems by throwing hordes of daemons and crazed proteans at the party, and would have much preferred the adventure to stick to the spirit of the previous books.

The chapters themselves are basically 3 big dungeon crawls, with no goals other than to clear them out and get the relevant plot cupon. To the adventure's credit, the design of the dungeons is interesting, but as someone who likes shorter- more concise dungeons, They felt like they are dragging on too much, with plenty of filler fights and encounters over the xp budget. Filler fights are a common thing in any AP, but a book comprised of mostely filler fights is dull to run in my opinion.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 6, Chapter 1: "Runaway Excavator"

#+BEGIN_QUOTE
has a dungeon happening inside a giant mech. This is a very cool idea, and one that was foreshadowed before with the Graveraker (Though, not too well). The most disappointing thing to me about this part, is that we never got any detail's on how the Graveraker even looks, not to speak about any illustration. Without those, it was hard to make sense of the situation, it felt undefined in a disappointing way.

This dungeon also features the crazed proteans- who are stated to attack the characters on sight, and no alternative means of defusing the situation are given to the players, not even some reasonable solution like promising to free them. I chose to allow such a solution to my players. But without it there was next to no content in this dungeon as most of the rooms are fights with said proteans.

Another thing happening in this chapter is the introduction of Il’setsya Wyrmtouched, who appears out of nowhere to give the party their next quest location, and escorts the party as a GMPC from then on. I chose to leave her out of my game, and tie the plot advancement to other things .GMPC is an idea I dislike, and it felt cheap to me to make the plot development of a story nearing its end happen by a random character appearing out of thin air.

I also think that actually using her as written- where she has some "triggers" later on In the book which cause her to act in a rash way and probably against the interest of the party, and also possibly steal the show in the final bossfight weather the party took her in or not- would be frustrating to deal with as a player. I'm sure some GMs can pull this off well, but I am not one of them.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 6, Chapter 2: "The Radiant Spark"

#+BEGIN_QUOTE
In this chapter, the party needs to delve into another dungeon- the ruins of an ancient fort constructed by an evil archmage bent on conquering Absalom with an army of mind controlled angels- in order to find the item that will allow them to face the final boss.

Before entering the dungeon, there is a section involving the use of the research mechanics. Where the party needs to balance spending more days getting prepared to the dungeon and gaining advantages in it with the risk of getting caught by the deamonic agents of Olansa.The way my game played out; the agents had too much stress on them to be able to research calmly for days as the adventure assumes- so we largely ignored this mechanic. But this is a cool concept.

The dungeon itself is nice. Though for some weird reason, the majority of creatures and hazards in it have access to some variation of the prismatic spray spell. So the dark tone of the location, at least in my group, was hurt a bit by having rainbows assault the characters every fight.Also, there seems to be an issue with the room size in the map- for example a room meant to house 3 gargantuan creatures is physically too small to contain them.

The boss of this chapter- a fallen planetar- has a problem in his stats. He possesses regeneration that can only be deactivated by evil damage, something which the lawful good party, Which the players guide instructs to make, will have no access to, meaning the PCs are unable to kill him in most conceivable groups. I decided to ignore this fact and just treat it as fast healing, not sure if there was a good reason to have it there in the first place.
#+END_QUOTE
— cite:reddit-n39df5

*** Book 6, Chapter 3: "The Gray Queen's Tower"

#+BEGIN_QUOTE
Dungeon number 3 in this book is an assault on the tower where the main villain is sitting and… going slowly insane, waiting to be killed. Really this calls for a change from the GM.For me, I upped the stakes by having Olansa launch a daemon attack on the citizens of the city- and the players have to stop her before she kills everyone.

The cool part about this dungeon, is the boss rush nature of it. To get to the final boss, the agents combat against the reincarnations of the 3 bosses from earlier in the campaign. (There are also many filler fights in this chapter, which serve no purpose in my opinion- the players are level 20, they don’t need to grind anymore.)

As written the boss rushs are cool fights, with enough to challenge the 20th level characters, the only thing I would change in there is to enlarge a bit the rooms they are found in, because they are too small for a dynamic fight to take place in them.

The problem is, these fights are not going to run as written, unless your players specifically avoid it there is an easy way to steamroll this entire dungeon-The artifact the players gained in the end of chapter 2 allows them to indefinitely mind control all the daemons present in there. I let my players have some fun with the pokemon-esqe gameplay of capturing all the demons (actually demon capturing sounds more like SMT but I digress) , until I had to ask them by the end to not use the artifact they were given- or the game would not be fun.

Olansa as a final boss is also quite unimpressive. Her ability to turn invisible even to see invisibility feels cheap, and the poison on her weapon- Teats of death- Is irrelevant to the combat because of its 1-minute onset time. Even with her artifact equipped she is just not a very interesting or challenging opponent as written. I heavily altered it for my session and would advise doing the same to any other GM to make sure the ending of the campaign is properly epic.
#+END_QUOTE
— cite:reddit-n39df5

* Resources
** Missing Persons Casefiles
*** "[[https://paizo.com/community/blog/v5748dyo6shbn?Edgewatch-Cold-Case-15561-Evidence-A][Edgewatch Cold Case #1556.1, Evidence A]]"

On their blog, Paizo published "[[https://paizo.com/community/blog/v5748dyo6shbn?Edgewatch-Cold-Case-15561-Evidence-A][Edgewatch Cold Case #1556.1, Evidence A]]" in July 2020, a letter discovered under a table in the Tipsy Tengu, a piece of evidence regarding one of the missing persons that form the basis of the mystery in Book 1.


#+BEGIN_COMMENT
-Naurgul's Casefiles
 - https://paizo.com/threads/rzs4349b&page=8?1-Devil-at-the-Dreaming-Palace#389
- jsled's casefiles
 - https://paizo.com/threads/rzs4349b&page=10?1-Devil-at-the-Dreaming-Palace#482
#+END_COMMENT

** Journal Entries / Notes / Handouts
*** Book 1 Chapter 4: Pratchett's Journal

[[https://www.reddit.com/r/Pathfinder2e/comments/p1479k/agents_of_edgewatch_spoiler_handout_for_book_1/][u/corpboy has shared a 16-page original creation that is Pratchett's journal]],
encountered next to his dungeon in the basement of the Dreaming Palace. It
includes references into some other world lore, as described in the reddit
thread.

*** Book 2 Chapter 1: Investigation Leads

[[https://www.reddit.com/r/Pathfinder2e/comments/qynogu/spoilers_aoe_investigation_leads/][u/perryhopeless shared some OC art for the investigation leads from Book 2 Chapter 1.]]

** Maps
*** u/narchy's maps

User narchy has provided a [[https://drive.google.com/drive/folders/1LZdj40ot34lfxoGbzu5aTgnAKQ1M8_eY?usp=sharing][full collection of all the maps, "remastered"]]. They're quite nice.

#+BEGIN_QUOTE
I have finished the final book of the awesome Agents of Edgewatch AP, which brings to an end 7 months of working on these maps! I may go back and tweak a few of the earlier ones, but uiltimately I am really happy with how these turned out.

You can download them (books 1-6) from [[https://drive.google.com/drive/folders/1LZdj40ot34lfxoGbzu5aTgnAKQ1M8_eY?usp=sharing][Google Drive]] for you to use as you wish.

The maps for all books are also available as [[https://foundryvtt.com/packages/aoe-maps-remake-by-narchy][Foundry VTT module]], containing all the scenes with walls/doors/windows etc.

As always, feedback welcome! If you want to contribute to my Pathfinder book buying addiction, a coffee is always appreciated - [[https://www.ko-fi.com/narchymaps][www.ko-fi.com/narchymaps]] :)

Assets are from [[http://www.forgotten-adventures.net/][www.forgotten-adventures.net]]
#+END_QUOTE
— cite:reddit-on03uu-h5oij50

As well, [[http:cite:reddit-ph7txq-hbgkw36][they've provided a version of the festival grounds map…]]

#+BEGIN_QUOTE
I made a larger version of the festival grounds map a while ago, and I've finally gone back and finished it.

I have tried to recreate the various attractions as they are described in the books, and also included some areas with regular city buildings as they are needed for various encounters. Also, the festival grounds don't occupy the entire quarter - at least that's my interpretation!
#+END_QUOTE
— cite:reddit-ph7txq-hbgkw36

** Landing Pages

- [[https://www.reddit.com/r/Pathfinder2e/comments/pa523d/landing_page_for_my_agent_of_edgewatch_campaign/][u/faultypanda has a nice landing page, which garnered praise from Erik Mona in the comments]]
** Art, Fiction and Original Content
#+BEGIN_COMMENT
AoE Renders…
#+END_COMMENT
*** "Wrent's Confession", Book 2/3 Transition by KM Kovalcik (u/zombkat)

On reddit, [[http:cite:reddit-pq90e5][KM Kovalcik (u/zombkat) posted a bit of fiction detailing the crimes of Wrent Dicaspiron]], set in the interstitial between Books 2 and 3.

#+BEGIN_QUOTE
My players are about to move onto book 3, and I was unhappy with Wrent confessing a whole bunch of story stuff off-screen. My players did not interrogate her themselves, and I wanted some time to do some fiction writing. I wrote out her confession as if being interviewed by a priest of Sarenrae who wanted to see if it was possible to redeem her, or at the very least determine if her ramblings were truthful.
#+END_QUOTE
— cite:reddit-pq90e5
*** "Agents of Edgewatch as a 90s TV show", from u/narchy

[[https://www.reddit.com/r/Pathfinder2e/comments/qye7ly/agents_of_edgewatch_as_a_90s_tv_show_made_to/][u/narchy created and shared a wonderful video of their party's Agents, in celebration of getting to book 3: "Edgewatch Nights".]]

* Unofficial Errata
** Book 1
*** Book 1, Chapter 1

- The name of the pub in the first encounter is [[http:cite:paizo-aoe-book1#page=89][referred to as "the Arcadian" in the description of Pratchett on page 89 of Book 1]], but it is the "Tipsy Tengu" everywhere else, of course.

*** Book 1, Chapter 2

- The encounters in Chapter 2 are spec'ed for a level 2 party, so level the party to level 2, no matter what the guide at the front of the book says.

** Book 2
*** Book 2, Chapter 4

- In D15 (Sanctuary), one of the cadets is listed as "Kirsta Malopedes" but referred to later in the text as "Cadet Pennington".
  — cite:paizo-aoe-book2#page=41

- War Razors are listed in stat blocks as doing "piercing" damage; it should be "slashing".
  #+BEGIN_QUOTE
  OK, I thought I was losing my mind reading through the Sanctum, last night, but War Razors are typoed consistently in this book as being Piercing weapons. AoN has them as Slashing, as is, of course, the only reasonable option.
  #+END_QUOTE
  — cite:paizo-forums-rzs4349c-59

* Colophon
** Licensing

This work is generally licensed as [[https://creativecommons.org/licenses/by-nc-sa/4.0/][Creative Commons By-Attribution Non-Commercial Share-Alike, International, Version 4.0]].

This work is a collection of quotes, links and original content regarding running the Paizo Adventure Path /Agents of Edgewatch/.

Copyright of the quoted forum posts and comments is held by the respective original authors.

Block quotes appearing herein have been licensed by the authors, generally in terms "compatible with Creative Commons By-Attribution, Share-Alike, Non-Commerical, version 4.0". See "meta" for more details.

#+BEGIN_COMMENT
FIXME: link to meta, license attestations
- link directly to github
#+END_COMMENT

This work – "The GM's Guide to /Agents of Edgewatch/" – uses trademarks and/or copyrights owned by Paizo Inc., used under [[https://paizo.com/community/communityuse][Paizo's Community Use Policy (paizo.com/communityuse)]]. We are expressly prohibited from charging you to use
or access this content. "The GM's Guide to /Agents of Edgewatch/" is not published, endorsed, or specifically approved by Paizo. For more information about Paizo Inc. and Paizo products, visit [[https://paizo.com/][paizo.com]].

#+BEGIN_COMMENT
FIXME:
> You agree to create an account on paizo.com and add an entry describing your material on our Community Use Registry at paizo.com/community/communityuse/registry, with links where appropriate.
#+END_COMMENT
** Sources and Contributing

The source repository of this Guide is https://github.com/jsled/gms-guide-to-agents-of-edgewatch.
Contributions as pull requests are welcome. Contributions in other forms will be considered.

The primary hosting of this Guide is https://asynchronous.org/gms-guide-to-agents-of-edgewatch.

** Editor

The editor of this Guide is [[http://asynchronous.org/jsled][jsled]].
