#+OPTIONS: ^:{} ^:nil _:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
#+HTML_HEAD: <link rel="stylesheet" href="guide.css"></link>
#+HTML:<script src="guide.js"></script>
#+TITLE: The GM's Guide to "Agents of Edgewatch"
* Introduction
** Mission Statement
   :PROPERTIES:
   :CUSTOM_ID: mission_statement
   :END:

This guide is for those who are running the Paizo Adventure Path /Agents of Edgewatch/.

It is a pretty wonderful adventure, albeit not without some problems.

In the course of the Editor's investigation, they have found of lot of links that are beneficial to the game master; thus compiled herein.

*This guide seeks to be a compendium of useful knowledge about the Adventure Path, as well as an index to it beyond the published content.*

Please enjoy.

** Spoiler Warning

You're viewing a community-sourced Gamemaster's Guide to running the /Agents of Edgewatch/ Adventure Path from Paizo.

**This is entirely spoilers, by definition.**

** In Progress

As of March 2022, this guide is in progress and development. Your editor is compiling it as they run AoE for their group, so things will generally be added as the game progresses through 2021 and the first half of 2022.

See the [[Colophon][Colophon]] for how you can help contribute.

* Adventure Path Overview

/Agents of Edgewatch/ is the story of the player characters -- the titular
Agents of Edgewatch -- and their journey to understand and defeat the threat
of the Twilight Four, a cabal of devotees to Norgorber in their attempt to
take control of the Primarchy of Absalom.

In [[#node/plot/book1][Book 1 ("The Devil in the Dreaming Palace")]], the Agents will come up through the ranks.

In [[#node/plot/b1c1][Book 1, Chapter 1 ("The Mean Streets of Absalom")]], the characters start their jobs as Agents of Edgewatch with some basic tasks.

In [[#node/plot/b1c2][Book 1, Chapter 2 ("Missing Persons")]], the Agents investigate some missing persons.

In [[#node/plot/b1c2][Book 1, Chapter 3 ("Into the Undercity")]], the Agents follow up on a lead regarding the missing persons, traveling through the under-city to a secret entrance to a nightclub frequented by criminals.

In [[#node/plot/b1c4][Book 1, Chapter 4 ("The Murder Hotel")]], the Agents investigate the reason for the missing persons: a murder hotel operated by a Norgorbor cultist.

--------------------

In [[#node/plot/book2][Book 2 ("Sixty Feet Under")]], the Agents will defeat the first of the Twilight Four – The Skinner – and her murderous cult.

In [[#node/plot/b2c1][Book 2, Chapter 1 ("The Unusual Suspects")]], the Agents are tasked to investigate rumors of an upcoming bank robbery.

In [[#node/plot/b2c2][Book 2, Chapter 2 ("A Penny Saved")]], the Agents put a stop to the bank robbery, catching the Copper Hand red-handed.

In [[#node/plot/b2c3][Book 2, Chapter 3 ("Caught Copper-Handed")]], the Agents take down the Copper Hand thieves guild in their hideout, uncovering their connection to cultists.

In [[#node/plot/b2c4][Book 2, Chapter 4 ("Descent into Death")]], the Agents delve into the Catacombs under the Ascendent Court to track down the Skinsaw cult and it's leader "The Skinner", the first of the Twilight Four.

--------------------

In [[#node/plot/book3][Book 3 ("All or Nothing")]], the Agents will foil the plans of the second of the Twilight Four – The Infector – and his attempt to poison thousands.

In [[#node/plot/b3c1][Book 3, Chapter 1 ("Street Justice")]], the Agents trace from the Skinsaw Cult to a Docks gang who they worked with.

In [[#node/plot/b3c2][Book 3, Chapter 2 ("The House Always Wins")]], the Agents infiltrate an upscale Gala to steal a fearsome device from a casino lockbox.

In [[#node/plot/b3c3][Book 3, Chapter 3 ("Deadly Games")]], the Agents rush to the Blood City Games in the Irorium to head off a large-scale terrorist attack.

--------------------

In [[#node/plot/book4][Book 4 ("Assault on Hunting Lodge Seven")]], the Agents will infiltrate The Infector's temple, capture, and hold them … but ultimately will be arrested and implicated in murder.

In [[#node/plot/b4c1][Book 4, Chapter 1 ("The Noxious Retort")]], the Agents visit an alchemical conference as cover to find ingress to the secret Blackfingers temple to capture The Infector.

In [[#node/plot/b4c2][Book 4, Chapter 2 ("The Gervin Legacy")]], the Agents will defend The Infector from waves of enemies intent on freeing him.

In [[#node/plot/b4c3][Book 4, Chapter 3 ("A Wonderful Time in Harrowland")]], the Agents will investigate a failed harrow-themed-park before ultimately being arrested along with Acting Primarch Wynsal Starborn.

--------------------

In [[#node/plot/book5][Book 5 ("Belly of the Black Whale")]], the Agents will first infiltrate and then break out of prison, then turn their attention to the third of the Twilight Four — The Rumormonger.

In [[#node/plot/b5c1][Book 5, Chapter 1 ("Dishonorably Discharged")]], the Agents earn the trust of a crime lord by taking down rival gangs.

In [[#node/plot/b5c2][Book 5, Chapter 2 ("Belly of the Black Whale")]], the Agents infiltrate the notorious "Black Whale" prison complex in Absalom's Kortos Bay, to break Wynsal Starborn out.

In [[#node/plot/b5c3][Book 5, Chapter 3 ("The Rumormonger’s Stronghold")]], the Agents track down and defeat The Rumormonger in their trap-laden dungeon.

--------------------

In [[#node/plot/book6][Book 6 ("Ruins of the Radiant Siege")]], the Agents will obtain an artifact they need to defeat the fourth of the Twilight Four – The Gray Queen – newly empowered by fulfilling the terms of the Twilight Four's contract with Norgorber.

In [[#node/plot/b6c1][Book 6, Chapter 1 ("Runaway Excavator")]], the Agents stop the rampaging excavator "Graveraker", and find an ally against the last of the Twilight Four.

In [[#node/plot/b6c2][Book 6, Chapter 2 ("The Radiant Spark")]], the Agents search for an incredible artifact called the /Radiant Spark/.

In [[#node/plot/b6c3][Book 6, Chapter 3 ("The Gray Queen's Tower")]], the Agents assault the Gray Queen's fortress.

----------

The [[http:cite:reddit-pabt0r][AP doesn't make it in-your-face obvious up front about the goals of the Twilight Four or their pact with Norgorber]]. Only in the Toolbox entry for Olansa Terimor in Book *6* is the compact revealed…

#+BEGIN_QUOTE
While most who aspire to divinity in Absalom dream of passing the Test of the
Starstone, Olansa’s aspirations were both much more direct and much more
grounded. She pledged her soul to the Gray Master alongside the other members
of the Twilight Four so that when they collectively overthrew Absalom’s
rightful standing primarch and installed one of their own into power, they
would each receive a gift of immense divine power. There would be no need to
dare the unknown dangers within the Starstone Cathedral—only a single
momentous act of devotion to the God of Thieves.
— cite:paizo-aoe-book6#page=90
#+END_QUOTE

* Meta
  :PROPERTIES:
  :CUSTOM_ID: node/meta
  :END:
** Length
   :PROPERTIES:
   :CUSTOM_ID: node/meta/length
   :END:

This – of course – is going to vary dramatically based on the table at which the game is being run, how many side-quests and how much character-service is done, &c.

Based naïvely on the idea that characters should advance in level every 3-4 gaming sessions, a Level 1 - 20 Adventure should take between 55 and 80 sessions, or 1 - 1.5 years at 1 session/week.

This seems to be supported by the experience at some tables, with people reporting "1-2 years" to finish an AP.

[[http:cite:paizo-forums-rzs4349c_18][On the Paizo Forums, Kazimir_980 reports taking seven 3-to-6-hour sessions to get through book 1.]]

[[http:cite:reddit-n39df5][On Reddit, u/DragoldC42's group took 9 months for the entire AP.]]

[[http:cite:reddit-q9a8a1][u/Merithras asked a similar question that got some good responses, as well.]]

** Difficulty
   :PROPERTIES:
   :CUSTOM_ID: node/meta/difficulty
   :END:

Like many APs, the Agents of Edgewatch is considered by some to be … "tuned hot" … "spicy" … "extremely deadly for PCs" … a "TPK machine". This is generally and especially true in the first few PC levels.

- [[http:cite:reddit-q42xy3][This thread from u/Sachiel2014 has a lot of great detail about specific ways things might be difficult for specific parties and tables.]]

- [[http:cite:paizo-rzs43851][On the Paizo forums, Calybos1 prompts a good discussion of the early difficulty of Agents of Edgewatch.]]

- [[http:cite:paizo-rzs43g90][VampByDay lists some specific concerns with early fights in the first two books of the AP.]]

- The bulk of the discussion at [[https://www.reddit.com/r/Pathfinder2e/comments/oknoo0/agents_of_edgewatch_catacombs_are_a_death_trap/]["Catacombs are a death trap"]] is about the general perception of the difficulty of these early APs.

- [[http:cite:paizo-rzs43ftq]["Zandu the Devourer" was frustrated by repeated near-TPKs and PC deaths, and others shared their experiences.]]

- [[https://www.reddit.com/r/Pathfinder2e/comments/oknoo0/agents_of_edgewatch_catacombs_are_a_death_trap/h59ksqb/?utm_source=reddit&utm_medium=web2x&context=3][Some people saying this might be outliers, though.]]

- [[http:cite:reddit-xcdyww]["u/BigNorseWolf" asks "Is Agents of Edgewatch a meatgrinder or is it PF2 ?", prompting a long thread of 142 comments.]]
  The following day, [[http:cite:reddit-xdelju][a since-deleted Reddit user asks "is Agents of Edgewatch a good AP to run, or is it too difficult/unbalanced?"]]; apparently, not done /quite/ done, another 45 comments are added.

----------

In general, in PF2E, when rebalancing encounters for a larger party, you should prefer "more weaker" enemies, not "single up-leveled" enemies.

- the PF2 math is too tight for even-stronger enemies
- too hard to land hits, too high chances of crits (both directions)

----------

- [[http:cite:paizo-rzs4371h]["NewNameLater" asks about scaling the adventure and its encounters down for a "buddy cop" duo play.]]

** Quality
   :PROPERTIES:
   :CUSTOM_ID: node/meta/quality
   :END:

[[http:cite:reddit-raouq8][Tarondor made a guide to the Adventure Paths. HERE IT IS.]] They rank /Agents of Edgewatch/ 16 out of 33. A poll they did of 142 people across Reddit and the Paizo forums, ranked /Agents of Edgewatch/ 12/33. That puts it in the middle of the "Pretty Damn Good!" pack.

That same guide is referenced in response to [[http:cite:reddit-teucpn][u/spacemonkeydm's inquiry regarding reviews of _Agents of Edgewatch_]].

** On Being Police
   :PROPERTIES:
   :CUSTOM_ID: node/meta/on_being_police
   :END:

Some tables will have objections or distaste for playing the role of police,
or perhaps more specific practices like doing lethal damage by default or the
AP-encouraged practice of "legalized theft" of property.

#+BEGIN_COMMENT
The publication of the Adventure Path was in fact delayed by multiple months
due to [FIXME: not right?] protests associated with the Black Lives Matter movement in the United
States in the summer of 2020.
#+END_COMMENT

The AP has some text detailing ways to handle the main objections to how it
assumes "policing" will be done in the way that it is written.

Even still, some people fundamentally feel aspects of this Adventure Path is
somewhere between "in poor taste" and "downright offensive".

The main objections are:

- The immediate discretion of the Agents – rather than any formal judicial process and jurisprudence – is strongly encouraged.

- Pathfinder 2E RAW does lethal damage by default, and players take non-trivial penalties for attempting to do non-lethal damage.

- The PCs are encouraged by the AP to simply "requisition" any valuable gear or consumables they encounter from citizens in the course of their duty, in lieu of pay.

  - ​[[http:cite:reddit-n39df5][u/DragoldC42, reddit.com/r/Pathfinder2e, 2021-05-02]]
    #+HTML: <details>
    #+HTML:   <summary>"being able to confiscate property freely feels weird"</summary>
    #+BEGIN_QUOTE
  - The agents, as policemen, being able to confiscate property freely feels
    weird in this part of the adventure, when they are mostly dealing with
    ordinary citizens. My group didn’t really care that much, but it was a
    good topic to raise in session zero and clear out our preferences on
    anyway. It's very easy in any case to just give the characters a salary.In
    my experience, later on in the AP, when the agents are dealing with
    criminals and cults, it feels much more justified to use what they can
    take, or to give it back for a bounty.

  — cite:reddit-n39df5
  #+END_QUOTE
    #+HTML: </details>

  - — cite:paizo-rzs4349b-21
    #+BEGIN_COMMENT uncleared quote
Police, stealing people's personal property for personal enrichment. Oof.

So, when I run this I'll have to redo the entire treasure system.
    #+END_COMMENT

- If even not immediately stolen by the Agents, loot returned to the police is effectively fenced and the usual sale value (50%) is given to the Agents.

  - cf. — cite:paizo-rzs4349b-31
    #+BEGIN_COMMENT uncleared-quote
If I run this, I'd probably deal with treasure through a combination of better gear provided by Headquarters, contributions from grateful festival organizers, and letting the PCs' equipment level up as they advance. Definitely no looting bodies or pocketing arbitrary fines (or citizens slipping purses of gold into the officers' pockets).

Maybe add a supply officer NPC to the Edgewatch station who issues higher-level equipment as the PCs become authorized for it -- but only if they fill out the proper forms in triplicate, of course.

As for the new gear, it's a bit disappointing the nightstick is such a poor weapon. And I'm definitely not going to be using the blindpepper bomb and tube in my game, given the real-world issues around the casual overuse of tear gas and pepper spray. Maybe some sort of sleep/knockout gas alchemical weapon would be a better alternative?
    #+END_COMMENT

- The Agents are tasked to, well, be police: to enact violence on behalf of the State to resolve disputes.

  - The very first encounter is "beat a bunch of citizens unconscious".
    - cf. — cite:paizo-rzs4349b-52
      #+BEGIN_COMMENT uncleared-quote
At one point, the PCs, who are cops, wind up in a situation where they may have to beat citizens unconscious. And not depraved or awful criminals, just people in a bar who are belligerently drunk. Some of them are even Good aligned.

The AP encourages using social skills to deescalate the situation, and I don't think it's all that bad, but it stuck out to me as a bit awkward in terms of timing given real world events.

The PCs also get to 'fine' people and keep the money and return to the station and then requisition gear from defeated opponents...which, while it makes sense in-setting, given the use of civil forfeiture by real police it still leaves a bit of a sour taste in my mouth. This part is easy enough to ignore or change in various ways, but it's less than ideal.

Those are really the only issues I found with it beyond the premise itself being poorly timed, and the first is not a big deal, just slightly off-putting.
      #+END_COMMENT

  - The Agents are tasked to – effectively — break up a labor action in the role of police, in Book 1 Chapter 2.

    - And the [[http:cite:paizo-rzs4349b-311][kobolds go from protesting pay to being "extremely homicidal"]], to boot.
      Though as [[http:cite:paizo-rzs4349b-314]["Benchak the Nightstalker" points out, there is a "schism" in the ranks that is useful to highlight.]]
      [[http:cite:paizo-rzs4349b-327]["EdwinM" suggests taking it a different direction entirely]],
      and [[http:cite:paizo-rzs4349b-328]["SilentCal" has another alternate scenario.]]
      [[http:cite:paizo-rzs4349b-332]["Data Lore" offers their modifications to the chapter.]]


There are a number of solutions to these problems:

- Pay the Agents a salary to keep in line with Treasure By Level without making it a direct outcome of their activities.

- Simply change the rules to make non-lethal damage default and at no penalty; give all magical characters the [[https://2e.aonprd.com/Feats.aspx?ID=1835][Nonlethal Spell Metamagic Feat (2)]].

  - Note that the Adventure Path does include some item and spells specifically to help address these issues.

- Create some sort of deus ex machina (eg. a magical badge) that provides objective truth regarding the "Lawfulness" and "Goodness" (or at least Neutrality) of the Agent's actions while in the field.

- Use [[https://2e.aonprd.com/Rules.aspx?ID=1357][Automatic Bonus Progression]] to ease some of the pressure to provide loot.

----------

[[http:cite:paizo-rzs436hc-25][Naurgul describes a clever RAW-mechanical way to help with the lethal/non-lethal damage issue]], inside a larger thread on the topic…

#+HTML: <details>
#+HTML:   <summary>For my group, all I changed was to apply PC dying rules to NPCs. […]</summary>
#+BEGIN_QUOTE
For my group, all I changed was to apply PC dying rules to NPCs. That allows my players to deal lethal damage until the last hit or try to save the enemy combatants after they fall down (which comes at the expense of actions that could have been used on ending the fight).

[…]

It seems to me that this is the best of both worlds, meaning I don't restrict my PCs too much but at the same time being nonlethal is not trivially easy to achieve either.

— cite:paizo-rzs436hc-25
#+END_QUOTE
#+HTML: </details>

----------

[[http:cite:paizo-rzs4349b-382][In the Paizo AoE Book 1 thread, "GreatGraySkwid" details their changes for the "Asset Forfeiture Loot System"]] and a
[[https://template.pf2.tools/v/f1WTlqVT-peackeeper-badge][Peacekeeper's Badge]] (along with some other Book 1 plot modifications).

[[http:cite:reddit-q98yrs][u/Umutuku asks for some examples of play with the common alternative solutions]], and the [[https://rollforcombat.com/category/podcast/agents-of-edgewatch/][Roll for Combat : Agents of Edgewatch podcast]] has implemented some of these options, as well as others.

#+BEGIN_COMMENT uncleared-quote paizo-rzs4349b-85
A lot of people have been posting about how they are changing the "loot"
system from the AP and I wanted to share my approach as an alternative that
requires fewer bigger changes. I think the fact that Edgewatch doesn't have
the funding is a good plot development to start with and I want to keep that
aspect; however, I don't want to encourage "looting" civilians to keep pace
with the game leveling wealth mechanics.

Instead, I want to do 2 things.

1. Give characters the choice to be responsible and require meticulously
cataloging evidence or rewards given by grateful civilians. Through this, I
plan to reward players further in the AP based on their choices to be
responsible.

2. Have consequences for operating outside their responsibilities as city guards.

My goal behind that is for the players to choose the type of guard they want
to become, but to have consequences for those type of decisions. This could
mean their character being kicked from the force or imprisoned, which will
equate, potentially, to character death from a story perspective.

There are districts with corruption and guards that are corrupt. The
Edgewatch, however, under Lieutenant Lavarsus will not put up with those
shenanigans. Those are just some thoughts I have around my run which I'm
starting in about a month or so.
#+END_COMMENT
[[http:cite:paizo-rzs4349b-85][On the Paizo Forums, "tuxagon" shares some thoughts about their plans for a more minimal change to the system.]]

[[http:cite:paizo-rzs4349b-152]["thewastedwalrus" points out that the detestable real-world practice of civil asset forfeiture is not quite the same as what's outlined in the AP.]] But that opinion is not shared by all in the following worthy-of-reading comments.
#+BEGIN_COMMENT uncleared-quote-paizo-rzs4349b-152
From my understanding of civil forfeiture, the law set in the book is somewhat different to that. The guards are supposed to be only taking an amount of goods/money from the offending parties equal to or less than the amount of money that would be the fine for the crime, as opposed to civil forfeiture where the police take possessions from suspected criminals until they are able to prove that those possessions are not related to the crime.

Edgewatch's requisitioning here is supposed to be the punishment for the crime committed, whereas civil forfeiture is separate to any punishments the crime would normally warrant and can be arbitrarily much greater than the scale of the crime. A closer comparison to Edgewatch's policy might be traffic tickets that are paid on-the-spot.
#+END_COMMENT

[[http:cite:paizo-rzs4349b-120][GayBirdGM]] and [[http:cite:paizo-rzs4349b-121][Sporkedup]] both offer some counterbalance: there's plenty of bad things that the heroes are supposed to fight against because that's what these games are about, and the rest can pretty easily be worked around.

[[http:cite:reddit-o0y78z][u/brungry asks for some help with their party's Lawful Goodness in their roles, which generally has some good discussion of the overall issues with the AP.]]

In response, [[http:cite:reddit-o0y78z-h1yln02][u/Naurgul offers some interesting ideas…]]

#+BEGIN_QUOTE
[[https://2e.aonprd.com/Rules.aspx?ID=1357][Automatic Bonus Progression]] is a must I would say if your players are against this looting/fining/requisitioning thing. It really cuts down the amount of treasure the PCs need to have to stay competitive.

In my game I also had Kemeneles and Eunice organise a crowdfunding event behind their backs. […]

[…]

Finally, reformed criminals might offer some of their equipment as a gift. In my game Ralso gave them her ring of discretion as a gift for the help they're giving her to atone for her crimes and prepare for her upcoming trial.
— cite:reddit-o0y78z-h1yln02
#+END_QUOTE

[[http:cite:reddit-o0y78z-h1yrupj][In that same thread, u/GreatGraySkwid points to]] a Paizo forum thread from
[[http:cite:paizo-rzs438h4]["Imnotgoodwithnames", specifically about using Earned Income as an alternative reward mechanism.]]

[[http:cite:reddit-10gx9cq]["u/PapaHemmingway" asks about ways to improve the AP, in part focused on these similar themes.]]

----------

This is an area of running the AP where it will be important to be very clear with your players (and ensuring they're clear with each other) to make sure that everyone is playing a game they are comfortable playing.

----------

[[http:cite:reddit-wt04fq][In "I think I'm bouncing off of my first adventure path (Agents of Edgewatch)", "u/Pandarandrist" brings up a number of these same concerns after running the game for a while, with a few others mixed in.]]

----------

On a different note, [[http:cite:paizo-rzs43cn3][on the Paizo forums, "Evil Paul" highlights a few narrative themes that they feel are missing from the AP]]: "Investigations and Actual Police Work", "Police Corruption", "Politics, Legailities, Bureaucratic conflict", and finally "Difficult Decisions".
In the thread, [[http:cite:paizo-rzs43cn3-5][Naurgul links to some content expansions they made along similar lines.]]

----------

[[http:cite:reddit-snapx6]["u/Repulsive-Ad7501" asks a question about an infiltration mission in B4C1]], but the discussion mostly turns to various group's difficulty suspending disbelief for the AP.

*** Buddy Cops

[[http:cite:paizo-rzs434h7][On the Paizo Forums, "zen_fishy" shares]] some [[https://docs.google.com/document/d/1RZMR4A4YeGRqVDkQpIzvy9yMfPdDMxSXc_8Oax14c7s/edit][homebrew teamwork-influenced downtime rules that play into a "buddy-cop" aesthetic]].

** On Being Adventurers, not Police
   :PROPERTIES:
   :CUSTOM_ID: node/meta/on_being_adventurers
   :END:

The AP makes a mention about running the game with the PCs as Adventurers, rather than as official police.

[[http:cite:reddit-ngocjr][u/Amaya-hime asks for some clarity on how to do that.]] Plenty chime in with suggestions, and [[http:cite:reddit-ngocjr-gys0hst][u/Naurgul has an idea to get them through at least Book 1.]] [[http:cite:reddit-ngocjr-gyt9uz2][u/DandiAndy relays that their friend's game]] has a group of [[https://2e.aonprd.com/Feats.aspx?ID=2083][Vigilantes]] using the [[https://2e.aonprd.com/Rules.aspx?ID=1333][Free Archetype rules]], which seems like a clever spin on the AP (though might require /substantial/ editing to make work).

** United Paizo Workers

In October 2021 – about 1 year after the final book of /Agents of Edgewatch/ was published in December 2020 – Paizo labor organized and formed the /United Paizo Workers/.

[[https://www.reddit.com/r/Pathfinder2e/comments/q85tgm/the_new_paizo_unions_logo_is_a_reference_to_the/][Their logo is a reference to the Kobold Worker's Union from Book 1, Chapter 2.]]

** Related Content
*** _The Broken Scales_ and _Balancing the Scales_

On the Paizo Forums, [[http:cite:paizo-rzs43gj3]["GreatGraySkwid" notes]] that while it will require some adaptation…

#+BEGIN_QUOTE
[…] [[https://paizo.com/products/btq023di?Pathfinder-Society-Quest-10-The-Broken-Scales][/The Broken Scales/]] ties directly into the events of the AoE AP, and [[https://paizo.com/products/btq024zk?Pathfinder-Society-Scenario-205-Balancing-the-Scales][/Balancing the Scales/]] indirectly, as they both describe the havoc and aftermath caused by the mysterious activation and disappearance of a Graveraker prototype, an immense clockwork drill. Canonically, these events occurred in the year prior to the festival, but it's easy enough to move them (or some version of them) back to being approximately concurrent with the disappearance of Graveraker and tie them into the overall plot.
— cite:paizo-rzs43gj3
#+END_QUOTE

As many feel the Graveraker is not prominent enough through most of the AP, these scenarios might be useful for GMs or groups that want more of it.

* Enemy Makeup and Composition
  :PROPERTIES:
  :CUSTOM_ID: enemy-makeup
  :END:

The following is a summary of the enemies and challenges as written in the AP,
book by book.  This can help answer questions about – say – the suitability of
Champion focused on fighting undead (vs. elementals), to help guide the
player's characters to meet the challenges in the AP.

** Book 1

*Summary by Type*

| *type*         | *ch 1* | *ch 2* | *ch 3* | *ch 4* |
| *humanoid*     |      8 |     15 |      4 |      4 |
| *aberration*   |      1 |        |      1 |      1 |
| *animal/beast* |      8 |      4 |      2 |      1 |
| *construct*    |        |        |        |      4 |
| *devil*        |        |        |        |      1 |
| *elemental*    |        |        |        |      2 |
| *fey*          |        |        |        |      1 |
| *fiend*        |        |        |      2 |        |
| *ooze*         |        |        |      1 |      1 |
| *undead*       |      4 |        |      3 |        |

#+HTML: <div class="beta" style="display:none">
*Summary by Alignment (count)*

|              | *Good:3* | *Neutral:35* | *Evil:47* |
| *Lawful:22*  |          |              |        22 |
| *Neutral:47* |        1 |           29 |        17 |
| *Chaotic:16* |        2 |            6 |         8 |

*Summary by Alignment (Aggregate CR)*

|                   | *Good (4)* | *Neutral (59.25)* | *Evil (79.5)* |
| *Lawful (36)*     |            |                   |            36 |
| *Neutral (85.25)* |          2 |             55.25 |            28 |
| *Chaotic (21.5)*  |          2 |                 4 |          15.5 |

#+HTML: </div>

*Summary by Chapter*

| *chapter 1*                                |  *lvl* | *traits*                    |        |
|--------------------------------------------+--------+-----------------------------+--------|
| 6× Human                                   | -1 - 2 | humanoid                    | N      |
| 2× Goblin Warrior, "Grunka" & "Pelmo")     |     -1 | humanoid                    | CE     |
| 4× [[https://2e.aonprd.com/Monsters.aspx?ID=372][Skeleton Guard]]                          |     -1 | undead, skeleton            | NE     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=83][Cockatrice]]                              |      3 | beast                       | N      |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=328][Owlbear]]                                 |      3 | animal                      | N      |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=354][Rust Monster]]                            |      4 | aberration                  | N      |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=270][Hyenas]]                                  |      0 | animal                      | N      |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=381][Giant Viper]]                             |      2 | animal                      | N      |
| 1× Almiraj                                 |      1 | animal/beast                |        |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=49][Flash Beetle]]                            |     -1 | animal                      | N      |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=23][Ankhrav]]                                 |      3 | animal                      | N      |
|--------------------------------------------+--------+-----------------------------+--------|
| *chapter 2*                                |  *lvl* | *traits*                    |        |
|--------------------------------------------+--------+-----------------------------+--------|
| 15× [[https://2e.aonprd.com/MonsterFamilies.aspx?ID=65][Kobolds]]                                |  0 - 2 | humanoid                    | LE     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=386][Hunting Spider]]                          |      1 | animal                      | N      |
| 4× [[https://2e.aonprd.com/Monsters.aspx?ID=51][Bloodseeker]]                             |     -1 | animal                      | N      |
| 1× Boiling Fountain                        |      2 | hazard                      |        |
| 2× Dart Barage                             |      3 | hazard                      |        |
| 2× Exploding Statue                        |      2 | hazard                      |        |
| 1× Hampering Snare                         |      1 | snare                       |        |
|--------------------------------------------+--------+-----------------------------+--------|
| *chapter 3*                                |  *lvl* | *traits*                    |        |
|--------------------------------------------+--------+-----------------------------+--------|
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=321][Gelatinous Cube]]                         |      3 | ooze                        | N      |
| 3× [[https://2e.aonprd.com/Monsters.aspx?ID=218][Ghoul]]                                   |      1 | undead                      | CE     |
| 2× Ratfolk, "Kekker" & "Greff"             |      2 | humanoid                    | LE     |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=65][Calgini Creepers]], "Tiano" & "Morviggus" |      2 | humanoid                    | CN     |
| 2× Vargouilles                             |      2 | animal/beast, fiend         | NE     |
| 1× Grick                                   |      3 | aberration                  | N      |
|--------------------------------------------+--------+-----------------------------+--------|
| *chapter 4*                                |  *lvl* | *traits*                    |        |
|--------------------------------------------+--------+-----------------------------+--------|
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=300][Mimic]]                                   |      4 | aberration                  | N      |
| 1× Hidden Chute                            |      3 | hazard                      |        |
| 1× Flying Guillotine                       |      5 | hazard                      |        |
| 2× Summoning Rune                          |      5 | hazard                      |        |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=187][Cinder Rat]]                              |      3 | elemental                   | N      |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=110][Barbazu Devil]]                           |      5 | devil, fiend                | LE     |
| 1× Canopy Drop                             |      4 | hazard                      |        |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=381][Giant Viper]]                             |      2 | animal                      | N      |
| 2× Humanoid                                |      2 | humanoid                    | NG, CG |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=349][Redcap]]                                  |      4 | fey                         | CE     |
| 1× Humanoid, "Ralso"                       |      4 | humanoid                    | NE     |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=383][Soulbound Doll]]                          |      2 | construct                   | NE, CE |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=557][Attic Whisperer]]                         |      4 | undead                      | NE     |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=20][Animated Statue]]                         |      3 | construct                   | N      |
| 1× Gas Trap                                |      5 | hazard                      |        |
| 1× Plunger Chute                           |      3 | hazard                      |        |
| 6× Pickled Punk                            |      1 | undead                      | NE     |
| 4× Shredskin                               |      2 | undead                      | NE     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=322][Ochre Jelly]]                             |      6 | ooze                        | N      |
| 3× [[http://2e.aonprd.com/Monsters.aspx?ID=413][Wight]]                                   |      3 | undead                      | LE     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=985][Binumir]]                                 |      3 | undead, incorporeal, spirit | LE     |
| 1× Human, "Henrid Pratchett"               |      6 | humanoid, serial killer     | CE     |

** Book 2

*Summary by Type*

| *type*         | *ch 1* | *ch 2* | *ch 3* | *ch 4* |
| *humanoid*     |     15 |      9 |     14 |     15 |
| *aberration*   |      1 |        |        |      6 |
| *animal/beast* |      7 |        |      1 |      7 |
| *construct*    |        |      2 |        |      8 |
| *daemon*       |        |        |        |      1 |
| *devil*        |        |        |        |        |
| *elemental*    |        |        |        |        |
| *fey*          |        |        |        |        |
| *fiend*        |        |        |        |      2 |
| *leshy*        |        |        |        |      4 |
| *ooze*         |        |        |      2 |      4 |
| *undead*       |        |        |        |     12 |

*Summary by Chapter*

| *chapter 1*                                  | *lvl* | *traits*                      |       |
|----------------------------------------------+-------+-------------------------------+-------|
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=406][Wasp Swarm]]                                |     4 | animal, swarm                 | N     |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=203][Ether Spider]]                              |     4 | beast, ethereal               | N     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=866][Xill]]                                      |     6 | aberration, ethereal          | LE    |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=125][Riding Dog]]                                |     2 | animal                        | N     |
| 14× Humanoid                                 | 2 - 5 | humanoid                      | CE/LE |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=59][Bugbear Tormentor]]                         |     3 | humanoid, goblin              | NE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=62][Bunyip]]                                    |     3 | animal                        | N     |
|----------------------------------------------+-------+-------------------------------+-------|
| *chapter 2*                                  | *lvl* | *traits*                      |       |
|----------------------------------------------+-------+-------------------------------+-------|
| 9× Humanoid                                  | 2 - 4 | humanoid                      | LE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=771][Dig-Widget]]                                |     5 | construct                     | N     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=1305][Skinstitch]]                                |     5 | construct                     | N     |
|----------------------------------------------+-------+-------------------------------+-------|
| *chapter 3*                                  | *lvl* | *traits*                      |       |
|----------------------------------------------+-------+-------------------------------+-------|
| 10× Humanoid                                 | 5 - 8 | humanoid                      | CE/LE |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=997][Vaultbreaker Ooze]]                         |     5 | ooze                          | N     |
| 1× Hallucination Powder Trap                 |     6 | hazard                        |       |
| 1× Spinning Blade Pillar                     |     4 | hazard                        |       |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=331][Tiefling Adept]]                            |     3 | humanoid, tiefling            | CE    |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=858][Weretiger]]                                 |     4 | human, humanoid, werecreature | NE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=44][Basilisk]]                                  |     5 | beast                         | N     |
|----------------------------------------------+-------+-------------------------------+-------|
| *chapter 4*                                  | *lvl* | *traits*                      |       |
|----------------------------------------------+-------+-------------------------------+-------|
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=22][Giant Animated Statue]]                     |     7 | construct                     | N     |
| 6× [[https://2e.aonprd.com/Monsters.aspx?ID=373][Skeletal Champion]]                         |     3 | undead, skeleton              | NE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=171][Dullahan]]                                  |     9 | undead                        | LE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=308][Nightmare]]                                 |     6 | beast, fiend                  | NE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=353][Roper]]                                     |     9 | aberration                    | CE    |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=323][Black Pudding]]                             |     7 | ooze                          | N     |
| 1× Hands of the Forgotten                    |     8 | hazard                        |       |
| 1× Life Magnets                              |     7 | hazard                        |       |
| 1× Tyrroicese                                |    10 | construct, ooze; unique       | NE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=322][Ochre Jelly]]                               |     6 | ooze                          | N     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=316][Ofalth]]                                    |    10 | aberration                    | CE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=827][Tick Swarm]]                                |     9 | animal, swarm                 | N     |
| 3× [[https://2e.aonprd.com/Monsters.aspx?ID=327][Otyugh]]                                    |     4 | aberration                    | N     |
| 4× [[https://2e.aonprd.com/Monsters.aspx?ID=281][Fungus Leshy]]                              |     2 | leshy, fungus                 | N     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=1305][Skitterstitch]]                             |     6 | construct, mindless           | N     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=385][Spider Swarm]]                              |     0 | animal, swarm                 | N     |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=989][Bone Skipper Swarm]]                        |     6 | animal, swarm                 | N     |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=316][Ofalth]] Zombie                             |     7 | aberration, undead, zombie    | NE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=89][Ceustodaemon (Guardian Daemon)]]            |     6 | fiend, daemon                 | NE    |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=238][Flesh Golem]]                               |     8 | construct, golem              | N     |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=1305][Skinstitch]]                                |     5 | construct                     | N     |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=549][Army Ant Swarm]]                            |     5 | animal, swarm                 | N     |
| 14× Humanoid                                 |   5-9 | humanoid                      | CE/LE |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=771][Dig-widget]]                                |     4 | construct                     | N     |
| 4× [[https://2e.aonprd.com/Monsters.aspx?ID=992][Excorion]]                                  |     7 | undead                        | NE    |
| 1× human, "Wrent Dicaspiron" - "The Skinner" |    10 | humanoid                      | CE    |

** Book 3

It might seem like something's missing with Book 3, but the majority of Chapter 2 is a casino heist using the [[https://2e.aonprd.com/Rules.aspx?ID=1221][Infiltration Rules]] from the Game Mastery Guide.

*Summary By Type*

| *type*         | *ch 1* | *ch 2* | *ch 3* |
| *humanoid*     |     15 |      2 |     11 |
| *aberration*   |        |        |        |
| *animal/beast* |        |        |      4 |
| *construct*    |      1 |        |        |
| *daemon*       |      1 |        |        |
| *devil*        |        |        |        |
| *elemental*    |        |        |      3 |
| *fey*          |      1 |      2 |        |
| *fiend*        |        |      1 |        |
| *leshy*        |        |        |        |
| *ooze*         |        |        |        |
| *undead*       |        |        |      2 |

*Summary by Chapter*

| *chapter 1*                            | *lvl* | *traits*                       |      |
|----------------------------------------+-------+--------------------------------+------|
| 14× Gang Tough                         | 6 - 9 | humanoid                       | N/NE |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=593][Meladaemon (Famine Daemon)]]          |    11 | daemon, fiend                  | NE   |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=998][Avarek]]                              |     8 | fey                            | NE   |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=239][Alchemical Golem]]                    |     9 | construct, golem               | N    |
| 1× Gang Leader, "Bloody Berleth"       |    11 | humanoid, orc                  | NE   |
|----------------------------------------+-------+--------------------------------+------|
| *chapter 2*                            | *lvl* | *traits*                       |      |
|----------------------------------------+-------+--------------------------------+------|
| 1× Bouncer                             |     8 | humanoid                       | N    |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=1003][Svartalfar]]                          |     8 | fey                            | LE   |
| 1× Half-Elf Occultist, "Scathka"       |    12 | humanoid                       | NE   |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=462][Velstrac interlocutor]], "Ekimilixus" |    12 | fiend, velstrac                | LE   |
|----------------------------------------+-------+--------------------------------+------|
| *chapter 3*                            | *lvl* | *traits*                       |      |
|----------------------------------------+-------+--------------------------------+------|
| 4× [[https://2e.aonprd.com/Monsters.aspx?ID=1000][Eberarks]]                            |    10 | beast, fire                    | NE   |
| 2× Irorian Skeleton                    |    11 | undead, skeleton, mindless     | NE   |
| 3× [[https://2e.aonprd.com/Monsters.aspx?ID=200][Elemental Tsunami]]                   |    11 | elemental, water, aquatic      | N    |
| 8× Shikwashim Mercaneries              |     9 | humanoid, lizardfolk           | NE   |
| 1× Elf, "Franca Laurentz"              |    13 | humanoid, elf                  | CN   |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=220][Hill Giant]]                          |     7 | giant, earth, humanoid         | CE   |
| 1× Lizardfolk, "Oggvurm the Merciless" |    14 | humanoid, lizardfolk, ravenile | NE   |

** Book 4

*Summary By Type*

| *type*         |  *ch 1* | *ch 2* | *ch 3* |
| *humanoid*     | 49 - 64 |     15 |      3 |
| *aberration*   |         |      2 |      3 |
| *animal/beast* |       2 |        |        |
| *astral*       |         |      5 |        |
| *celestial*    |       1 |        |        |
| *changeling*   |       1 |        |        |
| *construct*    |         |      3 |        |
| *daemon*       |         |        |        |
| *devil*        |         |        |        |
| *dragon*       |         |        |      1 |
| *elemental*    |         |        |        |
| *fey*          |         |        |      1 |
| *fiend*        |       2 |        |      1 |
| *leshy*        |         |        |        |
| *ooze*         |         |        |        |
| *undead*       |       1 |      2 |      1 |


*Summary by Chapter*

| *chapter 1*                            |   *lvl* | *traits*                              | *A*          |
|----------------------------------------+---------+---------------------------------------+--------------|
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=90][Leukodaemon (Pestilence Daemon)]]     |       9 | fiend, daemon                         | NE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=547][Ankou]]                               |      14 | fey                                   | LE           |
| (13 + 5d4)× humanoid                   |   5 - 6 | humanoid                              | CE/NE/LE, CN |
| 19× humanoid                           |  9 - 12 | humanoid                              | CE/NE/LE, CN |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=59][Bugbear Tormentor]]                   |       3 | humanoid, goblin                      | NE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=282][Lich]]                                |      12 | undead; rare                          | NE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=79][Changeling Exile]]                    |       3 | changeling, humanoid                  | CN           |
| 1× Secret-keeper, "Velberi Jallist"    |      14 | humanoid                              | NE           |
| 5× Poison Eater                        |       8 | humanoid                              | CE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=15][Balisse (Confessor Angel)]]           |       8 | celestial, angel                      | NG           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=1005][Jorogumo]]                            |      13 | humanoid                              | NE           |
| 2× Joro Spider                         |       8 | animal                                | N            |
| 1× Stabbing Beast                      |      15 | fiend, herald                         | NE           |
| 1× "Jonis Flakfatter" - "The Infector" |      16 | humanoid                              | NE           |
|----------------------------------------+---------+---------------------------------------+--------------|
| *chapter 2*                            |   *lvl* | *traits*                              | *A*          |
|----------------------------------------+---------+---------------------------------------+--------------|
| 12× humanoid                           |  9 - 12 | humanoid                              |              |
| 3× Clockwork Assassin                  |      13 | construct, clockwork                  | N            |
| 5× [[https://2e.aonprd.com/Monsters.aspx?ID=367&PWL=true][Shining Children]]                    |      12 | astral                                | CE           |
| 3× humanoid                            | 13 - 14 | humanoid                              | NE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=251][Lesser Death]]                        |      16 | undead, rare                          | NE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=713][Leng Spider]]                         |      14 | aberration, dream, uncommon           | CE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=343][Quelaunt]]                            |      15 | aberration                            | CE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=283][Demilich]]                            |      15 | undead, rare                          | NE           |
|----------------------------------------+---------+---------------------------------------+--------------|
| *chapter 3*                            |   *lvl* | *traits*                              | *A*          |
|----------------------------------------+---------+---------------------------------------+--------------|
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=482][Cornugon]]                            |      16 | fiend, devil                          | LE           |
| 1× Shatterling                         |      14 | fey, uncommon                         | CE           |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=398][Uthuls]]                              |      14 | elemental, air                        | CE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=422][Zaramuun]]                            |      16 | elemental, earth                      | CE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=39][Banshee]]                             |      17 | undead, spirit, incorporeal, uncommon | CE           |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=871][Zomok]]                               |      16 | dragon, plant                         | N            |
| 3× [[https://2e.aonprd.com/Monsters.aspx?ID=414][Will-o-Wisp]] (variant)               |      13 | aberration, air, uncommon             | CE           |
| 2× [[https://2e.aonprd.com/NPCs.aspx?ID=927][humanoid cultist]]                    |      14 | humanoid                              | NE?          |
| 1× The Rabbit Prince                   |      17 | humanoid, halfling                    | CE           |

** Book 5

*Summary By Type*

| *type*         | *ch 1* | *ch 2* | *ch 3* |
| *humanoid*     |     11 |     46 |        |
| *aberration*   |      1 |      4 |      2 |
| *animal/beast* |        |      2 |      1 |
| *astral*       |        |        |        |
| *celestial*    |        |        |        |
| *changeling*   |        |        |        |
| *construct*    |      1 |      4 |  24-27 |
| *daemon*       |        |        |        |
| *devil*        |        |        |        |
| *dragon*       |        |        |        |
| *elemental*    |        |      2 |        |
| *fey*          |        |        |        |
| *fiend*        |        |        |      5 |
| *hag*          |        |      3 |        |
| *leshy*        |        |        |        |
| *plant*        |      7 |        |        |
| *ooze*         |      7 |        |        |
| *undead*       |      9 |        |        |

*By Chapter*

*Note:* The approximately 50 humanoids and undead involved in the "The Shoot-Out" at the House of the Planes at the end of Chapter 1 are not included below, since the actual fight will be highly variable.

#+BEGIN_COMMENT
| *part 4: not intended for combat*          |       |                             |     |
| 50× humanoids                              | 11-17 | humanoid, undead, tiefling, |     |
#+END_COMMENT

| *chapter 1*                                     |   *lvl* | *traits*                             | *A* |
|-------------------------------------------------+---------+--------------------------------------+-----|
| 1× Zealborn, "Miogimo"                          |      17 | undead, unique                       | CE  |
| 3× Shadow Guard                                 |      11 | humanoid                             | CE  |
| 8× Zeal-Damned [[https://2e.aonprd.com/Monsters.aspx?ID=218][Ghoul]] (variant)                  |      10 | undead, ghoul                        | CE  |
| 1× Garrote Master Assassin                      |      16 | humanoid                             | LE  |
| 6× Carnivorous Mushroom ([[https://2e.aonprd.com/Monsters.aspx?ID=209][Giant Flytrap]])         |      11 | plant, mindless                      | N   |
| 7× Children of Venom                            |      13 | humanoid, ooze; uncommon             | NE  |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=393][Terotricus]], "Agoltholch, Bringer of Rot"     |      19 | fungus; rare                         | CE  |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=737][Naga]], "Mother Venom"                         |      17 | aberration; unique                   | NE  |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=408][Wemmuth]]                                      |      15 | plant                                | NE  |
| 6× Bloody Barber goon                           |      12 | humanoid, rogue                      | CE  |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=242&PWL=true][Iron Golem]] (variant)                         |      14 | construct, golem, mindless           | N   |
| 1× Gangster                                     |      17 | humanoid, tiefling; unique           | CE  |
|-------------------------------------------------+---------+--------------------------------------+-----|
| *chapter 2*                                     |         |                                      |     |
|-------------------------------------------------+---------+--------------------------------------+-----|
| 2× water elemental vessel                       |      16 | elemental, water                     | N   |
| 34× Black Whale Guards                          |      12 | humanoid                             | LN  |
| 1× Prison Warden, "Lord Guirden of House Gixx"  |      19 | humanoid                             | LN  |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=257][Night Hag]] (variant)                          |      16 | fiend, hag; unique                   | NE  |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=254][Sea Hag]]                                      |      16 | hag; unique                          | CE  |
| 11× Tiderunner Aquamancers                      |      13 | humanoid, azarketi; uncommon         | N   |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=303][Mukradis]]                                     |      15 | beast                                | N   |
| 3× Lusca                                        | 16 - 18 | aberration, aquatic                  | CE  |
| 4× Clockwork Assassin                           |      13 | construct, clockwork, mindless       | N   |
| 1× Ixusoth (hyakume brainwasher)                |      15 | aberration; unique                   | NE  |
|-------------------------------------------------+---------+--------------------------------------+-----|
| *chapter 3*                                     |         |                                      |     |
|-------------------------------------------------+---------+--------------------------------------+-----|
| 1× Reginald Vancaskerkin                        |      18 | aberration, humanoid                 | NE  |
| 18-21× Clockwork Injectors ([[https://2e.aonprd.com/Monsters.aspx?ID=1004][clockwork assassin]]) | 13 - 14 | construct, clockwork, mindless       | N   |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=102][Shemhazin]] (mutilator demon)                  |      16 | fiend, demon                         | CE  |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=275][Kraken]] ("Lavialar")                          |      18 | beast, aquatic                       | NE  |
| 5× "Pulping Golem" ([[https://2e.aonprd.com/Monsters.aspx?ID=242&PWL=true][Iron Golem]] (variant))       |      14 | construct, golem, mindless           | N   |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=368][Shoggoth, "Pool of Secrets"]]                  |      19 | aberration, amphibious; rare         | CN  |
| 5× [[https://2e.aonprd.com/Monsters.aspx?ID=101][Glabrezu (treachery deamon; "lie-masters")]]   |      13 | fiend, demon                         | CE  |
| 1× Clockwork Amalgam                            |      20 | construct, clockwork, mindless; rare | N   |

** Book 6

*Summary By Type*

| *type*         | *ch 1* | *ch 2* | *ch 3* |
| *humanoid*     |      2 |        |        |
| *aberration*   |      3 |        | 1      |
| *animal/beast* |        |        |        |
| *astral*       |        |        |        |
| *celestial*    |        |      7 |        |
| *changeling*   |        |        |        |
| *construct*    |        |      6 | 1      |
| *daemon*       |        |        | 2      |
| *devil*        |        |        |        |
| *dragon*       |      1 |        |        |
| *elemental*    |        |        |        |
| *fey*          |        |        |        |
| *fiend*        |      1 |      2 | 15     |
| *hag*          |        |        |        |
| *leshy*        |        |        |        |
| *monitor*      |     10 |      6 |        |
| *plant*        |        |        |        |
| *ooze*         |        |      3 |        |
| *undead*       |        |      6 | 2      |


*By Chapter*

| *chapter 1*                            |    |                                  |    |
|----------------------------------------+----+----------------------------------+----|
| 1× Time Dragon, "Veksciralenix"        | 20 | dragon, time; unqiue             | N  |
| 5× Hegessiks                           | 15 | monitor, protean                 | CN |
| 4× Overdrive Imenteshes                | 17 | monitor, protean; rare           | CN |
| 1× Gnome, "Blune Bandersworth"         | 20 | humanoid, gnome; unique          | NE |
| 3× Blune's Illusory Toadies            | 16 | protean, incorporeal             | CN |
| 1× Nenchuuj                            | 19 | fiend, sahkil                    | NE |
| 1× Hestriviniaas                       | 22 | monitor, protean                 | CN |
| 3× Hundun Chaos Mages                  | 18 | aberration                       | CE |
| 1× Ganzi, "Il’setsya Wyrmtouched"      | 18 | ganzi, humanoid                  | CN |
|----------------------------------------+----+----------------------------------+----|
| *chapter 2*                            |    |                                  |    |
|----------------------------------------+----+----------------------------------+----|
| 1× Agent Of The Gray Queen             | 19 | fiend, daemon; rare              | NE |
| 3× Slithering Rifts                    | 18 | ooze, mindless; rare             | N  |
| 3× Camarachs                           | 17 | monitor                          | CN |
| 3× [[https://2e.aonprd.com/Monsters.aspx?ID=780][Radiant Warden]]                      | 18 | construct                        | N  |
| 1× Living Mural                        | 19 | construct; rare                  | CN |
| 5× Ghaeles Of Kharnas                  | 17 | celestial, azata; rare           | CG |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=243][Adamantine Golem]]                    | 18 | construct, golem, mindless; rare | N  |
| 2× [[https://2e.aonprd.com/Monsters.aspx?ID=282][Lich]]                                | 13 | undead; rare                     | NE |
| 4× Graveknights of Kharnas             | 17 | undead; rare                     | NE |
| 3× [[https://2e.aonprd.com/Monsters.aspx?ID=538][Maruts]]                              | 16 | monitor, aeon, inevitable        | LN |
| 1× Astral Deva, "Ulressia The Blessed" | 19 | celestial, angel; unique         | NE |
| 1× Rhevanna, "Mikiros"                 | 22 | fiend; rare                      | NE |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=544][Planetar]], "Avsheros The Betrayer"   | 23 | celestial, angel; unique         | CE |
|----------------------------------------+----+----------------------------------+----|
| *chapter 3*                            |    |                                  |    |
|----------------------------------------+----+----------------------------------+----|
| 2× Agent Of The Gray Queen             | 19 | fiend, daemon; rare              | NE |
| 1× Chaos Gulgamodh                     | 21 | construct, mindless; unique      | CN |
| 4× Shemhazians (mutilator demon)       | 17 | fiend, demon                     | CE |
| 1× [[https://2e.aonprd.com/Monsters.aspx?ID=852][Eremite]], "Xirikles"                 | 20 | fiend, velstrac                  | LE |
| 2× Excorion Paragon                    | 18 | undead; rare                     | NE |
| 1× Daemonic Skinner                    | 20 | fiend, daemon, humanoid; unique  | CE |
| 3× [[https://2e.aonprd.com/Monsters.aspx?ID=596][Purrodaemon (War Daemon)]]            | 19 | fiend, daemon                    | NE |
| 1× Daemonic Preacher                   | 22 | fiend, daemon, humanoid; unique  | NE |
| 1× Alchemical Horror                   | 21 | aberration                       | NE |
| 1× Daemonic Infector                   | 22 | daemon, humanoid; unique         | NE |
| 1× Olansa Terimor, "The Gray Queen"    | 23 | daemon, humanoid; unique         | NE |
| 3× [[https://2e.aonprd.com/Monsters.aspx?ID=91][Astradaemon (Void Daemon)]]           | 17 | fiend, daemon                    | NE |


#+BEGIN_COMMENT
| 1× Izfiitar                 | 20 | protean, monitor        | CN |
| ?× Penqual                  | 15 | fiend, sahkil, swarm    | NE |
#+END_COMMENT

* Party Makeup and Composition
  :PROPERTIES:
  :CUSTOM_ID: node/party-makeup
  :END:

[[http:cite:paizo-rzs43j2z][On the Paizo Forums, some folks discuss restricting or justifying the various archetypes.]]

[[http:cite:paizo-rzs433iw][An early thread on the Paizo forums, started by "captain yesterday", inquires about clever and punny character/party concepts for the AP, leading off strong with]]:

#+begin_quote
For me, I think my character will be a Shoony Investigator named McGruff.
#+end_quote

[[http:cite:reddit-tnqa61][On Reddit, "u/Blarg96" asks about the possibility of being a mounted character in AoE]], the general consensus that this almost-entirely-inside-the-urban-environments-of-Absalom adventure is not really the best setting for a mounted character.

[[http:cite:reddit-ty2slq]["u/Asdrodon" asks "Full [dual-class] martial edgewatch party. Is there any hope?" with good feedback.]]

[[http:cite:reddit-umsua9]["u/Alvenaharr" asks about an Intimidation build for AoE, which gathers a good few responses.]]

[[http:cite:reddit-v4x8ic]["u/DM_From_The_Bits" asks about a 5-character party to help with the difficulty of the AP.]]

[[http:cite:reddit-zgjqsq]["u/thegamesthief" asks "Is Agents of Edgewatch a good AP to convert for an urban fantasy vigilante style game?"]]

[[http:cite:reddit-xauzjp][Only tangentially related to _Agents of Edgewatch_, "u/Haos51" asks about a problematic Merchant Goblin Undead Summoner player.]]

** Alchemist

An Alchemist character who is a follower of Norgorber – even in his less-offensive "Blackfingers" aspect – might still create dramatic tension with the party, as it becomes clear early on that the Agents are on the trail of a muder cult of Norgorberites.

A plot point in Book 1 and then the end of Book 3 is the poison called "Blackfinger Blight".

A key event in Book 4 is the "Noxious Retort", a world-class Alchemical conference at the Norgorber temple in Absalom; the PCs will need to infiltrate this conference to advance the plot.

The Temple of Norgorber and its NPCs can be used to great effect to provide foreshadowing, or even just as a downtime location if the PC wants formula, reagents or poisons. Be mindful of the information the PC gives up, and the roles of the NPCs in Book 4, if you go this route.

On the other hand, "DragoldC42" points out that this does lead to lots of enemies with poison resistance…

#+BEGIN_QUOTE
([Poisoner-archetype was] Bad choice for the AP in retrospect, there are a metric ton of poison resisting enemies in this campaign)
— cite:reddit-n39df5
#+END_QUOTE

** Champion

There is a non-trivial presence of undead throughout the AP. A Champion who takes [[https://2e.aonprd.com/Feats.aspx?ID=221][Shining Oath]] will have plenty of opportunity to weave that into their play:

#+BEGIN_QUOTE
You’ve sworn an oath to put the undead to rest. Add the following tenet to your champion’s code after the other tenets: “You must end the existence of undead you encounter as long as you have a reasonable chance of success; in the unlikely event you find a good undead, you can try to work out a more peaceful way to help it recover from its undead state rather than destroying it in combat, such as helping it complete its unfinished business and find peace.”
#+END_QUOTE

As a central part of Book 5 is teaming up with the "zealborn" undead master criminal Miogimo to advance the Agent's interests, this oath can create plenty of dramatic tension to play out, as well.

[[http:cite:reddit-v8y4n0]["u/ccekim" asks about how a LG Champion can reconcile undercover police work with their tenants.]]

[[http:cite:reddit-yaxkrk]["u/Slow-Host-2449" asks more broadly about oath selection for a Champion.]] A lot of this discussion is about the enemy types encountered, so see the [[#enemy-makeup][Enemy Makeup and Composition]] section of this guide for more detail.

** Gunslinger

[[http:cite:reddit-sm87lo]["u/Hoarder-of-Knowledge" asks about the viability of Gunslingers after being initially disappointed.]]
** Investigator

[[http:cite:reddit-vae7i7]["u/Haos51" asks about their Automaton Learned Guard Prodigy Investigator in balance with the rest of their party.]]

** AP-provided Archetypes
*** Edgewatch Detective (Player's Guide, Level 2)
*** Jalmeri Heavenseeker Archetype (Book 2, Chapter 3/4, Level 7)
*** Provocator Archetype (Book 3, Chapter 3, Level 12)
* Locations and Geography
** Precipice Quarter
*** Tipsy Tengu
*** Radiant Festival
There is some confusion about the size of the Precipice Quarter in relation to the Radiant Festival grounds.

#+BEGIN_QUOTE
First of all, there's a map of the Precipice Quarter. At first I thought it
was just a small part of the district but after looking at it closely its
general shape seems to fit neatly to the full district. But later I checked
the Paizo forums and I saw someone saying that the map is supposed to
represent about 25% of the district according to some Paizo staff (there was
no specific link to the quote).
— cite:reddit-lj6pc4
#+END_QUOTE

In some readings, the map of the Radiant Festival grounds is co-extensive with the Precipice Quarter.

In the correct reading, the Radiant Festival grounds are one smaller part in the south east corner of the Precipice Quarter.

This is clarified in [[http:cite:paizo-rzs434qp-3][this comment from "Moximus" on the Paizo forums]], overlaying the festival grounds at:

- [[https://drive.google.com/file/d/1iwZR5_NkgR3LwRBghE0Uy3eNTQU9x_JC/view?usp=sharing][At the stated scale]]
- [[https://drive.google.com/file/d/1_iTjN5iFxZ_xzT7fV4d945jUVDZxH8yN/view?usp=sharing][With the festival at half the stated scale]]

[[http:cite:paizo-rzs434qp-4][While "not directly involved with the Adventure Path", James Jacobs thinks that there's a tyop in the map scale]], given Moximus images.

However, if you adopt the former position, you might be interested to see [[http:cite:paizo-rzs4349b-396][Naurgul's map of a patrol route through the Quarter]].

Along with [[narchy's maps][the rest of their excellent maps]], [[http:cite:reddit-ph7txq-hbgkw36][narchy provided a version of the festival grounds map…]]

#+BEGIN_QUOTE
I made a larger version of the festival grounds map a while ago, and I've finally gone back and finished it.

I have tried to recreate the various attractions as they are described in the books, and also included some areas with regular city buildings as they are needed for various encounters. Also, the festival grounds don't occupy the entire quarter - at least that's my interpretation!
— cite:reddit-ph7txq-hbgkw36
#+END_QUOTE

----------

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following related to the Radiant Festival]]:

- [[https://drive.google.com/file/d/15oJmhINY75JJAXJVwbRGBmCQnDugCsl6/view?usp=sharing][Street to the Hall of Nations during the Festival]]
- [[https://drive.google.com/file/d/1Z9Z7qDVs8LkqYPqbqsUfs7fiFuRtRi8f/view?usp=sharing][Closeup of the Hall of Nations]]

*** Edgewatch Station
    :PROPERTIES:
    :CUSTOM_ID: node/loc/precipice/edgewatch-station
    :END:

The nature of the Edgewatch Station is also up for some interpretation.

In some readings, supported by the text, the Edgewatch precinct station is a run-down, ramshackle affair, quickly constructed. [[http:cite:pazio-rzs434ha-2]["Moximus" relays some great imagery for their version of the precinct.]]
#+BEGIN_COMMENT
- "I always pictured the watch headquarters shoehorned into some existing, half repaired building.
  My imagining puts in the shell of what was once a grand hotel, now with half the rooms collapsed and just boarded off, and holding cells being old rooms"
- https://paizo.com/threads/rzs434ha?Community-Created-Content#3
#+END_COMMENT

In other readings -- often correlated with an Edgewatch that can afford to provide a salary to its Agents -- the Edgewatch precinct is a newly-constructed building with all the refinements.

Paizo forums users [[http:cite:paizo-rzs434ha-8][Bast L.]] and [[http:cite:paizo-rzs434ha-11][Sovaka]] have both provided maps of the Edgewatch Station.

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following of Edgewatch Station]]:

- [[https://drive.google.com/file/d/1H8S4GQe_orYLVUFN1Cq_GgcIKTrtHSOn/view?usp=sharing][Edgewatch HQ - Front Entrance]]
- [[https://drive.google.com/file/d/1l6s3zLS7oOedwMesYLdRJtGTtCArtDJq/view?usp=sharing][Expanded Entrance to Edgewatch HQ]]
- [[https://drive.google.com/file/d/1MkuDAvr0qvoFF-_ckWj36xKFhsnbHH6h/view?usp=sharing][Lavarsus and Ollo standing in front of the expanded front of Edgewatch HQ]]
- [[https://drive.google.com/file/d/1M3FzS45yduS2oiqAM7macqx1ky_qp3Cy/view?usp=sharing][Edgewatch HQ - Edgewatch Wants You poster]]
- [[https://drive.google.com/file/d/1hQfwI-vLnU5Pg-k9YZSQjsrSWyTEJTHw/view?usp=sharing][Edgewatch HQ - Edgewatch Wants You recruitment wall]]
- [[https://drive.google.com/file/d/1Q4TCD8gdgh3elVBRdOjzSXL4Yd3Q-68e/view?usp=sharing][Grospek Lavarsus]]
- [[https://drive.google.com/file/d/1rhKV-hC4fWNFirQ6l95-AudRfIZtbPRC/view?usp=sharing][Lavarsus in his office]]

*** Knight's Marvelous Menagerie

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following]]:

- [[https://drive.google.com/file/d/1yYh_elbVjiXzNFn-pWe6UYVSOsEoAqNA/view?usp=sharing][The front entrance to the Marevlous Menagerie]]

*** Dragonfly Pagoda

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following of The Dragonfly Pagoda and the threats there]]:

- [[https://drive.google.com/file/d/1HHeGWVzVs8mbrKEWgZJ3pPRwSPk6UiWp/view?usp=sharing][Dragonfly Pagoda - Courtyard]]
- [[https://drive.google.com/file/d/1mAQLstHNKhiKwWC9Gu14Zj1AF3tyKHRb/view?usp=sharing][Dragonfly Pagoda - Closeup of Rekarek and kobolds]]
- [[https://drive.google.com/file/d/1Mz87zlgGJcmWKsfns74wpHxPwUiv-XHA/view?usp=sharing][Battle Leader Rekarek]]

*** Beldrin's Tower
#+BEGIN_QUOTE
- Beldrin's tower in Precipice Quarter ends up being the place of the final
  confrontation. It should at least be mentioned earlier, implant the idea of
  visiting it for a tour while the festival is going on.
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE
*** Radiant Festival
    :PROPERTIES:
    :CUSTOM_ID: node/npc/radiant_festival
    :END:
#+BEGIN_QUOTE
- The story of how the radiant festival started gets explored in book 6. I had
  a float featuring the half-angel in the parade
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE
** Foreign Quarter
*** Irorium / Blood City Games
    :PROPERTIES:
    :CUSTOM_ID: node/npc/blood-city-games
    :END:

- Sleepless Suns

- Book 2, Chapter 3
  - Copper Hand Hideout
- Book 3
  - Irorium / Blood City Games

#+BEGIN_QUOTE
- The Irorium will be the setting of a big part of book 3. Make sure to
  mention it a few times. I had Oggrum (one of the gladiators the PCs will
  have to fight eventually) get a float in the radiant parade advertising his
  exploits.
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE
** Ascendant Court
- Godless Graycloaks
- Book 2, Chapter 4
  - The Catacombs, Skinsaw Cultists, The Skinner
- Book 4
  - Temple to Norgorber, Noxious Retrort
*** Noxious Retort / Temple of Norgorber
    :PROPERTIES:
    :CUSTOM_ID: node/npc/noxoius-retort
    :END:
#+BEGIN_QUOTE
- The Noxious Retort is an annual alchemical conference taking place at the
  Blackfingers temple. It will be showcased in book 4. Make sure your players
  learn about it beforehand if they are into alchemy or if they try to learn
  about Norgorber temples in the city.
—- cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE
** The Puddles
- The Muckruckers
- Book 2, Chapter 1
  - Smugglers
** The Docks
*** Crestwatch
    :PROPERTIES:
    :CUSTOM_ID: node/loc/crestwatch
    :END:

[[http:cite:paizo-aoe-book3][Book 3, _All or Nothing_]] describes Crestwatch as follows:

#+BEGIN_QUOTE

Crestwatch is a pinewood boathouse that was raised and converted to serve as
the Harbor Guard’s headquarters several hundred years ago. It’s situated on
the waterfront between a maze of marinas, overlooking the water from
barnacle-crusted pilings.  As the district has grown, the building has been
augmented with new upper stories for offices and expanded laterally with
temporary holding cells and entire warehouses of confiscated evidence. The
base of the boathouse has remained largely unchanged: a wide-open storeroom
with knotty floorboards and creaking staircases that ascend to the upper
halls.

— cite:aoe-paizo-book3#page=9
#+END_QUOTE

[[http:cite:paizo-lost-omens-absalom][_Absalom: City of Lost Omens_]] describes Crestwatch as follows:

#+BEGIN_QUOTE
A squat stone building with a 100-foot-high minaret marks the administrative
center of the Docks. The Harbor Guard houses its barracks and headquarters on
the east side of the building, while the Dock Council contains its meeting
chambers and offices on the west side.

— cite:paizo-lost-omens-absalom#page=126
#+END_QUOTE

The particulars of the description from Book 3 are not at all important to the
plot, and the more-recently-released details from _Absalom: City of Lost
Omens_ is probably the "more"-canonical description to use, if you care about
such things.

** The Coins
- Token Guard
- Book 2, Chapters 1-2
  - Bank leads, Bank Robbery
*** Lucky Nimbus Casino
    :PROPERTIES:
    :CUSTOM_ID: node/npc/lucky-nimbus
    :END:
#+BEGIN_QUOTE
- The Lucky Nimbus casino will play a role in book 3. Make sure to mention it
  exists. I had an elaborate float advertising it in the radiant parade.
#+END_QUOTE
— cite:reddit-ocdrxm-h3uh21r
** Eastgate
*** House of the Planes
    :PROPERTIES:
    :CUSTOM_ID: node/npc/house-of-the-planes
    :END:

In [[#node/plot/b1c2][Book 1 Chapter 2]], the Agents will come to [[#node/npc/hoff][Jeremin Hoff's]] speakeasy to follow clues.

In [[#node/plot/b5c1][Book 5 Chapter 1]], the Agents will return to this neutral ground to participate in a negotiation among various gangs.

Book 1 has flavor of the various rooms, but Book 5 has the map. :)

#+BEGIN_QUOTE
- House of Planes will be revisited in one of the later books. So it should
  probably be mentioned a few times. In book 2 I had my PCs track down one of
  the smugglers there after a botched attempt to raid their base of
  operations.
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE

** Kortos Bay
*** The Black Whale
    :PROPERTIES:
    :CUSTOM_ID: node/npc/black-whale
    :END:
#+BEGIN_QUOTE
- The Black Whale is a prison for important political prisoners that is
  visited in book 5. Give it a brief mention maybe at some point when
  appropriate.
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE
** Starwatch, Starwatch Keep
#+BEGIN_QUOTE
- Starwatch will eventually (in book 3) adopt the PCs and Starwatch Keep is
  where they'll get some offices of their own. Have them visit it early on if
  they want or make sure they've heard it at least. Same goes for Fort
  Tempest, make sure they've heard it exists.
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE
* NPCs

There are dozens more NPCs throughout _Agents of Edgewatch_. The following are
called out for being a bit more notable than the rest, either because of
multiple intersections with the plot, or notable details about how to run them
as the GM.

** Primary / Major
*** Jonis Flakfatter — "The Infector" / "Father Infector" (NE male human high priest 15)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/flakfatter
    :END:
*** Olansa Terimor — "The Gray Queen" (NE female human city planner, master thief 20)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/terimor
    :END:

Olansa Terimor is the ultimate enemy of the Adventure Path. As written the AP only brings her up very incidentally in the first three books, and then has them speak to the Agents in passing at the beginning for Book Four.

On the Paizo Forums, [[http:cite:paizo-rzs43hfo][user "OmegaZ" details how they planned to change Terimor to be a more reasonable final boss for the Adventure Path.]]

*** Reginald Vancaskerkin — "The Rumormonger" (NE male human entrepreneur 18)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/vancaskerkin
    :END:

#+BEGIN_QUOTE
- Vancaskerkin ends up being one of the main antagonists. Make Vancaskerkin
  prominent, especially through his tabloid Eyes on Absalom. Don't forget to
  tell the PCs about the frontpages of the paper (especially the ones that
  they are featured on), invite them for interviews, make them trust him as a
  partner they can go to ask for help. My players certainly have. For book 2
  Vancaskerkin will show up and warn the PCs about Pratchett trying to publish
  his memoirs from prison to create a favourable impression to the public
  before his upcoming trial.
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE

----------

[[http:cite:paizo-rzs4349d-12]["Lord Shark" notes that "The Rumormonger" is a /bit/ too obvious of a name for Vancaskerkin]].
   [[http:cite:paizo-rzs4349d-14][GayBirdGM shares that that is precisely why they changed it to "The Reaper" for their game]],
    [[http:cite:paizo-rzs4349d-82]["EdwinM" went with "The Whisperer"]],
    and [[http:cite:paizo-rzs4349d-97]["The ShadowShackleton" went with "The Preacher"]].
    [[http:cite:paizo-rzs4349d-79]["AlastarOG" thinks y'all're overestimating your players. ;)]]

--------------------------------------------------

[[http:cite:reddit-sxyxm8]["u/higoram" posts some OC art of Reginald Vancaskerkin.]]

----------

([[http:cite:paizo-rzs4349b-268][If the name "Vancaskerkin" is familiar to you, there's good reason: it's a bit of a running gag/easter egg in Paizo's APs.]])

*** Wrent Dicaspiron — "The Skinner" (CE female human cult leader 10)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/dicaspiron
    :END:
*** Lieutenant Grospek Lavarsus, of Edgewatch (LN male human city guard commander 7)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/lavarsus
    :END:
#+BEGIN_QUOTE
- Lavarsus ends up getting manipulated by the antagonists and arresting the
  wrong person. Play up Lavarsus as full of pride and incompetent
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE

-----

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following of Edgewatch Station]]:

- [[https://drive.google.com/file/d/1Q4TCD8gdgh3elVBRdOjzSXL4Yd3Q-68e/view?usp=sharing][Grospek Lavarsus]]
- [[https://drive.google.com/file/d/1rhKV-hC4fWNFirQ6l95-AudRfIZtbPRC/view?usp=sharing][Lavarsus in his office]]
- [[https://drive.google.com/file/d/1MkuDAvr0qvoFF-_ckWj36xKFhsnbHH6h/view?usp=sharing][Lavarsus and Ollo standing in front of the expanded front of Edgewatch HQ]]
*** Captain Asilia of Gyr, of Starwatch (N female human ranger 12)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/asilia
    :END:

#+BEGIN_QUOTE
A stern-looking human woman with a shock of white hair and an impressive
tricorn sits behind a broad, imposing desk.  She stands and introduces herself
as Captain Asilia of Gyr (N female human ranger 12), leader of Starwatch and
commander of the warship Hurricane Wings, and gestures for the agents to sit
down, gesturing to the room’s comfortable chairs.
— cite:paizo-aoe-book3#page=6
#+END_QUOTE

#+BEGIN_COMMENT

- Captain of Starwatch
- Will be "commanding officer" in Book 3, 4?
  - Book 3 page 6: picture, narrative introduction
- Nautical dress

#+END_COMMENT
*** Captain Shristi Melipdra, of the Sleepless Suns (LG male human guard captain 7)
*** Wynsal Starborn (LG male human acting primarch of Abasalom 17)
** Secondary / Minor
*** Ama Uomi (LN female human architect 3)

Introduced in Book 1 Chapter 2, Ama returns briefly in Book 6 Chapter 1 to help the Agents if they were kind to her in Book 1.
*** Blune Bandersworth (NE male gnome architect, ex-thief, and illusionist 20)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/bandersworth
    :END:
*** Hendrid Pratchett (CE male half-elf serial killer 6)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/pratchett
    :END:

While Pratchett is the BBEG of Book 1, they are fundamentally disconnected from the events in the AP, and as such are only a minor NPC.


#+BEGIN_QUOTE
I have to say, Hendrid Pratchett is one of the scariest and abhorrent monsters
I've ever seen for Pathfinder. Facing this guy is worse than facing a
Shoggoth, at least you expect the eldritch horror to come if facing one of
them or know that they're around.

This guy is an act to follow for Chaotic Evil Villians, he's a charismatic
manipulator to where he's easily so trustworthy to any person that would
interact with him, yet so demented that the more you begin to peel away at his
alibi and hotel, the darker tones start to kick in and break away at you
mentally with each of his heinous crimes.

His form of revenge on getting hit with a mug is peeling away the skins of the
four adventurers or mentally torturing two people to kill each other and make
fake escape attempts that end up in vain, only for them to become scarred that
they can't even trust the help that comes to save them. The fact that he keeps
Ralso tied psychologically by having two dolls to act as her replacement
sisters and his other demented works of art. And let's not forget the two
ghosts he keeps as children to see him as a father figure.

James, congratulations. I am literally scared of this guy.

— cite:paizo-rzs4349b-41
#+END_QUOTE
*** Sergeant Moldun Ollo (LG male dwarf senior officer 8)

In contrast to the blowhard Captain Lavarsus, Sgt. Ollo keeps Edgewatch Headquarters running, and is likely to be a friend and ally to the Agents.

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following]]:

- [[https://drive.google.com/file/d/1xPfFiwdWQv1pnqlY8udvDiGZ_qSc9ULe/view?usp=sharing][Sergeant Moldun Ollo, Solo]]
- [[https://drive.google.com/file/d/1MkuDAvr0qvoFF-_ckWj36xKFhsnbHH6h/view?usp=sharing][Lavarsus and Ollo standing in front of Edgewatch HQ]]
*** Detective Desdelen "Skinny" Bolera (NG female half-elf investigator 6)

Introduced in Book 1, the GM is encouraged to use Bolera at a few points throughout the AP, but is never more than a minor NPC.

The AP-specific "Edgewatch Detective" Archetype has a Feat named after Bolera: [[https://2e.aonprd.com/Feats.aspx?ID=2196][/Bolera's Interrogation/]].

*** Corporal Kerr Batiste (NE female human officer 8)

Presented in Book 1, Corporal Batiste is described as corrupt, which presents the NPC as either a foil or resource to the agents later in the AP.

*** Cass Hamish, of the Garrote Sisterhood (N female human assassin 16)

Cass Hamish is one of the notable npcs in the House of the Planes in [[#node/plot/b1c3][Book 1, Chapter 3]], and can come back again in her professional capacity in [[#node/plot/b5c1][Book 5, Chapter 1]].

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders]], including the following of [[https://drive.google.com/file/d/1XkJ9EZ7Xi9Uq4ABO0rA37X4kbU8QGvZq/view][Cass Hamish]] of the Garrote Sisterhood.

*** Ziraya Al-Shurati, of the Muckruckers (LN female human investigator 7)
*** Captain Runewulf "The Unbeliever", of the Godless Graycloaks (N male human barbarian 13)

#+BEGIN_QUOTE
"as he is more colloquially known, Runewulf the Unbeliever."
— cite:paizo-aoe-book2#page=28
#+END_QUOTE
*** Kekker and Gref (LE male ratfolk smugglers 2)

Encountered as smugglers in the undercity in [[The Back Door][Book 1 Chapter 3]], Kekker and Gref can come up again in [[#node/plot/b4c1][the alchemical conference "The Noxious Retort" in Book 4 Chapter 1]].
*** Gage Carlyle (N male human casino owner 11)

- Book 3, Chapter 2
- Owner and proprietor of the Lucky Nimbus Casino
*** Maurissa Jonne (N female human ex-brawler / gang leader 10)
*** Franca Laurentz (CN female elf bio-terrorist 13)
*** Lord Ganfen of House Kethlin (N male human administrator 12)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/lord-ganfen
    :END:
*** Jeremin Hoff (LE male human power broker 13)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/hoff
    :END:

Introduced in [[#node/plot/b1c3][Book 1 Chapter 3]], Hoff will come back up in [[#node/plot/b5c1][Book 5 Chapter 1]], but is generally not a plot-critical character.
*** Ralso (NE female half-orc thief 4)
*** Harlo Doleen (?? male human adjutant to Wynsal Starborn ??)
    :PROPERTIES:
    :CUSTOM_ID: node/npc/doleen
    :END:

#+BEGIN_QUOTE
- Harlo Doleen ends up getting murdered which is a major plot point and
  twist. I made him be an acquaintance to one of the PCs. The PC used to be a
  slave and Harlo used to be his master. They have an awkward relationship now
  after not seeing each other for more than 3 years.
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE
*** Kayln Pounch (NE female human priest of Blackfingers 12)
*** Miogimo (CE male zealborn criminal mastermind 17)
*** Il'Setsya Wyrmtouched (CN female ganzi arcanist 18)
*** Festival Committee / Grand Council

#+BEGIN_QUOTE
- Some members of the festival committee and the grand council will end up
  playing major roles in the final books. So they should be introduced and
  interacted with early. I had my PCs give a brief 5 minute presentation in
  front of the radiant festival committee at the palace in Wise Quarter about
  their discovery of a potential bank heist plot.
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE

Specifically the following notable NPCs are members of the Festival Committee and/or Grand Council:

- [[#node/npc/lord-ganfen][Lord Ganfen of House Kethlin, master of blades of the Irorium]]
- [[#node/npc/terimor][Olansa Terimor, City Planner]]
- [[#node/npc/bandersworth][Blune Bandersworth, City Architect]]
*** Godless Graycloaks

It's not quite stated strongly enough in the Player's Guide that the Godless Graycloaks are explicitly and strictly atheist.
* Plot
  :PROPERTIES:
  :CUSTOM_ID: node/plot
  :END:
** General

- Though limited by being created before the final two books were published, on the Paizo forums, [[http:cite:paizo-rzs4388l]["IcedMilk" outlines some of the larger plot threads that might warrant foreshadowing.]]

- [[http:cite:reddit-ug36in][On reddit, in thread titled "Advice on starting", "u/ognir-rrats" asks for advice for folks starting the AP. This is a mix of general Pathfinder 2E tips, plus a bit of detail on the encounters in the first few chapters, and the AP overall.]]

- [[http:cite:reddit-s7rs9j]["u/Laz_r_us91" asks about jumping into Book 2 at 5th Level.]]
  [[http:cite:reddit-wbcrsm]["u/DramFan" asks about how/where/when to integrate a party at 5th level into the AP.]]

- [[http:cite:reddit-sei87z]["u/Meamsosmart" recounts some details of completing the entire AP as a character.]]

- [[http:cite:reddit-z9l84c]["u/Excaliburrover" – a name appearing throughout this guide's citations – posts "GM finished Agents of Edgewatch AMA" on Reddit.]]

** Book 1: "The Devil in the Dreaming Palace"
   :PROPERTIES:
   :CUSTOM_ID: node/plot/book1
   :END:
*** Title … spoilers, Paizo!

Just the name of this book is a spoiler combined with the fact that the Party meets Pratchett, who identifies himself as the owner of The Dreaming Palace in literally the first encounter the PCs have in the game. :(  Even Players who are not /trying/ to spoil themselves might come across the book name on the internet, including AoN.

Since you can't change the book name, there are a couple of options:

1. Rename the "Dreaming Palace" hotel. The name is not particularly important … feel free to change it.
2. Skip the Pratchett+Ralso encounter in the Tipsy Tengu entirely (see [FIXME] link to below).
*** Book 1, Chapter 1: "The Mean Streets of Absalom"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b1c1
    :END:
**** Noise Complaint / Tipsy Tengu

As mentioned earlier, the title of the book matches the name of the hotel that the primary atagonist tells the party in their very first encounter.

It's a strange decision the AP authors made, here.

Changing the name of the "Dreaming Palace" will preserve the suspense throughout the book, and is recommended.

Also, just skip the encounter with Pratchett and Ralso in the Tipsy Tengu entirely.

The encounter serves two purposes:

1. Foreshadow Pratchett. There is no particular need to do so, and this extremely brief encounter doesn't particular serve to do so well in any case.

  [[http:cite:reddit-n39df5][u/DragoldC42 concurs...]]
  #+BEGIN_QUOTE
  The chance encounter with the book villain in the very start is a bit too
  obviously foreshadowing- seeing the owner of the dreaming palace in an
  adventure named this way does not give much room to doubt. I found it not
  really disrupting, as the players could make some disconnect, but for another
  GM I would advise to just change the name of Pratchett's hotel.
  — cite:reddit-n39df5
  #+END_QUOTE

2. Provide a reason why the skins of the drunk adventurers are flayed and hanging in Pratchett's trophy room (they broke his nose). Pratchett has plenty of motivation to kill anyone he wants (he's a sadistic serial-killer dick-hole), so there's no need to /motivate/ this.


----------

[[http:cite:paizo-rzs4349b-246][Smoagendash II describes some interesting variations they made in this first book.]]

----------

Posting on Reddit, [[http:cite:reddit-r8zm44][u/Kraydez provides a link to their remake of the Tipsy Tengu map, in DungeonDraft]].
**** Missing Persons

[[#node/resources/missing-person-casefiles][See the "Resources / Missing Person Casefiles" section for resources relating to this element of Book 1.]]

**** "Panic at the Zoo" / Knight's Marvelous Menagerie

The Menagerie encounter has a bit of a reputation for being rough.

You have some options.

#+BEGIN_QUOTE
- the deadly zoo encounter- which includes two different monsters with the ability to petrify the party as well as a buffed rust monster, against which the party has to pace without a real chance to take 10 minutes of rest- is too much for most level 1 parties, including mine.

I gave my players the option to just tie up the monsters with rope after a successful grapple check, and this gave a much easier win condition to the combats while still being hard enough considering they had to go all over the zoo with no rests.
— cite:reddit-n39df5
#+END_QUOTE

Responding to a [[http:cite:paizo-rzs4349b-230][concern from "Johnico" that the Rusty fight is "crazy"]], [[http:cite:paizo-rzs4349b-231][Deadmanwalking notes that rust monsters are generally offensively weak, so if actions are used correctly, it should balance out okay.]]

[[http:cite:reddit-t1mxvf][u/darkboomel asks about how reasonable it is to nerf Book 1, Chapter 1 enemies]], then follows up a couple of weeks later,
[[http:cite:reddit-t5ebpi][describing how they re-tooled this part of the AP]].

**** Blackfinger Blight
     :PROPERTIES:
     :CUSTOM_ID: node/npc/blackfinger-blight
     :END:

Blackfinger Blight is introduced in Book 1 Chapter 1 as the cause for the behavior of the animals in the Menagerie.

#+BEGIN_QUOTE
The zoo creatures themselves are acting unusually aggressive, with a
starting attitude of hostile. This is the result of a rage-inducing
serum called blackfinger blight. An agent of Jonis Flakfatter, one of
the city’s high priests of Norgorber (and an important antagonist later
in this campaign), tested his latest formulation by introducing the
contagion into the animals’ water supply.
— cite:paizo-aoe-book1&page=13
#+END_QUOTE

It doesn't show up again until it plays a part in the climax of Book 3.

If your part contains an Alchemist, you might want to insert some detail for them to learn.

----------

[[http:cite:paizo-rzs4349d-28][AlastarOG finds the Blackfinger Blight effects too "basic" and misaligned with the narrative, so they revised its effects]].
#+BEGIN_COMMENT uncleared quote paizo-rzs4349d-28
Another idea for this ark, I don't like the blackfinger blight effects, seems way too ''basic'' as far as evil plots go. I liked the idea that it was a poison that made everyone mad and attack everyone around
them like it was foreshadowed in chapter 1. For this reason, I'm thinking of switching its effects to this:

Saving Throw DC 32 Fortitude; Onset 1 round; Maximum Duration 6 rounds; Stage 1 confused 1 round (1 round); Stage 2 confused 1 round, gain a +1 status bonus to attack and damage, -1 status to AC (1 round); Stage 3: Permanently confused until poison is countered.

I'm hoping to have this be a bit like the crowd murder moment in kingsmen, this should be a bit more poignant I'd say, and also make the fight a bit more interesting, as they could very much wail on each other.
— cite:paizo-rzs4349d-28
#+END_COMMENT

#+BEGIN_COMMENT
- Introduced in Book 1, Chapter 1
- Plays a key role in Book 3 Chapter 3
- Doesn't really show up between.

If your party has an Alchemist or Investigator, they might get curious to follow up on this clue…

- index
  - Book 1, pg 13:
    - "The zoo creatures themselves are acting unusually aggressive, with a
      starting attitude of hostile. This is the result of a rage-inducing
      serum called blackfinger blight. An agent of Jonis Flakfatter, one of
      the city’s high priests of Norgorber (and an important antagonist later
      in this campaign), tested his latest formulation by introducing the
      contagion into the animals’ water supply. An agent who succeeds at a DC
      15 Nature check realizes that this sudden hostility seems abnormal, as
      does the black froth around some of the creatures’ mouths, yet the
      Edgewatch agents aren’t intended to discover much about the contagion
      itself at this time. Rather, this is foreshadowing for the much larger
      role blackfinger blight will play later on in the Adventure Path, (see
      the campaign summary on page 76).

      The poison’s current formulation has a short half-life.  If knocked
      unconscious or restrained, creatures affected by the virus recover in a
      day or two.  None of the escaped creatures are currently capable of
      spreading the blight.

  - Book 3, pg 5: Heading, "The Blackfinger Blight Bomb"

#+END_COMMENT
**** The Graveraker goes missing

The AP makes a point of the Graveraker going missing at this point.

It is extremely easy for a/ you to miss this point here in the text and b/ for the party to not notice the detail; it's another piece of foreshadowing that can get a bit lost.

The Graveraker does not come up again until Book 4, but is an important plot point much later in the AP; the party will have a critical encounter within its strange extra-dimensional interior!

Many folks recommend making more of a point of it.

#+BEGIN_QUOTE
- The Graveraker becomes an important plot point in the 4th and 6th books, Yet after it disappears somewhere in the start of this book, no mention of it exists in the AP for three whole books- at least not in a way major enough to remind the players it exists. My group totally forgot about it by the point the twists happened. I would advice all GMs running the AP to find ways to bring the Graveraker up a few times. Also, no art of the Graveraker exists in the AP at all. I would have really liked to see what it is like!
— cite:reddit-n39df5
#+END_QUOTE

[[http:cite:paizo-rzs4349b-446][OmegaZ planned to stage an event to make its disappearance conspicuous to all.]]

[[http:cite:paizo-rzs4349b-447][GreatGraySkwid disagrees a bit, and has some good perspective about the Gravewalker going missing…]]
#+BEGIN_QUOTE
The whole point of Graveraker's disappearance happening off camera is so that
the actually qualified Agents of Edgewatch (i.e., not "our" party) can be
dedicated to tracking down an established and well-known exhibit of the
Festival, leaving our teams of rookie misfits to investigate a batch of people
who may or may not actually be missing.  If you emphasize it happening in
front of your team, it's goes from being a Chekov's gun to a massive red
herring, as you get them all riled up wanting to pursue a mystery there are no
leads for them to follow and no way you can allow them to solve until several
books later.  — cite:paizo-rzs4349b-447
#+END_QUOTE

#+BEGIN_QUOTE
- The Graveraker will show up again in book 4. Show Bolera working on the
  Graveraker case. In my game, she's slowly uncovering some clues like
  mentioning that she thinks it was no coincidence that the zoo attack and the
  Graveraker theft happened at the same time, interviewing the inventor and
  making some vague references about a missing power source and the
  involvement of the radiant festival committee
— cite:reddit-ocdrxm-h3uh21r
#+END_QUOTE

**** XP

[[http:cite:paizo-rzs4349b-237][Kasoh tots up all the Chapter 1 XP so you don't have to! :)]]

*** Book 1, Chapter 2: "Missing Persons" / The Dragonfly Pagoda
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b1c2
    :END:

*Unofficial Errata* The encounters in Chapter 2 are spec'ed for a level 2 party, so level the party to level 2, no matter what the guide at the front of the book says.

[[http:cite:paizo-rzs4349b-129][Bast L. notes that if the Agents try to do the right thing and negotiate with Doopa, as-written, they're then thrown into a beyond-extreme encounter.]] Downthread, [[http:cite:paizo-rzs4349b-193][LarsC has an idea.]]

[[http:cite:reddit-shkce0]["u/DankYeehaw" asks for "Help GMing Agents if Edgewatch Book 1 Chapter 2", specifically with re-flavoring the murderous kobold union members and the police tasked to go beat them up. Fair.]]

*** Book 1, Chapter 3: "Into the Undercity" / House of the Planes
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b1c3
    :END:
**** The Back Door

[[http:cite:paizo-rzs4349b-404][As "GreatGraySkwid" notes, there's no reason the Agents should arrest the ratfolk Kekker and Gref in the "Back Door" to the House of Planes, in Book 2.]]

[[http:cite:paizo-rzs4349b-408][Also, "GreatGraySkwid" notes that the ratfolk Kekker and Gref share no common language with their Caligni trading partners.]]

The drug [[https://2e.aonprd.com/Equipment.aspx?ID=807]["grolna"]] referenced in Chapter 3 is not at all significant to the plot of the AP.

**** The House of the Planes

This section is intended to provide leads to Ralso and Pratchett, and to tie the missing stone masons to Ralso.

As written, it is extremely heavy-handed. Literally every NPC knows something absurdly relevant about Pratchett or Ralso.

In terms of priority, the following things "must" happen here:

- The party should meet Reginald Vancaskerkin, and ideally they should /like/ him.

  #+BEGIN_QUOTE
  - Reginald Vancaskerkin is described in the book as someone who is "oily, nosy, and of questionable moral fiber", while the later books seem to think he has become a fan and friend of the party, at least until he backstabs them. I would advice playing him as someone who your players would like, and not a walking red flag as my reading of the first book alone implied to me.
  — cite:reddit-n39df5
  #+END_QUOTE

- The party should find out that Ralso fenced some Minkainan stone mason tools, and she works at the Dreaming Palace.

- [Read The Alexandrian and invent two more clues, in case they don't find that one.]

Everything else is gravy.

- While Hoff will come back up later in the AP (Book 5), Hoff is not a plot-critical character.

- Book 5 does have a map of the House of the Planes, and I'll recommend using it. The location is interesting, even if this is just a social encounter.

----------

[[http:cite:paizo-rzs4349b-428]["MathNerdGord" provides an alternate puzzle – a "reskinned knights/knaves type puzzle" – for this section if you think your party will find the one in the book not challenging enough]]; others follow up with their puzzle variants.

[[http:cite:reddit-wb98m4]["u/queengodiva" asks for some help on how to run the House of the Planes NPC/infodump,]] with some good options and feedback presented.

*** Book 1, Chapter 4: "The Murder Hotel" / The Dreaming Palace
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b1c4
    :END:
**** Content Warning

This dungeon is no joke, either difficulty-wise or thematically … especially thematically.

You should make sure your Players are comfortable with the content here. *It's more important to make sure of that than to prevent spoiling things.*

Some people are going to have serious problems with – for example – mutated, deformed fetuses kept alive in jars! Some people might have real-life bad experiences with voyeurism or being spied on!

It is of course okay if they do, and it's your job to only challenge them as much as they are comfortable being challenged.

Be kind.

**** The Dreaming Palace

[[http:cite:reddit-p887ao][At least two groups have independently tamed the mimic into becoming a party "pet" or acquaintance. :)]]

[[http:cite:reddit-ojp6to][u/Excaliburrover has some concerns with the pacing/leveling in the Dreaming Palace]], specifically with the hazards that can deliver PCs — basically – directly to the boss 1 level early.

#+BEGIN_QUOTE
My issue is with the fact that the players are supposed to get from lvl 3 to lvl 4 mid dungeon but there are 2 occasions in which they might skip right trough. It would be climactic for sure to meet the final boss right away but it would spell the end of them as well
— cite:reddit-ojp6to
#+END_QUOTE

[[http:cite:reddit-ojp6to-h5354t4][u/Naurgul has some good advice if players get too close to Pratchett too soon…]]

#+BEGIN_QUOTE
- First of all, the PCs aren't that likely to fall into the pit traps, especially the second one leading directly to the chamber next to Pratchett. After falling into one or two traps they will probably stop barging into the rooms haphazardly.

- Second, they can always run away upstairs. Just make sure to use descriptions to give them subtle hints that Pratchett lies behind that final door.
— cite:reddit-ojp6to-h5354t4
#+END_QUOTE

[[http:cite:reddit-yj8pyy]["u/kenvalbrandur" has a question about Pratchett's office layout.]]


[[http:cite:reddit-w6ajgj]["u/UnfortunateHyrbrid" asks for some Dreaming Palace help, and receives it in spades.]]


[[http:cite:reddit-z8xods]["u/murshawursha" asks if the whole AP is as hard as Book 1 and The Dreaming Palace in particular.]]

-----

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following related to the Dreaming Palace]]:

- [[https://drive.google.com/file/d/1HQ5YNd77Mf54IkWEPU7FD7QAoPbRQRwI/view?usp=sharing][Hendrid Pratchett]]
- [[https://drive.google.com/file/d/1OAfOFKJ2BmHJxbEudGRdUPP7e2G6vAX9/view?usp=sharing][Ralso]]
- [[https://drive.google.com/file/d/1occvguuijG75hke_3hiBStQVmDoT0DhT/view?usp=sharing][Ralso in the Dreaming Palace lobby]]
- [[https://drive.google.com/file/d/1-siPIlAOLL2lPPHF0bjA0IeLFlGFeEep/view?usp=sharing][Pratchett's Dungeon – Pratchett only]]
- [[https://drive.google.com/file/d/14Mc0NQwrxe-LfY3DGHDwnZH-6-CfCThj/view?usp=sharing][Pratchett's Dungon – Pratchett and the Binumir]]

----------

On the Paizo forums, [[http:cite:paizo-rzs43cn4][user Kneymo describes how they went radically off-script, and converted the entirety of The Dreaming Palace towards a different theme.]]

**** Hendrid Pratchett encounter

Experiences with this encounter vary, but it is a Severe 4 encounter, and based on the time and physical constraints of this dungeon crawl, the party will likely be encountering Pratchett with below-full health and limited resources (consumables, spells) remaining.

On reddit, [[https://www.reddit.com/r/Pathfinder2e/comments/otxspj/final_fight_of_the_first_book_of_agents_of/h70146j/?utm_source=reddit&utm_medium=web2x&context=3][u/SanityIsOptional suggests a varied action spend from Pratchett to help smooth the encounter for the PCs]]:
#+BEGIN_QUOTE
From my experience running him: Make sure he's spending actions to move
around and using intimidate on the players. Essentially eat up his actions
on thematic and interesting things that aren't attacks. Especially if they
end up harassing the players or making the characters angry at him. He
shouldn't be taking the party seriously, and should be trying to taunt them
at least in the start of the fight.
— cite:reddit-otxspj-h70146j
#+END_QUOTE

This goes both ways, too. As in PF2 generally: the party using actions to force /enemies/ to spend actions is of good utility.

[[http:cite:reddit-otxspj-h71hhre][u/mads838 agrees]]:
#+BEGIN_QUOTE
The group i played in managed it. But it was tough as All hell. Try to convince you players to start using stuff like grapple, trip or disarm. Actions wasted because of those are actions he isnt using to kill the players.
— cite:reddit-otxspj-h71hhre
#+END_QUOTE

--------------------------------------------------

The Binumir are also a challenge.
[[http:cite:reddit-otxspj-h7jg3rc][As u/narchy notes]]:
#+BEGIN_QUOTE
The ghost twins scream is a REALLY nasty one. The fighter and champion in our group failed the save, which means no AoO or Retributive Strike.
— cite:reddit-otxspj-h7jg3rc
#+END_QUOTE

[[http:cite:reddit-otxspj-h6yiyr8][u/Naurgul has some advice]]:
#+BEGIN_QUOTE
The fight gets much easier if the PCs take out the children twin ghosts he has with him with RP instead of fighting. If they are reminded of their former lives they don't attack. So maybe give them a few extra hints about that. For example if they try to recall knowledge on them ask if they use society or religion; a successful society check should be enough to remind them of the twins they read about in their missing persons reports.
— cite:reddit-otxspj-h6yiyr8
#+END_QUOTE

And [[http:cite:reddit-larstr0n-otxspj-h6ygq77][u/larstr0n (GM, Tabletop Gold podcast) recommends using the Binumir the scale the combat on the fly]]:
#+BEGIN_QUOTE
If you're concerned about Pratchett, there’s a lot of room to run his ghost twins suboptimally and use them to ratchet the tension up and down depending on what level of peril you’re looking for.
— cite:reddit-larstr0n-otxspj-h6ygq77
#+END_QUOTE

Stepping back a bit, [[https://www.reddit.com/r/Pathfinder2e/comments/otxspj/final_fight_of_the_first_book_of_agents_of/h6zoyve/?utm_source=reddit&utm_medium=web2x&context=3][u/Unconfidence finds this encounter "exemplary of the stuff I don't like about Paizo's APs."]]:
#+BEGIN_QUOTE
This combat made me think that either the people who made this system really
didn't understand the way poison interacts with death & dying, or that I am
missing something about it. Because like, going to the ground with
persistent damage, that's death. And we certainly had three of our six party
members at high levels of Wounded.

It's extremely dicey and pretty exemplary of the stuff I don't like about
Paizo's APs. The entire "difficulty" seems to be in high numbers and a
serious risk of a few bad rolls dooming a character or a party, despite any
of their best choices. I would seriously suggest any DM running this
consider putting Alchemical Antidotes or something of the sort somewhere in
the Inn, or I dunno, something.
— cite:reddit-otxspj-h6zoyve
#+END_QUOTE

[On Rebalancing]

[[http:cite:reddit-otxspj-h6z514n][u/SighJayAtWork describes]]:
#+BEGIN_QUOTE
I had six PCs so I added an extra "body" to the Binumir (like an eatin, I gave them both two actions) and a few Zrukbats to the encounter, just to give them some more bodies to deal with
— cite:reddit-otxspj-h6z514n
#+END_QUOTE

[[http:cite:reddit-zfzfro]["u/memnoch_87" asks how the party is supposed to handle Pratchett.]]

**** Pratchett Escape/Chase
[[http:cite:paizo-rzs4349b-441][Naurgul has some guidance on how to handle Pratchett's attempted escape using the GMG's Chase Subsystem…]]
#+BEGIN_QUOTE
Here's some potential obstacles for this chase scene along with some example checks that the characters could use to bypass them:

- secret door closes behind him (acrobatics to jump in before it closes, athletics to hold it open, thievery to re-open)
- flaming mass (acrobatics to jump through, athletics make a path, or they can just walk through it and take some damage)
- Pratchett throws down the shelves with the jars in E31 (Athletics to throw them out of the way, Acrobatics to squeeze through the gaps, maybe some spell)
- leftover monsters attack (acrobatics to tumble through, Athletics to shove away, recall knowledge or deception to distract them)
— cite:paizo-rzs4349b-441
#+END_QUOTE

** Book 2: "Sixty Feet Under"
   :PROPERTIES:
   :CUSTOM_ID: node/plot/book2
   :END:
*** Book 2, Chapter 1: "The Unusual Suspects" / Bank Robbery Investigation
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b2c1
    :END:

While ultimately pretty linear, this chapter has a bit of an open-world / sandbox feel, putting choice into the party's hands.

#+BEGIN_QUOTE
is a very strong point in this book- a less structured investigation sequence gave an almost "open world" feeling while playing, with the party able to choose the pace and theorize on where the robbery will take place. Running this section was a lot of fun for me!
— cite:reddit-n39df5
#+END_QUOTE

[[http:cite:paizo-rzs4349c-91][Naurgul used this as an opportunity to substantially re-work the chapter, tying their PC's backstories into the plot.]]

#+HTML: <details>
#+HTML: <summary>Instead of being given all the leads they are at the beginning of this book […]</summary>
#+BEGIN_QUOTE
Instead of being given all the leads they are at the beginning of this book, they instead only learn from Ralso that there's a group of thieves called the Copper Hand who are definitely planning to rob a bank using the radiant parade as a cover. From there I'm expecting the players come up with the following lines of investigation more or less on their own:

- *Get the route of the parade and compare it with the addresses of known banks:* This will yield them a number of banks that are possible targets. I'm planning to include the 3 possible targets mentioned in the original but I'm also adding "Chadraxa's cheap loans" and "Vault of Abadar" as banks that the parade will pass by, maybe even some more.
- *Investigate the possible targets:* This should be largely the same as the original except I'm gonna make a point of emphasising how big the Penny & Sphinx garden lawn is and how far away the main bank building is from the road.
- *Figure out where security is weakest:* That should yield the information that the Token Guard is the most easily corruptible and unscrupulous district guard. (And that the Vault of Abadar is extremely well-guarded and unlikely to be the target)
- *Investigate the float makers:* Some gathering of information in the Ivy District (where one of my PCs hails from) will yield the information that is available at the tannery in the original story, i.e. an apparatus has been stolen that was used in a play to make it look like Aroden was raising the Starstone out of the ocean.
- *Ask the other district watches if they've heard of the Copper Hand:* That should yield an answer from the Stilt House. This is similar to the original story, except after they get the ledger at the smugglers' lair, they will not learn the exact location of the heist... but I'm not sure exactly what they should learn, probably something about what kind of supplies the thieves have purchased from the smugglers, e.g. sails and caltrops and stuff.

The final clue is the new PC joining the ranks. […]
— cite:paizo-rzs4349c-91
#+END_QUOTE
#+HTML: </details>

--------------------------------------------------

In response to a question about how to recover if Droan burns the incriminating secret journal, [[http:cite:paizo-rzs4349c-129][Naurgul outlines multiple ways to do so]].

----------

At this point, some people notice that not all the toolbox items are actually included in the pre-written adventure path, such as the [[https://2e.aonprd.com/Equipment.aspx?ID=814][Ethersight ring]]. [[http:cite:paizo-rzs4349c-147][Michael Sayre suggests having Rohka Stoneswarn give it to the PCs to help with her ether spider problem.]]

-----

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following related to the smuggling ring encounter]]:

- [[https://drive.google.com/file/d/1YKvydvFquPp92Ql5kwrUQc83rjO7uyCv/view?usp=sharing][Percen Droan]]
- [[https://drive.google.com/file/d/1XfsDqggrtuojkzoN8mk9ZQm3ExHPJ4j_/view?usp=sharing][Confronting Percen Droan]]

----------

[[http:cite:paizo-rzs4349c-176][Paizo forum user "rokeca" shared some plans for "making the Chapter 1 investigation more rewarding and open ended."]]

*** Book 2, Chapter 2: "A Penny Saved" / Bank Robbery
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b2c2
    :END:

#+BEGIN_QUOTE
The robbery itself is okey - The robber's plan is kinda silly and they are bound to fail, but it felt good having the party stop them and save the day anyway. I feel that a GM taking the time to improve this scene could make it into a much better moment than I had.
— cite:reddit-n39df5
#+END_QUOTE

----------

[[http:cite:paizo-rzs4349c-149][jsled went a bit overboard, and detailed the sequence of most of the floats that the Agents would expect to see in their hours of waiting for the robbery to happen.]]

#+BEGIN_QUOTE
I expect my party will stand guard at the PS&T, and BOLO for greasepaint/clowns, or anything that might get them over the fence.

It started off by wanting to provide some drama/tension with some red-herring floats. Taking clues from many other posters here and on reddit, I also wanted to incorporate some entities/foreshadowing from the AP.

[…]

Then it came to some "filler" floats. I figure the Parade has order-of-175 floats, takes about 3 hours, and has a ~12mi route in order to hit all the districts/quarters.
— cite:paizo-rzs4349c-149
#+END_QUOTE

[[http:cite:paizo-rzs4349c-150][Naurgul offered their details]], too, and [[http:cite:paizo-rzs4349c-151][GreatGraySkwid supplemented with a number of business and locations from the /Pathfinder Chronicles Guide to Absalom/]].

-----

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following related to the Bank robbery]]:

- [[https://drive.google.com/file/d/1lJANpfrBnUqBjEZ6d1dL7Hjw-IAcudJg/view?usp=sharing][Kolo Harvan]]
- [[https://drive.google.com/file/d/1dP9BOi4qVz9ID56SF8yWXSFqfZG_tsRR/view?usp=sharing][Dig Widget]]
- [[https://drive.google.com/file/d/1-JKNHAMzTqSM1MHfSGflgHJk0ko4XL0F/view?usp=sharing][Kolo, Copper Hand and Dig Widget in front of the bank vault]]


----------

"GreatGraySkwid" offers…

#+BEGIN_QUOTE
I wanted a tile of a mast w/ sails to drop on the map during the bank robbery
but couldn't find one, so I hacked this together in the GIMP, and thought I'd
share it in case anyone else might want it:

[[https://drive.google.com/file/d/1gURIDnmlGTHOcx6eS8HQ_621Bk_Mknp1/view?usp=sharing][Mast Tile]]

— cite:paizo-rzs434ha-65
#+END_QUOTE

----------

[[http:cite:paizo-rzs43lnt][Paizo forum user "Naurgul" detailed their extensive expansion of the bank robbery investigation.]]

*** Book 2, Chapter 3: "Caught Copper-Handed" / Copper Hand Hideout Takedown
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b2c3
    :END:

#+BEGIN_QUOTE
felt a bit disappointing in my group, because there was an expectation that another investigative part would follow the format of chapter 1. But the infiltration into the copper hands hideout was still an enjoyable dungeon. Our unlucky elf rouge got a minor case of lycanthropy from this part though- nothing a visit to a temple could not fix, but this could have messed with some plans.
— cite:reddit-n39df5
#+END_QUOTE

----------

[[http:cite:paizo-rzs4349c-49][LarsC notes that Chapter 3 appears to be missing a large chunk of XP; some discussion follows about appropriate PFS scenarios to insert to pad out the XP.]]

----------

It's here at the very end of Book 2, Chapter 3 that we learn some pertinent backstory…

#+BEGIN_QUOTE
For the past few months, she explains, the Copper Hand has worked with a murderer named the Skinner and her cultists under threat of violence.
— cite:paizo-aoe-book2#page=27
#+END_QUOTE

*** Book 2, Chapter 4: "Descent into Death" / The Catacombs and The Skinner
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b2c4
    :END:

You will want to get a read on your group's (dis)like of dungeon crawls for this one. The dungeon itself is already large with prewritten encounters, and the AP does have tables for random encounters in addition.

#+BEGIN_QUOTE
As the agents explore the Catacombs, keep track of how long the party is
spending in the dungeon.  For every 8 hours that passes in the game world,
there is an 80% chance the agents run into a random encounter.
— cite:paizo-aoe-book2#page=31
#+END_QUOTE

In the AP's narrative, the missing Graycloaks contingent has been down for "several days"…
#+BEGIN_QUOTE
"It’s been several days since my team of Graycloaks descended into the Catacombs […]"
— cite:paizo-aoe-book2#page=29
#+END_QUOTE

…so being down at least a 1-3 days would not be unreasonable.

#+BEGIN_QUOTE
as a dungeon crawl was too long for our taste. It took us 3 whole 4 hour sessions to get through it. And even with plenty of side quests happening in there it was still a too long section of mostly combat in an otherwise more RP balanced adventure. I would advise any GM's who feel the combat becomes repetitive in their groups to shorten this part- there are enough simple encounters to cut out of it without losing anything important
— cite:reddit-n39df5
#+END_QUOTE

[[http:cite:reddit-oknoo0-h59vm90][u/DocTam suggests pushing holy water to help with the crawl]], generally:
#+BEGIN_QUOTE
I think providing/encouraging the party to get Holy Water is the best way to make the dungeon manageable; since it makes the hardest fights much easier. Books 3 and 4 have been much more manegable difficulty wise; so don't despair too much.
— cite:reddit-oknoo0-h59vm90
#+END_QUOTE

-----

[[http:cite:paizo-rzs4349c-112][Saqcat looks for clarification on how to handle Frefferth the Dullahan's Nightmare; consensus is to treat it like a mount.]]

-----

[[http:cite:reddit-tp09q7]["u/Laz_r_us91" asks for some advice on how to advance the plot at the end of Book 2 Chapter 4 in the face of his party of murderhobos.]]

-----

Paizo forum user [[http:cite:paizo-rzs438k8]["The Rising Phoenix" has produced a number of 3D renders, including the following related to Chapter 3]]:

- [[https://drive.google.com/file/d/11Ps9BMkGwHRzs3XN-2ATeRZq-0KCVKew/view?usp=sharing][The dullahan Frefferth and his unholy steed Polora]]
- [[https://drive.google.com/file/d/1yGO1dQpMfHoLb77gkPJiK_2SGbTeVdhF/view?usp=sharing][The Skinner, Wrent Discaspiron — solo shot of her, partially hidden in the darkness]]
- [[https://drive.google.com/file/d/1OrwQHdx71qeGXapFKLqzDfzbkxj41LOa/view?usp=sharing][The Skinner's Lair (empty)]]
- [[https://drive.google.com/file/d/198etLJ0kwKrieAy4W22Rw2oaq6QJ7VTi/view?usp=sharing][The Skinner, in her lair]]

--------------------------------------------------

Tyrrociese and the Ofalth might need specific handling.

As written, they are both level 10 (APL + 3) creatures. In direct combat with the party, even on their own, these are potentially very deadly encounters.

First, the Ofalth.

There are multiple strategies to account for this.

[[http:cite:reddit-oknoo0-h59zt3p][u/larstr0n (GM, Tabletop Gold podcast)]] strongly advises…
#+BEGIN_QUOTE
I strongly advise, for that monster, taking the book’s advice and having them
engage the ofalth in the next room in battle. In my game,I kept the ooze
focused on the party enough to freak them out, and then strung out a kong vs
Godzilla fight between the two big bads. This approach kept my party
challenges and made for a memorable, cinematic encounter.

— cite:reddit-oknoo0-h59zt3p
#+END_QUOTE

[[http:cite:paizo-rzs4349c-90]["Deriven_Firelion" agrees, the ofalth was brutal, even leveled down.]]
#+BEGIN_COMMENT uncleared-quote-paizo-rzs4349c-90
That elite ofalth was brutal. My players ran into it at lvl 7. I decided to reduce it to a regular Ofalth. It was still brutal.
#+END_COMMENT

[[http:cite:reddit-oknoo0-h5aswqa][u/valahan23 has a number of recommendations…]]
#+BEGIN_QUOTE
I'm currently running AoE and we finished up the catacombs about a month ago. Overall, I'm not a fan of Book 2. I Think the author is the type who loves theory crafting monsters without really thinking about balance. I first noticed this with the copper hand illusionists in chapter 3 that are supposedly level 5, but are a full wizard/rogue. Their spell DC was higher than the party's optimized level 6 wizard. I'd be fine with that if they weren't also a full blown rogue.

I ended up making some changes to to the eldritch ooze TYRROICESE cause I personally think that monster was just poorly designed. This is pretty much entirely was because the ooze template was used without really looking at how oozes work.

- Not all oozes are immune to slashing/piercing (gelatinous cube), but those that are also have the split trait, basically cutting them in half with the HP split between the two. The benefit to splitting them is that you can then have your caster nuke them with AoE. The eldritch ooze got the benefit of immunities without being able to be split. (So I got rid of these immunities on the eldritch ooze)

- Oozes are usually immune to critical hits/precision damage because they are just a blob of ooze so they don't have specific spots to hit for more damage. The eldritch ooze is a large suit of armor basically being piloted by an ooze. (I removed it's immunity to precision damage with the reasoning that the rogue and investigator would be able to find weak points in the armor to attack)

- Lastly I made his pseudopod burst follow the standard MAP rule. As letting a solo encounter have 3 attacks at +23 when the party's AC is in the high 20s was just insane to me. His chance to crit was way above 50% with an average crit doing around 46 damage.

Even with these adjustments it was a super close fight with most of the party unconscious and the remaining members sitting around 10-20 HP when they defeated it.
— cite:reddit-oknoo0-h5aswqa
#+END_QUOTE

Then, Tyrroicese.

#+HTML: <details>
#+HTML:  <summary>the fucking Tyrroicese in book 2 of Agents of Edgewatch is probably the single most bullshit statblock I've seen printed for this game</summary>
#+BEGIN_QUOTE
That said, the fucking Tyrroicese in book 2 of Agents of Edgewatch is probably the single most bullshit statblock I've seen printed for this game, and is a ridiculous encounter for the level it's fought at. I would suggest nerfing it heavily or even just entirely skipping it, as it's got basically no plot relevance and exists solely to grind some PCs down to a fine powder. Let's talk a little about what's wrong with this thing.

It's a PL+3 creature with immunity to piercing, slashing, critical hits, and precision damage. Are you a rogue? Get fucked. Are you an archer? Get fucked. Are you anyone using any weapon that isn't bludgeoning? Get fucked. Did you get lucky and roll two nat 20s on your attacks? Get fucked. It doesn't even split when taking damage it's immune to like other oozes so you can blast it with AoE - nope, it's just immune. Not only that, but it summons an ochre jelly with 1 action and can keep quickening it. It can move 45 feet every round as a free action, ignoring difficult terrain. It can hit three people with its 15-foot reach 2d10+13+1d6 attacks with no MAP for 2 actions. That reach is enough to hit nearly the whole room that it's in. It's got motion sense, so invisibility and darkness and blinding effects won't help. And to top it all off, when it inevitably downs someone, it can subsume them as one action to get 30 HP back and use their fucking feats and abilities. Like, who the fuck designed this and thought it was a fine thing to throw at a level 7 party? As a random irrelevant dungeon boss with no plot relevance other than having eaten one of the stranger guards they were told to find, no less?
— cite:reddit-v3h7h8-ib0hvlf
#+END_QUOTE
#+HTML: </details>

[[http:cite:reddit-pxcik6-hen4otc][Be mindful about what types of damage your party can do, vs. what Tyrroicese is immune to…]]
#+BEGIN_QUOTE
That didn't went well in my group. We had two damage dealers in our group at that time, two fighters. One used a great pick and the other used arrow. So that creature was immune to the main damage dealers of the party.

I had to go out of Encounter Mode and we started a skill challange scene... Up to this day my players remember that fight as "how unfair is PF2e". I wished I have removed that creature from the adventure.
— cite:reddit-pxcik6-hencbbl
#+END_QUOTE

[[http:cite:reddit-pxcik6-hen4otc][u/DragoldC42 has a clever suggestion to lean into a strict interpretation of "motion sense" to help give the PCs a fighting chance…]]
#+BEGIN_QUOTE
Tyrroicese has no senses but motion sense. Therefore I ruled that it will only be able to sense a PC that used a move action on its turn, and a PC that acted in a space Tyrroicese knows about without moving will be hidden from it.

My players figured this out by seeing how the creature reacts (with the help of a recall knowledge from the investigator) and were then able to strategize on that (the monk drew aggro by moving, and the rest stood as still as they could while sniping at the monster)
— cite:reddit-pxcik6-hen4otc
#+END_QUOTE

[[http:cite:reddit-pxcik6-heseed9][u/OmniscientIce's party took 3 attempts to take out Tyrroicese, but with a satisfying conclusion…]]
#+BEGIN_QUOTE
I pulled out DarkSouls boss fight music for the fight. Made sure to really hype up how scary this thing was and that killing it first try isn't everything.

It took my party three attempts to defeat it. […]

When they finally defeated the monster it felt like an incredible achievement that they'd earned together. They got a ton of XP and then found the remaining GreyCloaks in the next room. I consider the fight a highlight of the dungeon. It just needs to be given the attention and respect the foe deserves.
— cite:reddit-pxcik6-heseed9
#+END_QUOTE

----------

[[http:cite:paizo-rzs4349c-48]["Benchak the Nightstalker" highlights a "not enough hands" problem with the Seamer's "Wire Catch" reaction.]]

----------

[[http:cite:reddit-qtjysv][u/Excaliburrover highlights a problem with The Skinner's "Chain Up" ability at the end of Book 2…]]

#+HTML: <details>
#+HTML:   <summary>I'm a bit scared for the Chain Up ability of the Skinner written as is. […]</summary>
#+BEGIN_QUOTE
I'm a bit scared for the Chain Up ability of the Skinner written as is. Restrained is a very "1e" condition and my players are not used anymore to not be able to play their turn. Also the DC to get free is abnormally high so you need a teammate to smash the chain for you.
— cite:reddit-qtjysv
#+END_QUOTE
#+HTML: </details>

Consensus in the thread is that it is broken, and an Escape DC of 32 is more reasonable.

** Book 3: "All or Nothing"
   :PROPERTIES:
   :CUSTOM_ID: node/plot/book3
   :END:

#+BEGIN_QUOTE
This is probably my favorite book in the AP! It was the best at not only giving varied scenarios to play in, but also providing GM tools to expand and enhance those parts to their liking.
— cite:reddit-n39df5
#+END_QUOTE

*** Book 3, Chapter 1: "Street Justice"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b3c1
    :END:

#+BEGIN_QUOTE
which involves resolving a gang war in the docks has some very flavorful NPCs with interesting personalities, one of which (Maurrisa) Became a recurring NPC in my game. This part is also relatively free in its structure and contains some moral choices to make.
— cite:reddit-n39df5
#+END_QUOTE

----------

[[http:cite:paizo-rzs4349d-39]["Billiam8817" makes the good point that Maurissa Jones and the Washboard Dogs are fully aware that they are supplying victims to the Skinsaw's *murder cult*]], which should really put them beyond the pale for being coöperated with.
[[http:cite:paizo-rzs4349d-41]["Evil Paul" agrees, and thinks this needs some "heavy editing" by the GM to make work.]]
[[http:cite:paizo-rzs4349d-40]["O.W." reiterates that the Agents /do not/ have to work with her, and outlines some tactical options for fighting her.]]

----------

[[http:cite:discord-880968862240239708_891395244199915530_945728763734405211]["Naurgul" nit-picks]] that in Narchy's map of the Sweeper Schoolhouse map remake, the windows on the east side of the building are not supposed to be boarded up; narchy responds that it'll be corrected in the "inevitable HD remake!" :)


----------

[[http:cite:reddit-vatz0z]["u/jsled" (your humble editor) relays how they handled Book 3 Chapter 1 in the style of "city-as-a-library" roughly using the Research points subsystem.]]

*** Book 3, Chapter 2: "The House Always Wins"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b3c2
    :END:

#+BEGIN_QUOTE
The casino heist is a very interesting chapter as well. Somehow the casino games given did not translate well into our VTT experience, But the inclusion of so many mechanics and tools to make the heist interesting is just great! I am sure many GM's can make good use of this part- even as inspiration for home games.
— cite:reddit-n39df5
#+END_QUOTE

[[http:cite:paizo-rzs4349d-33][AlastarOG's players are interested in making a copy of the vault key.]]  [[http:cite:paizo-rzs4349d-34]["O.W." provides excuses for saying "no".]]  [[http:cite:paizo-rzs4349d-35]["KyoYagami068" gins up a new Obstacle to fit the bill…]]
#+BEGIN_QUOTE
COPY THE VAULT KEY - OBSTACLE

Infiltration Points 8 (group);

Overcome DC 27 Crafting or Arcana or DC 29 Thievery. At least 2 Infiltration Points has to be gained using Arcana, because the key have arcane runes in it.

— cite:paizo-rzs4349d-35
#+END_QUOTE

----------

[[http:cite:paizo-rzs4349d-42]["Evil Paul" points out the heist represents the police being tasked to break into a legitimate business without any warrants to steal property.]] If you even allow this at your table, what if they just say "no"? Some discussion follows in the thread.
[[http:cite:paizo-rzs4349d-60][One idea is to make Gage Carlyle a mobster or mob banker]], to provide an excuse for the Agents to make their warrantless expedition, allowing the intended "Oceans Eleven" feel, rather than "legalized theft by agents of the State".
[[http:cite:paizo-rzs4349d-65]["Deriven_Firelion" believes very strongly]] this [[http:cite:paizo-rzs4349d-67][does not make any sense with how the rest of the Chapter is detailed]]; they make some good points.
[[http:cite:paizo-rzs4349d-71]["thewastedwalrus" reminds us that the chapter intro describes why the Agents are tasked to behave as they are.]]

You can, too, simply give the Agents a warrant, facilitated by Captain Asilia of Gyr of the Starwatch.

A few months later, [[http:cite:paizo-rzs4349d-85]["Deriven_Firelion" reported how they changed the heist at their table]].

----------

The Svartalfar Killers have a 2-action "Spell-Imbued Blade" that looks very similar to a [[https://2e.aonprd.com/Classes.aspx?ID=17][Magus']] Spellstrike. You might want to adopt the same MAP penalties as Spellstrike (counts as two attacks applied after the Spellstrike) to keep some fairness.

----------

[[http:cite:reddit-renhym][u/Excaliburrover notes that the heist might be very expensive for the Agents, and wonders how the Agents can afford it.]]

*** Book 3, Chapter 3: "Deadly Games"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b3c3
    :END:

#+BEGIN_QUOTE
Gives the characters the task of dealing with a bomb threat in the middle of a gladiator tournament. The scenarios given in the AP itself are quite basic. But the tools provided, the various arena game mechanics and the flavor text-gave me plenty of inspiration to expand this part into a mini tournament arc- which was probably the highlight of the campaign! I highly recommend customizing this part to your group's liking.

I have made another post in the past about a stat problem with the final boss of this chapter- it has a mistake with its AC that makes fighting him a breeze, so you might want to check it out before you run it.
— cite:reddit-n39df5
#+END_QUOTE

*Unofficial Errata*: Oggvurm the Merciless is stated with an AC of 24; it should probably be 34, for a level 14 character.

-----

The AP mentions 2 creatures that do not exist in Pathfinder 2E…

#+BEGIN_QUOTE
Promoted in conjunction with the Radiant Festival, this year’s Blood City
Games boasts a wide array of combatants, both humanoid and non-humanoid.
Creatures such as a two-headed rukh from Osirion, a miniature barometz raised
by druids in Kyonin, and a particularly ornery peluda from the River Kingdoms
are featured on the bill. However, most fans are abuzz about the return of the
iruxi champion, Oggvurm the Merciless
— cite:paizo-aoe-book3#page=48
#+END_QUOTE

[[https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Rukh][A rukh is a giant two-headed vulture-like magical beast, that does exist in Pathfinder 1E.]]

[[https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Barometz][A barometz is a massive green ramlike creature, formed of vines and branches, also from Pathfinder 1E.]]

[[https://2e.aonprd.com/Monsters.aspx?ID=756][A peluda is a large fire dragon of swamplands and bogs, and has been brought forward to PF2E.]]

----------

On reddit, [[http:cite:reddit-r4u5ve][u/GamestingWeasly asks if there are any maps for the Irorium, besides the problematic one from the AP]].  [[http:cite:reddit-r4u5ve-hmj42tw][u/Naurgul quotes the AP, which suggests just using a generic map for a subset of the rather large space]].

** Book 4: "Assault on Hunting Lodge Seven"
   :PROPERTIES:
   :CUSTOM_ID: node/plot/book4
   :END:
*** Book 4, Chapter 1: "The Noxious Retort"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b4c1
    :END:

#+BEGIN_QUOTE
After a quick starting dungeon, this chapter including my favorite dungeon experience of the AP. The blackfinger temple- with the convention in it's upper floor, the puzzles, the interesting monsters, and the reasonable length of it- was a very fun dungeon crawl!
— cite:reddit-n39df5
#+END_QUOTE

*** Book 4, Chapter 2: "The Gervin Legacy"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b4c2
    :END:

#+BEGIN_QUOTE
In which the agents hole up in a haunted safe house to keep a watch over their prisoner, is another interesting chapter. It is divided into parts which feel tower-defense-like (protecting the house from assassins) and a small dungeon crawl in the basement. After cleansing the haunted house and defending it for so long, my players grew attached to the hunting lodge, so I gave them the deed to the house as a gift from the city as thanks for their service. The fact that the hunting lodge does not cointain any toilet in it became somewhat of a joke in our group, and the players announced they are building one in the house after they acquired it.

Small note about the final boss of this chapter- The lesser death is a tough monster- with its disadvantage aura and high attacks, definitely has a potential to kill a PC. My players have managed to exploit its teleporting reaction to trap it inside the house vault (which I stated to be teleport proof). That was a very proud GM moment for me, and I rewarded their creative thinking with a homebrew item that the lesser death bargained for its freedom.
— cite:reddit-n39df5
#+END_QUOTE

*** Book 4, Chapter 3: "A Wonderful Time in Harrowland"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b4c3
    :END:

#+BEGIN_QUOTE
the investigation of harrowland was not interesting for my group. I think that we are all missing the excitement about all the harrow lore in there- so it felt like we were missing half the fun in there. Still, I imagine that for a group with more golarion lore background this could be a nice theme dungeon.

The end of the book features the twist of Reginald framing the party. This did not land that well in my group for a couple of reasons:- The framing plot depends heavily on the Graveraker. About which most of my party forgot by the time they got to this point. Foreshadow it more!- Reginald was obviously evil from the first time they met him. So the reaction was more of "Oh finally he shows he is evil and we an go kick his ass" and not the seemingly intended shock.
— cite:reddit-n39df5
#+END_QUOTE

** Book 5: "Belly of the Black Whale"
   :PROPERTIES:
   :CUSTOM_ID: node/plot/book5
   :END:

#+BEGIN_QUOTE

This book has a nice change of pace from the previous ones- The agents have to work now outside the law, as their badges have been taken from them after they were framed. This gave the players many opportunities to test the moral compass of the characters, and how much are they willing to do outside the law to get their goals. Good RP stuff!
— cite:reddit-n39df5
#+END_QUOTE
*** Book 5, Chapter 1: "Dishonorably Discharged"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b5c1
    :END:

#+BEGIN_QUOTE
deals with gaining enough favor with a crime lord to get the secrets on how to break out the Starborn from the Black Whale prison. Miogimo the crime lord is a good [foil] to the agents, showing how taking justice into their own hands can make them end up. Overall, the chapter gives plenty of roleplay moments to shine.
— cite:reddit-n39df5
#+END_QUOTE

*** Book 5, Chapter 2: "Belly of the Black Whale"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b5c2
    :END:

**Unofficial Errata**: [[#node/errata/b5c2][The /Unfettered Mark/ ritual is an order of magnitude too expensive.]]

----------

#+BEGIN_QUOTE
is about the jailbreak from the black whale prison. The dungeon itself in there is decent, but I needed to put extra work in to make it feel more like a prison. Things like patrol routes, and more details about the day to day management of the prison are lacking the way they are presented in the adventure, I think this section could benefit from some clearer details.

After the prison break, the chapter goes again into a bit of an investigation- where the agents need to find the evidence to clear their names and catch Vancaskerkin, in my group at least we mostly glossed through this part, because some details and npc's presented in the chapter were not working well with the way things occurred in my game. This still seems like a nice scenario.
— cite:reddit-n39df5
#+END_QUOTE

*** Book 5, Chapter 3: "The Rumormonger’s Stronghold"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b5c3
    :END:

#+BEGIN_QUOTE
is the clockwork dungeon of Vancaskerkin. The dungeon itself is quite cool to run. There are different difficulty levels for many encounters, some cool monsters and a few secrets to discover. Reginald himself was a bit underwhelming (At least to the power level of my party), My solution was giving him 2 clockwork abilities at once, instead of just one, to up the danger- worked quite well for me!

Another great thing about the showdown with Vancaskerkin is the alternative win condition against him- instead of killing the villain, the players have an option of resolving the conflict by exchanging his mind using a machine he has build. My party went for this option, and Regi-mouse became a cannon part of our Golarion.

In my opinion, the fight against Reginald felt like it should have been the final one of the AP. He was behind all the troubles the agents faced so far, and by defeating him, clearing their names and redeeming Starborn in the eyes of the public, the agents can feel satisfied with their victory. I'll explain my reasons for this below- but to keep a strong thematic sense, I would advise to finish the campaign here- and avoid part 6. It is a perfectly self-contained ending by this point.
— cite:reddit-n39df5
#+END_QUOTE

** Book 6: "Ruins of the Radiant Siege"
   :PROPERTIES:
   :CUSTOM_ID: node/plot/book6
   :END:

#+BEGIN_QUOTE
Sadly, this last part of the AP is also the weakest in it. It has many interesting ideas, but I'm afraid that as written, it feels off from the rest of the AP, and does not contribute much to the story other than continuing it to level 20.

Firstly, the big villain is someone who was basically invisible to the players! Olansa shows up one time before this book, and this is just to shake the characters hands and go away. At least the AP makes her presence clear enough to the GM before this point, so some foreshadowing can be added- but this is work the GM cannot be aware of unless they kept reading ahead, in detail, and realize Olansa is not properly foreshadowed anywhere. It feels especially hollow facing Olansa after defeating Reginald- who was there plotting since the start of the game, and the characters have a really good reason to hate.

This could be a minor thing should Olansa have been an interesting villain, but as she stands in the book, she has no motivations. Her backstory seemed shallow, it is unclear what, if anything, she would do should the characters fail to dethrone her- the book gives no clue for us. It is unclear what her motivation to take the throne is other than to get more power. This came off to me very one dimensional and boring.

Thanks to a suggestion I saw in the Paizo forums, I altered her in my home game to have the plan to steal the whole city of Absalom into a demiplane, where she can rule it with an iron fist forever. But if you run it as is from the book, she is stated to do next to nothing but sit in her tower and wait to be defeated, other than maybe messing up some beurocracy in the city.

Secondly- This part of the adventure is a major change in tone from the rest of the AP.This is even said on page 3 of the book, where the writer explains the agents are now too strong for criminals to be a problem for them. So they should retrain their social skills and get ready for some extraplanar monsters popping in their way. I feel it's a bad note to finish a campaign focused on using diplomacy to solve problems by throwing hordes of daemons and crazed proteans at the party, and would have much preferred the adventure to stick to the spirit of the previous books.

The chapters themselves are basically 3 big dungeon crawls, with no goals other than to clear them out and get the relevant plot cupon. To the adventure's credit, the design of the dungeons is interesting, but as someone who likes shorter- more concise dungeons, They felt like they are dragging on too much, with plenty of filler fights and encounters over the xp budget. Filler fights are a common thing in any AP, but a book comprised of mostely filler fights is dull to run in my opinion.
— cite:reddit-n39df5
#+END_QUOTE

*** Book 6, Chapter 1: "Runaway Excavator"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b6c1
    :END:

#+BEGIN_QUOTE
has a dungeon happening inside a giant mech. This is a very cool idea, and one that was foreshadowed before with the Graveraker (Though, not too well). The most disappointing thing to me about this part, is that we never got any detail's on how the Graveraker even looks, not to speak about any illustration. Without those, it was hard to make sense of the situation, it felt undefined in a disappointing way.

This dungeon also features the crazed proteans- who are stated to attack the characters on sight, and no alternative means of defusing the situation are given to the players, not even some reasonable solution like promising to free them. I chose to allow such a solution to my players. But without it there was next to no content in this dungeon as most of the rooms are fights with said proteans.

Another thing happening in this chapter is the introduction of Il’setsya Wyrmtouched, who appears out of nowhere to give the party their next quest location, and escorts the party as a GMPC from then on. I chose to leave her out of my game, and tie the plot advancement to other things .GMPC is an idea I dislike, and it felt cheap to me to make the plot development of a story nearing its end happen by a random character appearing out of thin air.

I also think that actually using her as written- where she has some "triggers" later on In the book which cause her to act in a rash way and probably against the interest of the party, and also possibly steal the show in the final bossfight weather the party took her in or not- would be frustrating to deal with as a player. I'm sure some GMs can pull this off well, but I am not one of them.
— cite:reddit-n39df5
#+END_QUOTE

*** Book 6, Chapter 2: "The Radiant Spark"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b6c2
    :END:

#+BEGIN_QUOTE
In this chapter, the party needs to delve into another dungeon- the ruins of an ancient fort constructed by an evil archmage bent on conquering Absalom with an army of mind controlled angels- in order to find the item that will allow them to face the final boss.

Before entering the dungeon, there is a section involving the use of the research mechanics. Where the party needs to balance spending more days getting prepared to the dungeon and gaining advantages in it with the risk of getting caught by the deamonic agents of Olansa.The way my game played out; the agents had too much stress on them to be able to research calmly for days as the adventure assumes- so we largely ignored this mechanic. But this is a cool concept.

The dungeon itself is nice. Though for some weird reason, the majority of creatures and hazards in it have access to some variation of the prismatic spray spell. So the dark tone of the location, at least in my group, was hurt a bit by having rainbows assault the characters every fight.Also, there seems to be an issue with the room size in the map- for example a room meant to house 3 gargantuan creatures is physically too small to contain them.

The boss of this chapter- a fallen planetar- has a problem in his stats. He possesses regeneration that can only be deactivated by evil damage, something which the lawful good party, Which the players guide instructs to make, will have no access to, meaning the PCs are unable to kill him in most conceivable groups. I decided to ignore this fact and just treat it as fast healing, not sure if there was a good reason to have it there in the first place.
— cite:reddit-n39df5
#+END_QUOTE

*** Book 6, Chapter 3: "The Gray Queen's Tower"
    :PROPERTIES:
    :CUSTOM_ID: node/plot/b6c3
    :END:

#+BEGIN_QUOTE
Dungeon number 3 in this book is an assault on the tower where the main villain is sitting and… going slowly insane, waiting to be killed. Really this calls for a change from the GM.For me, I upped the stakes by having Olansa launch a daemon attack on the citizens of the city- and the players have to stop her before she kills everyone.

The cool part about this dungeon, is the boss rush nature of it. To get to the final boss, the agents combat against the reincarnations of the 3 bosses from earlier in the campaign. (There are also many filler fights in this chapter, which serve no purpose in my opinion- the players are level 20, they don’t need to grind anymore.)

As written the boss rushs are cool fights, with enough to challenge the 20th level characters, the only thing I would change in there is to enlarge a bit the rooms they are found in, because they are too small for a dynamic fight to take place in them.

The problem is, these fights are not going to run as written, unless your players specifically avoid it there is an easy way to steamroll this entire dungeon-The artifact the players gained in the end of chapter 2 allows them to indefinitely mind control all the daemons present in there. I let my players have some fun with the pokemon-esqe gameplay of capturing all the demons (actually demon capturing sounds more like SMT but I digress) , until I had to ask them by the end to not use the artifact they were given- or the game would not be fun.

Olansa as a final boss is also quite unimpressive. Her ability to turn invisible even to see invisibility feels cheap, and the poison on her weapon- Teats of death- Is irrelevant to the combat because of its 1-minute onset time. Even with her artifact equipped she is just not a very interesting or challenging opponent as written. I heavily altered it for my session and would advise doing the same to any other GM to make sure the ending of the campaign is properly epic.
— cite:reddit-n39df5
#+END_QUOTE

* Resources
  :PROPERTIES:
  :CUSTOM_ID: node/resources
  :END:
** Chat

- [[https://discord.gg/NRGPSfdy][The Pathfinder 2e Foundry VTT Community Discord]] has a [[https://discord.com/channels/880968862240239708/891395244199915530]["Agents of Edgewatch" thread in the "#ap-hub" channel]].

** Actually Plays
- [[https://rollforcombat.com/category/podcast/agents-of-edgewatch/][Roll for Combat : Agents of Edgewatch podcast]]
** Missing Persons Casefiles
   :PROPERTIES:
   :CUSTOM_ID: node/resources/missing-person-casefiles
   :END:

On their blog, Paizo published "[[https://paizo.com/community/blog/v5748dyo6shbn?Edgewatch-Cold-Case-15561-Evidence-A][Edgewatch Cold Case #1556.1, Evidence A]]" in July 2020, a letter discovered under a table in the Tipsy Tengu, a piece of evidence regarding one of the missing persons that form the basis of the mystery in Book 1.

On the Paizo forums, [[http:cite:paizo-rzs4349b-388]["OmegaZ" summarizes the missing persons as outlined by the book]], and [[http:cite:paizo-rzs4349b-389]["Naurgul" offers a list of detail beyond the handful of Missing Persons cases described in the AP…]]

#+BEGIN_QUOTE
Date: 2 Sarenith 4720

Name: Archibald Knight & Minera Frum

Description: Owner and vet of menagerie. They used to elope together but always returned on the same day. Their last outing was a week ago and they still haven't showed up.

Witness: Remy, zookeeper

-----

Date: 1 Sarenith 4720

Name: Kemeneles

Description: Taldan wizard. Studied at Arcanamirium decades ago. Possible connection with another mage from his days there. Case should be moved to Learned Guard, it's their jurisdiction.

Witness: Eunice, apprentice wizard

-----

Date: 28 Sarenith 4720

Name: Cody

Description: homeless

Witness: Esker of Ormuz

GM Notes: Esker did not witness the disappearance with her own eyes but knows Cody -despite her warnings- used to beg the passerby to take him with them and feed him / house him. She suspects the Aspis Consortium is behind the disappearance. 

-----

[…]

— cite:paizo-rzs4349b-389
#+END_QUOTE

Inspired by this, [[http:cite:paizo-rzs4349b-482][jsled offers their list, as well.]]

--------------------------------------------------

[[http:cite:paizo-rzs4349b-450][GreatGraySkwid's players created a full-on murderboard to track the details. :)]]

----------

[[http:cite:paizo-rzs4349b-485][On the Paizo forums, "Chan Wakhan" links to some player handouts for the missing persons case notes.]]
This was also [[http:cite:reddit-veaqrj][posted to Reddit]].

** "Eyes on Absalom"

[[http:cite:paizo-rzs4349b-477][GreatGraySkwid "reworked" the front page of Eyes on Absalom for their campaign…]]
#+BEGIN_QUOTE
I have reworked the Eyes On Absalom front page to tie into my campaign, with the conceit that it's published the morning after the Dreaming Palace raid, and so just covers pre-Chapter 4 events. My intent is to use it in Lavarsus's debrief, that he's furious they apparently leaked details of ongoing investigations to Vancaskerkin and made themselves out to be heroes in the process (something that is entirely Reginald's doing, not that it matters). Should be fun, and wanted to share before my session this Saturday (constructive criticism encouraged!):
[[https://drive.google.com/file/d/1DPPWEhbZhmpJtD9cQNCL24TH7onKTeXk/view?usp=sharing][Eyes On Absalom, Desnus 20, 4720]]
— cite:paizo-rzs4349b-477
#+END_QUOTE

[[http:cite:paizo-rzs434ha-42]["AlastarOG" created "an elaborate stream of [articles]" for their game, for your inspiration.]]

** Journal Entries / Notes / Handouts
   :PROPERTIES:
   :CUSTOM_ID: node/resources/notes-and-handouts
   :END:
*** Book 1 Chapter 4: Pratchett's Journal

[[https://www.reddit.com/r/Pathfinder2e/comments/p1479k/agents_of_edgewatch_spoiler_handout_for_book_1/][u/corpboy has shared a 16-page original creation that is Pratchett's journal]],
encountered next to his dungeon in the basement of the Dreaming Palace. It
includes references into some other world lore, as described in the reddit
thread.

*** Book 2 Chapter 1: Investigation Leads

[[https://www.reddit.com/r/Pathfinder2e/comments/qynogu/spoilers_aoe_investigation_leads/][u/perryhopeless shared some OC art for the investigation leads from Book 2 Chapter 1.]]

** Maps
   :PROPERTIES:
   :CUSTOM_ID: node/resources/maps
   :END:
*** narchy's maps
    :PROPERTIES:
    :CUSTOM_ID: node/resources/maps/narchy
    :END:

User narchy has provided a [[https://drive.google.com/drive/folders/1LZdj40ot34lfxoGbzu5aTgnAKQ1M8_eY?usp=sharing][full collection of all the maps, "remastered"]]. They're quite nice.

#+BEGIN_QUOTE
I have finished the final book of the awesome Agents of Edgewatch AP, which brings to an end 7 months of working on these maps! I may go back and tweak a few of the earlier ones, but uiltimately I am really happy with how these turned out.

You can download them (books 1-6) from [[https://drive.google.com/drive/folders/1LZdj40ot34lfxoGbzu5aTgnAKQ1M8_eY?usp=sharing][Google Drive]] for you to use as you wish.

The maps for all books are also available as [[https://foundryvtt.com/packages/aoe-maps-remake-by-narchy][Foundry VTT module]], containing all the scenes with walls/doors/windows etc.

As always, feedback welcome! If you want to contribute to my Pathfinder book buying addiction, a coffee is always appreciated - [[https://www.ko-fi.com/narchymaps][www.ko-fi.com/narchymaps]] :)

Assets are from [[http://www.forgotten-adventures.net/][www.forgotten-adventures.net]]
— cite:reddit-on03uu-h5oij50
#+END_QUOTE
*** Edgewatch Station
- [[http:cite:paizo-rzs434ha-8][paizo.com forums: "Bast L."]]
- [[http:cite:paizo-rzs434ha-11][paizo.com forums: "Sovaka"]]
*** Tipsy Tengu (Book 1, Chapter 1)

- [[http:cite:paizo-rzs434ha-12][paizo.com forums: "malnourish"]]
- [[http:cite:reddit-r8zm44][reddit.com: "u/Kraydez" provides a link to their remake of the Tipsy Tengu map, in DungeonDraft]]
*** Knights Marvelous Menagerie (Book 1, Chapter 1)

- [[http:cite:paizo-rzs434ha-13][paizo.com forums: "malnourish"]]

*** House of the Planes (Book 1, Chapter 3; Book 5, Chapter 1

Note that while no map is provided when this location is encountered in B1C3, a proper encounter is located here in Book 5, and a map is provided there.

- [[http:cite:paizo-rzs434ha-29][paizo.com forums: "EdwinM"]]

*** Copper Hand Hideout (Book 2, Chapter 3)

- [[http:cite:paizo-rzs434ha-38][paizo.com forums: "Drental"]]
- [[http:cite:paizo-rzs434ha-40][paizo.com forums: "Sodatron"]]

*** Catacombs (Book 2, Chapter 4)

- [[http:cite:paizo-rzs434ha-31][paizo.com forums: "EdwinM"]]

** Audio / Background / Ambiance

[[http:cite:discord-880968862240239708_891395244199915530_950816529119871026][In Discord, "Naurgul" outlines their audio selections for Book 1:]]

#+begin_quote
for general Absalom vibe I am using the album Antakya (by the band Quandro Nuevo) https://youtu.be/Rhw5djhjbvg?list=OLAK5uy_kD5znh6GPMgEkCpeCIt7DsmSXnCHvpa6g
for example the tracks "Antakya No.1" and "Antakya No.2" for strolling through the city, "Inside the Orthodox Church" for temples, Dadachi No.1 & No.2 for meetings, especially in social places like taverns, "Antiochia" for when mysteries arise etc.
for book 1 specifics I've used:
Lavarsus chastising the PCs: full metal alchemist (old series) OST 3 "carefree" https://youtu.be/KUGfSGCmVGA
tavern brawl: antakya quadro nueveo "dance through the tavern" https://youtu.be/Rn58xhYA-IY
patrol: mediaeval baebes Worldes Blysse "Erthe upon erthe"
cockatrice: Naruto Movie 2 Official Soundtrack "21 - Suna Bunshin"
owlbear: Shadow of the Colossus - "Grotesque Figures" Piano https://youtu.be/q-rXHfu_-OM
the bastard: Over the Garden Wall OST "03 - You Have Beautiful Eyes"
detective bolera theme: Dexter OST "10 - Can't Hide"
pagoda strike: Tooth and Tail OST "01 The Food of Beasts" https://youtu.be/GXnImIYY68k
pagoda fight: full metal alchemist ost 1 "12 - infiltration"
undercity exploration: Full Metal Alchemist Brotherhood OST 1 "18 - Beneath the City" https://youtu.be/5UJ6U_wwMbo
undercity fight: Celeste B-Sides "02. Old Site (Black Moonrise Mix)" https://youtu.be/6eeIEMOQw4s
house of planes: planescape torment ost tavern, bastion ost sole regret, tooth and tail ost fuel of the firebrand
murder hotel: the normal floors were basically all from the over the garden wall soundtrack (for example my players loved this combat music https://youtu.be/XCTsH7yXdxg and the auntie laurna theme was used for ralso exposition)
the basement was a mix between over the garden wall and dexter soundtrack
#+end_quote

** Landing Pages
   :PROPERTIES:
   :CUSTOM_ID: node/resources/landing-pages
   :END:

- [[https://www.reddit.com/r/Pathfinder2e/comments/pa523d/landing_page_for_my_agent_of_edgewatch_campaign/][u/faultypanda has a nice landing page, which garnered praise from Erik Mona in the comments]]

- [[http:cite:reddit-tg9m0p][u/redijedeye created a lovely interactive landing experience for their AoE party, using Foundry]]

** Art, Fiction and Original Content
   :PROPERTIES:
   :CUSTOM_ID: node/resources/art-fiction-oc
   :END:
*** "Wrent's Confession", Book 2/3 Transition by KM Kovalcik ("u/zombkat")

On reddit, [[http:cite:reddit-pq90e5][KM Kovalcik (u/zombkat) posted a bit of fiction detailing the crimes of Wrent Dicaspiron]], set in the interstitial between Books 2 and 3.

#+BEGIN_QUOTE
My players are about to move onto book 3, and I was unhappy with Wrent confessing a whole bunch of story stuff off-screen. My players did not interrogate her themselves, and I wanted some time to do some fiction writing. I wrote out her confession as if being interviewed by a priest of Sarenrae who wanted to see if it was possible to redeem her, or at the very least determine if her ramblings were truthful.
— cite:reddit-pq90e5
#+END_QUOTE
*** "Agents of Edgewatch as a 90s TV show", from "narchy"

narchy created the following videos for their group:

- [[http:cite:paizo-rzs434ha-48]["I made my party a little video to celebrate their exploits in Book 1!"]]
- [[https://www.reddit.com/r/Pathfinder2e/comments/qye7ly/agents_of_edgewatch_as_a_90s_tv_show_made_to/][In celebration of getting to book 3: "Edgewatch Nights"]]

*** "Agents of Edgewatch - Murder Hotel" by "BlackZack"

[[http:cite:paizo-rzs43bxb-1]["BlackZack" shares a delightfully-creepy video in the motif of Book 1 Chapter 4.]]

*** Vancaskerkin by "u/higoram"

[[http:cite:reddit-sxyxm8]["u/higoram" posts some OC art of Reginald Vancaskerkin.]]

** Journals and Blogs
[[http:cite:reddit-usyacc][In May 2022, u/Kwintak announced a Facebook journal/blog on running the AP]], which appears to have stopped updating in December 2022.
* Unofficial Errata
  :PROPERTIES:
  :CUSTOM_ID: node/errata
  :END:
** Player's Guide

A curious sort named [[http:cite:paizo-rzs43a5f][Efrixes askes on the Paizo Forums]] about a "hamster-like creature is on page 2 in the player's guide?". [[http:cite:paizo-rzs43a5f-7][Ron Lundeen clarifies that it was "cut for space".]]

** Book 1, Chapter 1
   :PROPERTIES:
   :CUSTOM_ID: node/errata/b1c1
   :END:

- The name of the pub in the first encounter is [[http:cite:paizo-aoe-book1#page=89][referred to as "the Arcadian" in the description of Pratchett on page 89 of Book 1]], but it is the "Tipsy Tengu" everywhere else, of course.

** Book 1, Chapter 2
   :PROPERTIES:
   :CUSTOM_ID: node/errata/b1c2
   :END:

- The encounters in Chapter 2 are spec'ed for a level 2 party, so level the party to level 2, no matter what the guide at the front of the book says.

- [[http:cite:paizo-rzs4346l-4][The wings on the Dragonfly Pagoda are backwards.]]

** Book 2, Chapter 3
   :PROPERTIES:
   :CUSTOM_ID: node/errata/b2c3
   :END:

#+BEGIN_COMMENT
- Link to Plot Notes re: Seamer's "Wire Catch" ability
#+END_COMMENT

- [[http:cite:paizo-rzs4349c-48][The Skinsaw Seamer's "Wire Catch" reaction requires a free hand they cannot easily have.]]

** Book 2, Chapter 4
   :PROPERTIES:
   :CUSTOM_ID: node/errata/b2c4
   :END:

- In D15 (Sanctuary), one of the cadets is listed as "Kirsta Malopedes" but referred to later in the text as "Cadet Pennington".
  — cite:paizo-aoe-book2#page=41

- War Razors are listed in stat blocks as doing "piercing" damage; it should be "slashing".
  #+HTML: <details>
  #+HTML:   <summary>OK, I thought I was losing my mind reading through the Sanctum, last night […]</summary>
  #+BEGIN_QUOTE
  OK, I thought I was losing my mind reading through the Sanctum, last night, but War Razors are typoed consistently in this book as being Piercing weapons. AoN has them as Slashing, as is, of course, the only reasonable option.
  — cite:paizo-forums-rzs4349c-59
  #+END_QUOTE
  #+HTML: </details>

- The Escape DC for The Skinner's "Chain Up" ability seems absurdly high. — cite:reddit-qtjysv

** Book 3, Chapter 3
   :PROPERTIES:
   :CUSTOM_ID: node/errata/b3c3
   :END:

- In E11, the room is described as:

  #+BEGIN_QUOTE
  Two long, tin tubs, each covered in rust but filled with boiling water, occupy the northwest corner of the room.
   — cite:paizo-aoe-book3#page=55
  #+END_QUOTE

  Tin does not have iron, and thus not rust.

- [[http:cite:paizo-rzs4349d-48][Oggvurm the Merciless is stated with an AC of 24]]; it should probably be 34 for this Level 14 creature.

** Book 5, Chapter 2
   :PROPERTIES:
   :CUSTOM_ID: node/errata/b5c2
   :END:

- GM's consensus is the cost for the /Unfettered Mark/ ritual – approximately
  12,000 gp per character – is way out of line with [[https://2e.aonprd.com/Rules.aspx?ID=581][Treasure By Level]] if
  characters are regularly spending their gold, and especially if using
  something like [[https://2e.aonprd.com/Rules.aspx?ID=1357][Automatic Bonus Progression]] where free currency and saleable
  gear is even less present. Knock a zero off the end of it.

* Colophon
  :PROPERTIES:
  :CUSTOM_ID: node/colophon
  :END:
** Licensing

This work is generally licensed as [[https://creativecommons.org/licenses/by-nc-sa/4.0/][Creative Commons By-Attribution Non-Commercial Share-Alike, International, Version 4.0]].

This work is a collection of quotes, links and original content regarding running the Paizo Adventure Path /Agents of Edgewatch/.

Copyright of the quoted forum posts and comments is held by the respective original authors.

Block quotes appearing herein have been licensed by the authors, generally in terms "compatible with Creative Commons By-Attribution, Share-Alike, Non-Commerical, version 4.0". See "meta" for more details.

This work – "The GM's Guide to /Agents of Edgewatch/" – uses trademarks and/or copyrights owned by Paizo Inc., used under [[https://paizo.com/community/communityuse][Paizo's Community Use Policy (paizo.com/communityuse)]]. We are expressly prohibited from charging you to use
or access this content. "The GM's Guide to /Agents of Edgewatch/" is not published, endorsed, or specifically approved by Paizo. For more information about Paizo Inc. and Paizo products, visit [[https://paizo.com/][paizo.com]].

** Sources and Contributing

The source repository of this Guide is https://github.com/jsled/gms-guide-to-agents-of-edgewatch.
Contributions as pull requests are welcome. Contributions in other forms will be considered.

The primary hosting of this Guide is https://asynchronous.org/gms-guide-to-agents-of-edgewatch.

** Editor

The editor of this Guide is [[http://asynchronous.org/jsled][jsled]].
